### ISSUE TITLE
[duplicate] duplicate to different persistence space duplicates in place

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1007]
Reported by a VISTA user when copying from one users folder to another users folder.  I am able to reproduce in master by copying from my items to scratchpad.

1. include `'examples/scratchpad/bundle' in main.js .  (Need multiple persistence spaces for this bug to show)
2. Create and save a new object in "my items". (you can use an existing object if you have one)
3. Right click on the object, select duplicate, and choose "scratchpad" as the destination.
4. Click "ok".

Expected outcome: the object will be duplicated to the "Scratchpad" folder, and it will be visible in the "scratchpad".
Actual Outcome: a duplicate of the object is created in the original folder, and the "scratchpad" folder is not changed.

**Comment by larkin** [comment]
@VWoeltjen @charlesh88 @akhenry How do you feel about investigating this in Kress?  It's blocking a user (really, a set of users) from using the system as intended; I would considering it critical.

**Comment by VWoeltjen** [comment]
I would agree with that assessment (critical); I'll investigate this

**Comment by VWoeltjen** [comment]
Part of the issue is that validation is rejecting a cross-space duplicate. The Locator is restoring the previous selection.

This isn't getting reflected in the TreeView and I'm not sure why. There's a watch that I'd expect to fire that isn't firing. I'm suspicious that this behavior reflects the same underlying problem as #1008.

To resolve _this_ issue, though, I believe it will be sufficient to change whatever logic is causing validation to fail (and to make sure that cross-space Duplicate works as intended)

**Comment by larkin** [comment]
Verified in testathon 2016-06-16-- duplicate across spaces now works properly.
