### ISSUE TITLE
[timeconductor] Bounds do not update when selecting date in calendar

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1018]
Time conductor bounds do not update when a date is selected from the calendar picker. 

Reproduction steps:
1. focus date input field
2. open calendar picker
3. select date

Expected outcome: bounds change
actual outcome: bounds do not change.

It's a specific pattern of focusing before selecting the time.  If you don't focus, it works inconsistently, but more frequently than if you focus before you select.

**Comment by VWoeltjen** [comment]
Observing this in testathon 6/16/2016 as well.

My steps to reproduce:

1. Load application, wait for initial navigation state to resolve so time conductor appears
2. Click on date picker for start time
3. Pick the day before its current value
4. __Observe:__ Text field updates to match this value, but visible TC bounds do not
5. Reopen date picker, choose a different day
6. __Observe:__ Now both text field and TC bound update
7. Repeat step 5 and observe 6 again, seemingly any number of times. (e.g. seems consistent at this point)
8. Click the text field associated with the date to focus it, but don't type anything
9. Reopen date picker, pick another day
10. __Observe:__ Text field updates, but TC bound doesn't.
11. Repeat step 5 and observe 6 again, seemingly any number of times. (e.g. seems consistent again)

Expected behavior for Step 4 and 10 is as described in Step 6.
