### ISSUE TITLE
[Documentation] Missing development dependencies

### ISSUE THREAD

**Issue by jesusprubio** [nasa/openmct#1032]
A couple of dependencies we need to generate the documentation are not present in the "package.json" file. To reproduce it:

``` sh
npm run otherdoc
```

<img width="930" alt="captura de pantalla 2016-06-20 a las 18 57 38" src="https://cloud.githubusercontent.com/assets/2753855/16203425/84b215ac-371a-11e6-825e-4ad9b43916ae.png">

Error content: _Cannot find module 'nomnoml'_

The same happens for the module "canvas". Of course we could install both globally but I think it has more sense to install them locally.

**Comment by akhenry** [comment]
@jesusprubio Thanks for bringing this up. We'd like to keep them out of package.json because they have dependencies that don't reliably install, and tend to be system configuration dependent. 

I totally agree, a local install is more appropriate here. These dependencies can be installed locally via
```
npm install nomnoml canvas
```

The best approach here might be to add this install step to the build script, `build.sh`. If you would be interested in doing that, feel free to file a PR, we love community contributions!

**Comment by jesusprubio** [comment]
Sure, but I'm starting a new branch then :). Thanks!

**Comment by akhenry** [comment]
@jesusprubio I'd like to keep this open for tracking purposes. I'll assign it to you if you don't mind.

Thanks again for your help!

**Comment by akhenry** [comment]
Assigned to @jesusprubio
