### ISSUE TITLE
[Examples] Kerbal Space Program integration

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1064]
It would be great to be able to display telemetry from [Kerbal Space Program](https://kerbalspaceprogram.com/en/). There are plugins for KSP (such as https://github.com/richardbunt/Telemachus/) that enable telemetry to be streamed from KSP via web sockets and other means. 

This would be great both as an example for developers of how to integrate with a real-time data source, but also for the purposes of demonstrating Open MCT in presentations, etc.

**Comment by larkin** [comment]
I few developers I have talked with have looked into https://github.com/KSP-Telemachus/Telemachus as it provides a websocket for real-time telemetry from kerbal. It's a good starting point for any integration.  

With that plugin, we'd need to write a telemetry provider to expose telemetry streams for objects using the Telemachus websocket API.  Additionally, we'd need an object provider to expose telemetry objects for all of the API strings as documented here:  https://github.com/KSP-Telemachus/Telemachus/wiki/API-String

Down the road it would be great if the Telemachus API can enumerate all all of the API strings it supports (perhaps as a hierarchy of vehicles -> parts -> measurements)  so that we can expose even more data.  

I've commented in https://github.com/KSP-Telemachus/Telemachus/issues/59 noting that it would be nice to load the dictionary in one go.
