### ISSUE TITLE
search filters not shown or cleared

### ISSUE THREAD

**Issue by RCarvalhoNASA** [nasa/openmct#1087]
Testathon 20160718, While testing #1065 , I found that when I cleared the search, the filters in the pull-down were still selected (which I would not expect).  Further, it did not actually filter what I was seeing in the tree view.  Lastly, when I went to do another search, those filters were immediately applied.  I would expect that when one clears a search, it should clear the filters as well, or, if one has filters applied with no text search, it should somehow still be filtering the tree.

**Comment by charlesh88** [comment]
As discussed during Testathon triage 7/18/16, CH to write up a UX recommendation and review with stakeholders.

**Comment by charlesh88** [comment]
So there are several elements to @RCarvalhoNASA's  comment:

1. **Clearing search doesn't clear filters**. The problem here is that the control that clears the search input also exits search mode - it's been overloaded. A better (and more commonplace) design pattern is to have two controls: the clear input control and a Cancel Search button. The "clear input" control just clears entered text, but keeps the user in search mode. It doesn't clear the filters. The Cancel Search button clears the filters and exits search mode. 
1. **The view wasn't being filtered** That sounds like a straight up bug: are you saying you filtered only by object types, and were seeing results that included types not in your filter? If so, could you send some screenshots or provide example search terms and filters? I can't duplicate that. 
1. **Doing another search reapplies filters** Hopefully number 1 above describes a more expected UX.
1. **Filter the tree without entering text in the search input** I totally agree, we should have this functionality - this is something I've wanted for a while. There is a big problem with the way that search is currently implemented though that may be an obstacle to doing this: rather than the query asking for all Display Layouts that match the entered query, instead, we search for all types that match the query, then filter the results to only display Layout-type objects. So, to allow the user to find all Layouts, we'd have to issue a search that returns *everything*, then filter it. That sucks and we shouldn't do that. I will file a separate issue to cover code changes to search to allow this.

**Comment by RCarvalhoNASA** [comment]
In regards your point 2 above, that was specifically in the case where I had done a search, included filters, then cleared the search.  The filters were still apparently active (I could see them checked in the pulldown, and when I started entering new search text they were applied), but the tree view was showing everything (not just filtered object types) while there was nothing in the search text field.

**Comment by charlesh88** [comment]
@RCarvalhoNASA Thanks. So distilling this down:

1. Provide a "Cancel Search" action that clears search filters. 
1. Allow filtration by type without the user having to enter anything in the search input.

The first item is pretty trivial, Charles can do this. The second item is more involved, and needs to be scoped.

**Comment by akhenry** [comment]
> 1. Provide a "Cancel Search" action that clears search filters.
Targeting Niven for this functionality

**Comment by charlesh88** [comment]
Cancel Search is completed and merged with #1106. Will tag or file a separate issue for "Search by type" and then close this issue.

**Comment by charlesh88** [comment]
Search by Type is covered by #1092. Closing this issue.
