### ISSUE TITLE
[API] Ensure correctness of adapter layer 

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1123]
Test, review, and revise adapter logic for new API (#999) to ensure correct behavior (at least to normal, post-prototype standards)

May need to split this into sub-tasks based on issues identified.

**Comment by VWoeltjen** [comment]
Likely want to address this after - or perhaps concurrently with - handling API review feedback from #1122

**Comment by akhenry** [comment]
#1131 introduces an adapter layer that bridges between the mutation events hosted on the `MutationCapability`  and the mutation events exposed by the `MutableObject` in the new object API. Some old style views will need to be updated to listen for mutation events on objects in order to stay in sync with changes made from the new API.

**Comment by VWoeltjen** [comment]
Working on this in the context of #1124
