### ISSUE TITLE
[Edit] Object Saved message needed on successful save

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1180]
The various save actions should indicate to the user with a notification when a save is successful. `NotifcationService.info` can be used for this purpose.
The Save actions affected are
- `SaveAction`, 
- `SaveAndStopEditingAction`,
- `SaveAsAction`

**Comment by BogdanAlexandru** [comment]
I noticed that while `info` notifications get auto-dismissed, they still show up in the notifications list in the indicator. So the user will get to see something like this:
![Imgur](http://i.imgur.com/wURYKdE.png)
I figure that'd be a lot of noise during editing. This seems to happen because the `NotificationService` only minimizes inside `dismissOrMinimize()`, and there's a comment there saying

```
//For now minimize everything, and have discussion around which
//kind of messages should or should not be in the minimized
//notifications list
```

I guess this is the right time to have that discussion! I'm assuming we don't want the _Save Successful_ noise in the notifications list. But we want to have _Save Failed_ notifications in the list. Am I right?

**Comment by VWoeltjen** [comment]
> I guess this is the right time to have that discussion!

I think you're right about that; tentatively placing in Rajaniemi, which begins Monday.

**Comment by charlesh88** [comment]
Yes, in general we don't want routine success messages (esp. those that would give us a high signal-to-noise ratio) showing in the messages list. We want stuff that is out of the ordinary that the user may and/or does need to pay attention to because something isn't working as normal.

**Comment by akhenry** [comment]
Yeah you're totally right, we don't want these sorts of messages to linger around indefinitely. My tendency would be to auto-dismiss `info` messages by default unless the `autoDismiss` is explicitly set to false.  Except that the logic currently [appears to be broken](https://github.com/nasa/openmct/blob/7439d949c472e76d7119dbf748120d636384c671/platform/commonUI/notification/src/NotificationService.js#L238) and an `autoDismiss` value of false would be overridden with true 😬

**Comment by BogdanAlexandru** [comment]
> Except that the logic currently appears to be broken and an autoDismiss value of false would be overridden with true 😬

You're right, I'll start there.

**Comment by akhenry** [comment]
closed by #1258

**Comment by charlesh88** [comment]
@akhenry Could you add some testing notes here prior to our Testathon today?

**Comment by charlesh88** [comment]
Testathon 2017/04/20 Added elems to a Telem Table clicked Save and Finish, saw notification. Verified fixed.
