### ISSUE TITLE
[Build] Evaluate type-checking (TypeScript, Flow)

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1246]
Evaluate (e.g. via prototype) and, if obviously beneficial, add build support for type-checking. Candidate solutions include TypeScript and Flow.

Things to consider in this evaluation:
- Prevalence of available tooling
- Impact on debugging
- Code clarity
- Anything else that seems like it would improve or harm development workflows

**Comment by VWoeltjen** [comment]
Dumping some links here for future reference

TypeScript vs Flow comparisons (a lot of these out there!):

* https://djcordhose.github.io/flow-vs-typescript/2016_hhjs.html
* http://michalzalecki.com/typescript-vs-flow/
* https://github.com/DJCordhose/flow-vs-typescript
* https://github.com/niieani/typescript-vs-flowtype
* https://shinesolutions.com/2017/01/05/typescript-flow-and-the-importance-of-toolchains-over-tools/

http://danluu.com/empirical-pl/ has a great summary of empirical work comparing dynamic typing to static typing. It's dense, but my general takeaway was that there isn't a lot of evidence that static typing offers benefits relative to dynamic typing. Static typing may be helpful in learning to use APIs (esp. when they are complex) and catches a rather modest percentage of bugs.

**Comment by larkin** [comment]
wontfix at this time.  Can address at later time.

**Comment by DusterTheFirst** [comment]
Being that it is a later time, It would be good to revisit this idea. Type checking, especially at this scale can save a lot on technical debt since problems with weird function signatures/unknown APIs disappear when they are self-documented like with what typescript/flow can do. Migration to typescript/flow can be done gradually since it is able to mesh well with existing javascript, allowing typescript/flow to slowly be integrated into the whole project.

With a project of this massive scale, moving to a type-checked language may be a huge feat and infeasable given the already existing structure of the project. A smaller undertaking may be to, either manually or generated from the existing jsdoc, create typescript typings files, allowing plugin developers an in-ide documentation of the API as well as allowing developers to integrate openmct into their own typescript/flow projects.

[linked here](https://github.com/DusterTheFirst/openmct-picopilot/blob/main/web/src/openmct.d.ts) is my (unfinished) attempt to bring a large chunk of the user-facing API into typescript for consumption by my own plugin/telemetry data source.
