### ISSUE TITLE
[Inspector] Inspector does not show changes to object properties

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1276]
Eg. Browse to an object. From a context menu, select "Edit Properties". Change the name, or notes field. Notice that in the inspector, the name and notes fields are not updated.

Probably object model sync issue. Inspector needs to listen for changes.

**Comment by VWoeltjen** [comment]
Since we're seeing this in a few places, should consider making `mct-representation` responsible for listening for changes so that we can solve this for legacy views once. (Unless there's a big performance impact for doing so.) 

Going forward, UI elements should listen for changes if they want to stay up to date

**Comment by akhenry** [comment]
Will be a lot of listeners, but if there's not a major performance impact it's a quick and universal solution.

**Comment by larkin** [comment]
Will address in context of https://github.com/nasa/openmct/issues/1282.

**Comment by larkin** [comment]
The inspector is watching `$scope.ngModel.selectedObject`, not something that mct-representation could catch, IMO.

A change to mct-representation here would not necessarily work unless it were to brute force change objects and refresh just about everything representation on mutation, which I imagine would break everything.

**Comment by VWoeltjen** [comment]
There are changes to `mct-representation` that fix some issues (e.g. #1303) but not this one, which I guess is because of the nature of the watch.

This might be a good instance to migrate a legacy component (the inspector) to an implementation more appropriate to the new API/paradigm (potentially as a non-Angular view.) Could also simplify integration of the `inspectors` extension point (part of #1307) in the process.

**Comment by larkin** [comment]
Fix as a bug, expect to rebuild inspectors shortly.

**Comment by larkin** [comment]
Reported again in #1596:

> @dhrubomoy May 28, 2017, at 8:09 PM
> Edit a clock for example, and the inspector properties don't get updated then and there.
Click another item, then click on the clock again. Now we will see the new updated time. But it should be updated immediately.
> 
> ![inspector_](https://cloud.githubusercontent.com/assets/12648587/26535243/9090bcc4-43f9-11e7-9da9-1b95d757122b.gif)

**Comment by larkin** [comment]
Still an issue, just needs to listen for mutation and update.

**Comment by larkin** [comment]
@dtailor90 Wanna take a look at this?

**Comment by dtailor90** [comment]
Fixed in PR #1744, closing
