### ISSUE TITLE
"error saving x" message while viewing tables of non-editable objects

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1382]
When viewing a historical or real time table of a non-editable object (e.g. a telemetry point provided by a plugin) the user sees "error persisting <object>" messages.  This appears to be due to the table view mutating the object to apply default column selection and the mutation kicking off persistence, which fails because the object does not support mutation/editing.

Reproducible with VISTA telemetry channels, I would expect it is also possible with WARP telemetry points.

**Comment by VWoeltjen** [comment]
I see two high-level approaches to solving this:

1. Mutation for non-editable objects is contradictory; instead, there should be console errors for this circumstance to alert developers that they are breaking the rules (we could show errors to the user too, but they should be less confusing / more appropriate to the circumstance.)
2. Treat all objects as mutable but treat non-editable objects as non-user-modifiable and non-saveable. Include checks at appropriate points (e.g. TransactingMutationListener?) such that non-editable objects simply get ignored while building transactions.

Thoughts? I'm leaning toward Option 1, as Option 2 seems to open the door for other confusing behavior. But I am also disregarding Options 3...n

**Comment by larkin** [comment]
This behavior came about as a shortcut, I recall @akhenry pointed out this behavior in the initial table implementation, but that was before the auto-persist changes and I felt it was a reasonable shortcut at the time.  I agree that the proper solution at this time would be not to mutate non-mutable objects (option 1).

**Comment by akhenry** [comment]
Of those options, Option 1 makes more sense so I'd be inclined to go for that. The table can use some other mechanism for communicating table column state to the inspector, and vice versa.

I also reported this behavior in the context of the Telemetry Tutorial (#1379) which does deferred object population via mutation. It's often useful to be able to mutate otherwise immutable objects during initialization, and use the standard mutation event channel to reflect those changes in the UI. What's the proposed solution here if we go with Option 1? Direct manipulation of the model + some other event mechanism to signal readiness of the object?

**Comment by larkin** [comment]
I'd consider using mutation to allow "delayed loading" of an object a hack.  In the new API, that is the responsibility of a custom composition provider.  I don't want to conflate "loading a model from persistence" with "mutating a model".

**Comment by akhenry** [comment]
@larkin ok, great, sounds like we have all the cases where we were previously doing mutation of immutable objects covered then.

The telemetry tutorial needs to be updated to use a composition provider as part of #1248

**Comment by charlesh88** [comment]
Testathon 2017/04/20 Could not duplicate this problem - verified fixed.

**Comment by larkin** [comment]
Was tested in VISTA, verified.
