### ISSUE TITLE
Items do not display across different devices or browsers

### ISSUE THREAD

**Issue by DyingEcho** [nasa/openmct#1461]
After downloading and installing OpenMCT I have created a test layout containing a few items and saved. I can access the items on the same browser (Vivaldi, Chromium-based) but when I try to access them from a different browser (Safari) or on a different device (Android TV) the items do not appear.

I am new to OpenMCT but I would rate this as a major loss of functionality.

**Comment by BogdanAlexandru** [comment]
This is because out of the box Open MCT uses the browser's local storage to persist info. See the bottom left indicator:
![Imgur](http://i.imgur.com/0y7EH1C.png)
The local storage provider is here: [LocalStoragePersistenceProvider.js](https://github.com/nasa/openmct/blob/e0b69868519e11910a828d9fc339dd1a8572794e/platform/persistence/local/src/LocalStoragePersistenceProvider.js)

Technically all you have to do to avoid this problem is use a different provider that persists data at the server level. That way, it will be available from any device that connects to your server.

**Comment by DyingEcho** [comment]
Wonderful, thanks!

**Comment by akhenry** [comment]
@BogdanAlexandru Thanks! 😄
