### ISSUE TITLE
Allow changing text size in Fixed Position

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#1496]
Users request that we can customize the size of text in a fixed position display.

**Comment by charlesh88** [comment]
I'll do a UI sketch, but this is very straightforward. This would be a great Help Wanted.

**Comment by charlesh88** [comment]
Finally, here's the sketch: [Open MCT UI sketches v2.3.0 fixed position text size only.pdf](https://github.com/nasa/openmct/files/1096049/Open.MCT.UI.sketches.v2.3.0.fixed.position.text.size.only.pdf)

**Comment by charlesh88** [comment]
@psarram Working on styling for text-size-1496 now.

**Comment by charlesh88** [comment]
### Testing notes

1. Create a new or edit an existing Fixed Position Display object.
1. Add a Text field to the work area. After entering text in the dialog and while it's selected, note that there is a new font size control in the toolbar:
![screen shot 2017-09-29 at 10 59 06 am](https://user-images.githubusercontent.com/1056412/31029117-5bfed5b4-a505-11e7-8635-0b7c8acdaca9.png)
1. Change the font size to another value. Observe: the field should immediately change size. If the font is too large for the text field's bounding box, it will be clipped. This is correct behavior and is by design.
![screen shot 2017-09-29 at 11 00 55 am](https://user-images.githubusercontent.com/1056412/31029167-8f5860ba-a505-11e7-8fbe-8adc10163c5c.png)
1. Add a telemetry object (like a Sine Wave Generator) and change its text size.
1. Save the Fixed Position object, and make sure that the size of the text elements has been persisted properly.

**Comment by VWoeltjen** [comment]
Verified during testathon 2017-10-05
