### ISSUE TITLE
[Documentation] Additional documentation on Telemetry API is necessary

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1501]
* Telemetry data: What is the expected structure of telemetry value objects?
* Telemetry metadata: esp. hints, priorities

**Comment by RGD2** [comment]
Step 0 from the old tutorial at  https://nasa.github.io/openmct/docs/tutorials/#telemetry-adapter is missing from the new tutorial.

**Comment by larkin** [comment]
@RGD2 The telemetry server is out-of-context for an Open MCT tutorial, thus the new tutorial has a sample telemetry server so that the tutorial can focus on the integration points without getting bogged down in the details of historical and streaming telemetry services.  Does that make sense?

**Comment by RGD2** [comment]
@larkin I hate to tell you this, but I feel **very** strongly that your answer is not acceptable. You're over-simplifying openmct-tutorial . 

I'm trying to evaluate OpenMCT, and to do so, I need to connect the control systems I have in my labs here to it. 

This really does seem entirely **in context** for the tutorial *from my point of view as a new user*, since the  https://nasa.github.io/openmct/getting-started/ "Integrating with telemetry sources" section links directly to this new tutorial, and the information I require is only available under the old one - linked above in my previous response.

I was really surprised that I couldn't readily find this information, since the last time I'd had some time to put into speculative development like this (not often) I had got so far as to see it, and I recalled appreciating the level of detail at the time. I eventually found it again by googling for it, so that means at least that the current 'getting-started' documentation is incomplete OR that it really should be part of openmct-tutorial, even if just as a footnote. 

It turns out not to be very complicated, and I'm sure from the point of view of a 'front-end' developer, it is out-of-context -- but for any *practical* new deployment of openmct it is pretty critical, and openmct-tutorial is the obvious starting point for such, especially just for evaluation.

And all that's really necessary is to carry over step0 of the old documentation, which is actually quite lucent. 

A more direct link to https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers 
wouldn't go astray.

It'd be nicer still to include an arduino+ethernet shield or esp8266 example which can act as the source -- but I see there are several examples of Websocket servers like that already:
 https://github.com/ejeklint/ArduinoWebsocketServer  
 https://github.com/razerbeans/WebSocket-Arduino  
 https://github.com/Links2004/arduinoWebSockets  

Adapting one of the above to be a openmct-tutorial-telemetrysource (separate git repo) would make sense too.

**Comment by larkin** [comment]
@RGD2 Point noted.  We will be expanding the tutorials to include the same scope as the old tutorials while also all being integrated, and you can expect step-0 to be broken out as a separate tutorial in the future.  I just can't give you a timeline for that.

Many of our deployments are to environments where a websocket or http telemetry service already exists, and so the tutorial is intended to help an integrator develop the necessary adapters to talk to those services.

Regarding the arduino services,  if you wanted to adapt one of those servers and publish it and maintain it, we would be happy to link to it as an example; otherwise it's going to sit in our backlog of tasks for some time.  If you'd like to create a separate issue for that, I can tag it as help-wanted to see if others in the community might be interested in tackling such a task.

**Comment by RGD2** [comment]
@larkin Excellent, thank you!
No urgency for me, It will help new users in future though. 

Re: arduino service: Tempting, I'll see how I go.

I think it's reasonable to link to existing examples 'in the wild'. There don't appear to many alternative compatible sources yet, but this one caught my eye, and I think deserves mention as an example of one in Python (and under MIT license) : https://github.com/uiuc-cs-ksp/krpc_openmct_telemetry_server  
Especially since Python's quite common for researchers and students, perhaps more so than JS.

**Comment by larkin** [comment]
@RGD2 Oh very interesting.  Someone had also completed a kerbal integration with the previous version of the API here: https://github.com/hudsonfoo/kerbal-openmct and instead of writing their own adapter, they simply integrated with the existing KSP Telemachus mod.  That plugin now needs to be updated based on the newest APIs, but it is useful to look at.  I'll mention that to @bryan-lunt.

**Comment by bryan-lunt** [comment]
Yes, I've seen that. I'm not a huge fan of Telemachus, I prefer kRPC. With a kRPC solution, I can potentially get almost any state information I want out of KSP. If I want to monitor the temperature of one particular radiator panel, I can do that. Unfortunately, my telemetry server is no longer plug-n-play compatible with the new API and new tutorials, but that can be easily solved later. These tutorials are very understandable.

When will there be new tutorials about writing MVC components that can be registered via the new API? How do we write consumers of telemetry data? (IE, custom display panels.) I would like to have at least an overheat light that can be programmed with a custom javascript function to turn different colors under different conditions, based on one or more telemetry stream.

**Comment by larkin** [comment]
Understood-- Telemachus had a limited number of telemetry points available and didn't do what I'd desire; I was looking for something that at a minimum would give stats at the level of flight engineer.  I think kRPC is likely a better option and will have more datatypes, as you say.  

For the MVC components, we hope to have those in a month or two.  We do have some prototype APIs which are close to what will be publicly supported if you'd like to get started earlier than that.

> I would like to have at least an overheat light that can be programmed with a custom javascript function to turn different colors under different conditions, based on one or more telemetry stream.

This is a request we've had from mission customers and this could be a stellar contribution.

Feel free to email us at arc-dl-openmct@mail.nasa.gov if you want to try the prototype APIs or for any questions that don't fit cleanly into github issues.

**Comment by larkin** [comment]
Closing this as resolved, will continue to improve in response to more specific issues.
