### ISSUE TITLE
[Time Conductor] Restore time conductor state in URL

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1550]
Previously the time conductor state (bounds, offsets, time system, mode) were reflected in the URL, and changes to the URL state were reflected in the conductor. This functionality has been removed as part of [recent refactoring]() and will need to be restored. This functionality previously resided in the `TimeConductorController`, but it probably makes sense to move this to the `ConductorViewService` which is not reloaded on navigation changes.

**Comment by VWoeltjen** [comment]
Old code for this is [here](https://github.com/nasa/openmct/blob/0785129b7fe2af452cbd2fe380d9a563692dcc98/platform/features/conductor/core/src/ui/TimeConductorController.js#L138-L177). To avoid breaking existing bookmarks, URL format should be identical to what was used here.

**Comment by VWoeltjen** [comment]
URL format, working backward from the above:

Constant | Key | Description 
----|----|---
MODE | tc.mode | Key for mode, default "fixed"
TIME_SYSTEM | tc.timeSystem | Key for time system
START_BOUND | tc.startBound | Numeric value of lowest timestamp (fixed mode)
END_BOUND | tc.endBound | Numeric value of highest timestamp (fixed mode)
START_DELTA | tc.startDelta | Numeric value of start delta (start_bound = now - start_delta)
END_DELTA | tc.endDelta | Numeric value of end delta (end_bound = now + end_delta)

Bounds are only applicable when mode is fixed; otherwise, deltas are applicable.

**Comment by VWoeltjen** [comment]
Notes from work-in-progress:

* There is no direct analogy for `mode` in the current time API
  * For backwards compatibility, could use combination of timeSystem and mode, then iterate through Time Conductor options to identify one that matches.
  * Going forward (e.g. when writing URLs) it doesn't make sense to keep mode and timeSystem. `tc.option` would be better, but the list of options given to the TC plugin as configuration will need keys to make that work reliably.
* Both bounds and deltas can be written to Time API directly; that should be straightforward.

**Comment by larkin** [comment]
For your first point of "no analogy for mode", true-ish.  

`fixed` -- corresponds to "no clock"
`realtime` -- corresponds to a specific clock.
`lad` -- corresponds to a specific clock.

I *think*, given my knowledge of our current deployments, that it is safe to slightly alter what `mode` previously meant, to mean something different.  The only case I know where people are actively creating links does not use modes of `realtime` or `lad`-- only fixed.  The argument for not wholesale changing `tc.mode` to `tc.clock` is that it's not a direct mapping so it's actually better in the old format.

**Comment by larkin** [comment]
@VWoeltjen I'm a little confused by:

> * Update controller to use same model as URL handler
>   * Likely want to move at least some functionality from TimeConductorController to TimeConductor

Perhaps this issue should be titled "[Time API] restore previous 'time api state in URL' functionality"?

The time conductor controller is quite intentionally separate from the Time API.  Goal here is mapping the previous url parameters to the Time API, without the conductor, as that may not be installed in a given deployment.

**Comment by larkin** [comment]
The idea being that the Time Conductor will read the existing state from the time API (so will read the state set by this code) when the application starts.  If no state is set when the application loads, then the time conductor will set defaults, and this code will update the url accordingly.

**Comment by VWoeltjen** [comment]
> @VWoeltjen I'm a little confused by:
>
> > * Update controller to use same model as URL handler
> >   * Likely want to move at least some functionality from TimeConductorController to TimeConductor
>
> Perhaps this issue should be titled "[Time API] restore previous 'time api state in URL' functionality"?

Good point, I'll adjust my thinking. It would be better to make this totally external to the TC plugin, which I hadn't really considered.

To clarify the confusing comment: Bounds/deltas fit into Time API nicely. For timeSystem and mode, it's true that I can implement these functionally with the Time API directly. However, doing so creates a problem when trying to reflect that state in the mode selector of the Time Conductor; that selector is just populated by [menu options from plugin configuration](https://github.com/nasa/openmct/blob/master/API.md#time-conductor-configuration) which don't directly correlate. I considered doing a `find` to identify a matching menu option, but that seemed hacky/error-prone. (At minimum, the combination of timeSystem/mode is not guaranteed to be unique; that's a somewhat unrealistic edge case, though.) So by "shared model" I really just mean menu selection. 

There's also the problem of "what if no menu option matches that timeSystem/mode pair" but now that I think about it, it's really no different that "what if there is no such timeSystem" or "what if there is no such mode," so that's just a case where we'll need reasonable fallbacks/logging.

Having said all that, the benefits of handling this external to TC look worth it. I'll move forward with that (along with the `find` approach for menu options) and see how it goes.

**Comment by larkin** [comment]
The TC Plugin already implements the behavior for menu options, so no need for you to handle that.  The TC Plugin is a plugin; the Time API should have zero knowledge of the plugin, the Time API should not interact with the plugin outside of the public interfaces defined in the Time API.

In the short term, users won't be linking to options the time conductor doesn't support because the way they generate urls is by manipulating the time conductor.  As they won't be able to select something not supported by the time conductor, they can't get to this invalid state.

At this point, I don't want to fix a bug we don't have reproduction steps for, and if we were to write reproduction steps (which would involve specifying url parameters manually), I'd advocate for a separate ticket where we can discuss the impact and defer the resolution if reasonable.  Given that it's akin to someone taking off the lid and turning some screws, and because I expect another iteration of UX changes to the TC plugin, I would vote to defer fixing that bug.

**Comment by VWoeltjen** [comment]
> The TC Plugin already implements the behavior for menu options, so no need for you to handle that.

Oh, why [yes](https://github.com/nasa/openmct/blob/master/platform/features/conductor/core/src/ui/TimeConductorController.js#L117-L123) it [does](https://github.com/nasa/openmct/blob/master/platform/features/conductor/core/src/ui/TimeConductorController.js#L142-L143).

The complicated roads I go down to recognize that things are simple...

**Comment by larkin** [comment]
@vwoeltjen 😍
