### ISSUE TITLE
Critical dependencies listed as devDependencies in package.json.

### ISSUE THREAD

**Issue by ajpower** [nasa/openmct#1622]
Open MCT requires packages like RequireJS and gulp.js to function. However, these packages and others are listed under `devDependencies` rather than `dependencies`. This is problematic when Open MCT itself is used as a dependency in an application, as certain package managers (such as Yarn) will not look at a dependency's `devDependencies`.

It is possible that I am not understanding the intended workflow of using Open MCT in an application.

**Comment by larkin** [comment]
@ajpower Open MCT is designed to be distributed after the build steps execute (i.e. after being built and published to npm), which is why gulp and requirejs are `devDependencies`.  Until we start publishing versions to NPM, you have to add the pre-build step to your project.

If you are depending on Open MCT, you can add a `postinstall` script that installs and builds Open MCT with `cd node_modules/openmct && npm install`.  Take a look at the [openmct-tutorial package.json](https://github.com/nasa/openmct-tutorial/blob/master/package.json#L8) for an example of how Open MCT should currently be utilized.

Let us know if you have any other questions.
