### ISSUE TITLE
[Fixed Position] Provide default position for telemetry points

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#17]
If a fixed position view contains a telemetry element in its composition but does not have at least one position/size for that telemetry element defined in the view's configuration, a default one should be chosen and displayed. If the user Edits and saves this, it should be stored to the view's configuration.

To see similar behavior, edit a Display Layout and drag objects from the Library to the Elements pane (or, from Browse mode, create new objects in the Layout directly.) Observe that these are assigned positions in the Layout view automatically. A similar positioning approach (starting from top-left, cascading down) should make sense for Fixed Position view as well.

**Comment by shivamndave** [comment]
Progress made on branch open17 (https://github.com/shivamndave/openmctweb/tree/open17)

Current condition: Currently the Fixed-position controller will add
a default position based on the index value during browse mode, 
however when deleted using edit toolbar, the element is not actually
deleted from the fixed position view and will reappear after navigating
away. If deleted from the element list, it will actually delete, but will
create an undefined "ghost" of the element deleted in the fixed position view 
that is only seen as an outline in the domain object's edit fixed-position view
because it remains in the elementProxyById and elementConfigById list, but
not the ids list of elements in the telemetry object.

The original problem is partially solved, however this has resulted in other bugs.
The branch will not be merged with master.

**Comment by charlesh88** [comment]
Suggest we hold on this for now pending New Edit mode.

**Comment by deeptailor** [comment]
Closing as Fixed Position display was deprecated and functionality was moved to Display Layouts
