### ISSUE TITLE
[YAMCS] Feedback on Yamcs Plugin

### ISSUE THREAD

**Issue by evenstensberg** [nasa/openmct#1701]
[Yamcs-OpenMCT-plugin](https://github.com/ev1stensberg/yamcs-openmct-plugin) is nearly done, but needs some feedback. Also run into some issues of distribution that I hope some of the people from the core team could help out with. 

Here's an initial todo, that I'd love feedback on:

1. Options ( what should we give users the possibility to modify? ) 
2. Minor errors in the terminal ( download the repo, integrate it in the openmct-tutorial and watch yourselves ) 
3. Realtime working properly with timeline? Looks a bit buggy, need verification on that, it's related to  the previous bullet point
4. Documentation, what should it include? 
5. Additional feedback
6. Add project structure, linting etc...

**Comment by larkin** [comment]
Thanks for your work on this @ev1stensberg! Some feedback:

1. Package it in a UMD module-- that way it can be loaded with commonjs, require, webpack, whatever.
2. Build dependencies (axios) into module so that it has no external dependencies. Users want it to "just work" out of the box.  The easier you make installation, the more likely it will get used.
3. Document how to install it in a project.  e.g. npm install, add to index.html, `openmct.install(YamcsPlugin(options));`

As far as options, you should support:

* configuring YAMCS host and protocol (e.g.`https://my-yamcs-server.com`)
* configuring YAMCS instance (e.g. `simulator` or `my-flying-satellite`).

I'll look into the realtime functionality, not sure what's the deal there.

**Comment by ev1stensberg** [comment]
Thanks for the feedback! Did everything you mentioned, the only thing left now, is to fix the realtime. Here's the error from OpenMCT @larkin 

![skjermbilde 2017-09-15 kl 22 19 43](https://user-images.githubusercontent.com/16735925/30501783-0df4adf4-9a64-11e7-964d-0b14cd26bc2a.png)

**Comment by ev1stensberg** [comment]
Could close in favor for #1331 , error needs resolve first

**Comment by akhenry** [comment]
@larkin This is the same error we're seeing with that data table in VISTA. Created issue to investigate it - https://github.com/nasa/openmct/issues/1817
