### ISSUE TITLE
TelemetryAPI.prototype.standardizeRequestOptions: "Cannot read property 'key' of undefined"

### ISSUE THREAD

**Issue by cuongquay** [nasa/openmct#1722]
When missing time system plugin, it causes an error of "Cannot read property 'key' of undefined"

Test case:
```
            openmct.install(openmct.plugins.UTCTimeSystem());
//            openmct.install(openmct.plugins.Conductor({
//                menuOptions: [
//                    {
//                        name: "Fixed",
//                        timeSystem: 'utc',
//                        bounds: {
//                            start: Date.now() - 30 * 60 * 1000,
//                            end: Date.now()
//                        }
//                    },
//                    {
//                        name: "Realtime",
//                        timeSystem: 'utc',
//                        clock: 'local',
//                        clockOffsets: {
//                            start: -25 * 60 * 1000,
//                            end: 5 * 60 * 1000
//                        }
//                    }
//                ]
//            }));
//            openmct.time.clock('local', {start: -THIRTY_MINUTES, end: 0});
//            openmct.time.timeSystem('utc');
```

**Comment by akhenry** [comment]
@cuongquay Thanks for your input and for pushing a PR for this issue. Just a reminder, we need that signed Contributor License Agreement so that we can merge your contribution.

You're absolutely right, Open MCT needs to handle this case more gracefully than it currently does. This impacts on a number of different parts of the system and we have a tracking issue where we are discussing this - #1624

Most of the telemetry we work with is temporal in nature, which is why we currently have this dependency in our code. In Open MCT, if your telemetry has timestamps, then a time system allows Open MCT to glean meaning from those timestamps. This doesn't mean that you need to have the Time Conductor enabled, but it does mean that a time system relevant to those timestamps will need to be enabled. eg. if your timestamps represent UTC time, then the UTCTimeSystem will need to be installed.

That said, Open MCT need not be restricted to temporal telemetry only, so we do need to handle the absence of time systems more gracefully.

**Comment by cuongquay** [comment]
Hi Andrew,

Thanks for your reminding me. I attached my signature on the 2nd page
of Contributor
License Agreement follow this email.
If you need anything more, just let me know.

Kindly Regards,

Cuong

**Comment by cuongquay** [comment]
So what should I do now? I didn't follow up this project yet. On the other hand, I just want to close the issue, the pull requuest what I created before. Now it's confusing for me what should I do.

Kindly regards,

**Comment by akhenry** [comment]
My apologies for not being clearer. I was suggesting an alternative change that you could make that addresses the same problem, but in a way that is consistent with our revised thinking on the role of the Time API.

If you have the time and inclination to make the change, great, if not, that's also fine. We appreciate the time that you have already spent on this issue.
