### ISSUE TITLE
[Tree] Drop down arrow remains even though object has no children

### ISSUE THREAD

**Issue by dtailor90** [nasa/openmct#1826]
For desired solution, see: https://github.com/nasa/openmct/issues/1826#issuecomment-387476466

To recreate:
1. Create a new Object
2. Add another object as a child of Object 1
3. Notice the drop down arrow next to Object 1 in tree (Works as intended)
4. Remove child object, but notice that drop down arrow is still there. 

![image](https://user-images.githubusercontent.com/13260688/33635428-c9a095fc-d9cc-11e7-89a6-93d6ed675efb.png)

**Comment by ev1stensberg** [comment]
So if there's no children in the parent, the arrow icon shouldn't be collapsed? Tried to reproduce, but seems to work here, no leftover arrow for the child, just the parent having the same state when there's no children

**Comment by aayusharora** [comment]
Hi @dtailor90 @akhenry 
The problem is not only that, if I create a new Object, without creating any other object as it's child, it is still is created with the arrow.

The expected solution should be to add and delete arrow based on whether there is any child element or not.

I will like to work on this @akhenry

**Comment by akhenry** [comment]
> So if there's no children in the parent, the arrow icon shouldn't be collapsed? 

My understanding of the issue is that if there are no children there should not be an arrow visible at all. @charlesh88 is this the intended behavior here?

This is the line of code that creates the arrow - https://github.com/nasa/openmct/blob/c1b2db848a6badfac3f335bd35b5ed889f65c918/platform/commonUI/general/res/templates/tree-node.html#L46 I suspect the problem is that the conditional statement only checks if `model.composition !== undefined`. If it's defined, but empty, then this will evaluate to true, rendering the arrow.

@ev1stensberg You were looking at this first, so you've got first right of refusal here if you want to fix it. Let me know if not, and @aayusharora can take over.

**Comment by ev1stensberg** [comment]
I'm just thinking that this should be intended behavior, cause it implies that you can do something to the map and it shows interactivity. If someone else wants to do it, go ahead 😊

**Comment by dtailor90** [comment]
@akhenry - after some investigation there is a bit of jquery that does the adding and removing of that class and it is not entirely handled by angular. Adding a conditional causes some side effects. eg not showing children even when present, and not expanding the tree.

**Comment by aayusharora** [comment]
@dtailor90 it is actually angular in the form of jqLite, that is doing this here. I am working on this, will fix this soon.

**Comment by aayusharora** [comment]
@akhenry @dtailor90 Will you please check this :)

https://github.com/nasa/openmct/pull/1904

**Comment by larkin** [comment]
Custom composition providers can use other attributes for composition; Checking for model.composition is not guaranteed to tell you if an object has composition.  A more foolproof check is `!!openmct.composition.get(domainObject)`.  However, that only tells you if an object supports composition; it does not tell you if it is empty or not.  To check if it is empty or not is a asynchronous `load` call, which is pretty expensive especially when done for every visible element in tree.

We need a cheaper check for "supports composition & is empty"; loading composition does not scale well.

**Comment by aayusharora** [comment]
Hey @larkin Can you check #1904 
I have solved it 70% 
Stuck in the remaining 30%

Your help will be really appreciated.

**Comment by akhenry** [comment]
Given the technical difficulties in addressing this issue, I think we need to reassess the basic UI paradigm here. Because counting children for everything in the tree is expensive let's just show the expander arrow for anything that supports composition. If it's empty, it shows nothing. This is what MacOS does -

<img width="771" alt="screen shot 2018-05-08 at 10 16 28" src="https://user-images.githubusercontent.com/4215777/39772034-f1e91b10-52a8-11e8-891c-2f9b7c0a027b.png">

The top folder has children, the second and third folders do not.  The second folder is expanded, with no children. The third folder is collapsed.

**Comment by aayusharora** [comment]
@charlesh88 @dtailor90 @akhenry 
Which of the domainObject will not have a composition property.
I think every element has it as it is there in the API,
correct me if I am wrong.

Means, If I will create any element, I will be seeing composition Array  in it.
![screen shot 2018-05-11 at 6 18 21 pm](https://user-images.githubusercontent.com/12194719/39925042-ce251f7a-5547-11e8-9b6c-7aadbf39c7bc.png)

**Comment by akhenry** [comment]
@aayusharora great question. Some objects store their composition in a `composition` array on the object itself, but this is not universal. There are also 'composition providers' which can provide asynchronous composition. Eg. if an external service needs to be queried to fetch the children of an object.

The most reliable way to test whether an object supports composition is to use the composition API. The Composition API can be queried for composition and will return undefined, eg -

eg.
```
var hasComposition = openmct.composition.get(object) !== undefined;
```

As well as checking the .composition attribute, this method will also look for composition providers.

The openmct API is exposed to controllers etc as the 'openmct' service. This can be defined as a dependency in the [associated bundle.js](https://github.com/nasa/openmct/blob/062ba4a9d7023291c3dd2f7ae4e587c551a2b569/platform/commonUI/general/bundle.js#L236)

**Comment by aayusharora** [comment]
@akhenry @dtailor90 
Thank you so much for the help.
Finally got it and fixed it here. Looking for my first PR merge at NASA :)

https://github.com/nasa/openmct/pull/1904/files
