### ISSUE TITLE
[Summary Widget] Can't add/edit rules

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#1858]
Discovered during VISTA R3.4 testing; can't add rules or edit default displayed value/color of a summary widget. The relevant controls just don't appear.

<img width="855" alt="image" src="https://user-images.githubusercontent.com/1685764/34366093-28c3dbb8-ea4c-11e7-8429-01020277d5dc.png">

**Comment by dtailor90** [comment]
Is this after adding telemetry?

**Comment by charlesh88** [comment]
That was my question too. If you haven't added at least one telemetry, you should see a message indicating such - which I don't see in these screen shots.

**Comment by VWoeltjen** [comment]
Yes, there was one telemetry element there at the time.

**Comment by VWoeltjen** [comment]
After a brief skim it stands out that there are a lot of Zepto selectors involved in building the UI for the summary widget form; wonder if maybe these selectors don't all work under the snow theme?

**Comment by dtailor90** [comment]
hmm Interesting. I wonder wether dependencies are working properly? Any Error messages?

**Comment by VWoeltjen** [comment]
No error messages on console. The message asking me to drop telemetry shows up when there's no telemetry, but once I add telemetry there is no Default Rule

**Comment by charlesh88** [comment]
I'm also seeing this on the uphill test server. When I add telem elems, I don't get any rules, and the telem elem doesn't appear in the Elements pool. If I save, I see the added telem elems contained in the widget in the tree. 

Going in to edit the widget, and leaving the widget (either with Save or lose changes) I do see console errors: Uncaught (in promise).
![screen shot 2017-12-27 at 3 09 58 pm](https://user-images.githubusercontent.com/1056412/34395807-5223eb84-eb18-11e7-8bbc-5fe418729e41.png)

**Comment by VWoeltjen** [comment]
Thanks for capturing that console error; I had filters turned on in Chrome without realizing it.

[This line](https://github.com/nasa/openmct/blob/284dec490344107452d75675b81262a6316ea0d4/src/plugins/summaryWidget/src/ConditionManager.js#L159) looks to be where the exception occurs. I believe there's a race condition where a composition map (`compositionObjs`) is expected to be populated before certain telemetry results come back. The problem is probably not reproducible with local storage (although may be able to reproduce it by adding an artificial delay)

**Comment by larkin** [comment]
You can reproduce this with sine wave generators by changing [GeneratorProvider's request method](https://github.com/nasa/openmct/blob/1ad5094b7229e4246d8a0666dff63e7141fdf395/example/generator/GeneratorProvider.js#L74-L79)  to:

```javascript
    GeneratorProvider.prototype.request = function (domainObject, request) {
        return Promise.reject([]);
    };
```

The VISTA telemetry provider doing something unexpected: if it receives no results for a given query, it rejects the promise.  I believe rejecting a promise the the correct way to handle erroneous responses, but "no data available" is not necessarily erroneous.  Changing the VISTA provider to resolve the promise with an empty array would resolve this bug.

**Comment by larkin** [comment]
The rejection mentioned above does cause the error message that Charles logged, but that's not the root cause.

The SummaryWidget uses the status capability to determine if the object is being edited, and it seems there is a bug with the status capability and object namespaces.  The statusService has an entry for `"<object-prefix>:<object-id>"`, but the status capability uses `domainObject.getId()` which returns only `"<object-id>"`  I'm not exactly sure how it gets to this state, but this is what I see:

![screen shot 2018-01-02 at 3 37 44 pm](https://user-images.githubusercontent.com/226503/34499222-eb7790ce-efd2-11e7-81a6-c29bf7106264.png)

As a result, [summeryWidget.editing is set to false](https://github.com/nasa/openmct/blob/1ad5094b7229e4246d8a0666dff63e7141fdf395/src/plugins/summaryWidget/src/SummaryWidget.js#L203-L210), and the [rule section gets hidden](https://github.com/nasa/openmct/blob/1ad5094b7229e4246d8a0666dff63e7141fdf395/src/plugins/summaryWidget/src/SummaryWidget.js#L216-L226).

I think the solution here that would be inline (for now) with our other displays is to use the editorCapability to check if the object is being edited instead of the status listener.  And figure out why the status listener isn't working.

**Comment by larkin** [comment]
Ok, digging more, it's because the summary widget doesn't properly translate the new-style identifier to an old-style identifier before querying the object API.  Quick candidate fix incoming.

**Comment by VWoeltjen** [comment]
Verified fixed, able to add telemetry and edit the summary widget rules thereafter with this change.

> VISTA
> * Version 3.4.0-prerelease-2
> * Revision 5e3aefdbee504fd74547005c432925ee7786762f
> * Built 2018-01-02 17:40:34.851-0500

**Comment by charlesh88** [comment]
Testathon 2/21/2018: Verified fixed
