### ISSUE TITLE
Integrating User Management not found

### ISSUE THREAD

**Issue by KarthikaMohan** [nasa/openmct#1876]
Cannot provide different login for users using this application.
If anything for integrating different users is available in this project then please tell me.

**Comment by VWoeltjen** [comment]
Thanks for filing the issue. The short answer is that we haven't implemented support for this yet, at least not in a way we will maintain going forward. Our [road map](https://nasa.github.io/openmct/about-open-mct) has Identity Providers planned for late 2018, which would support this kind of integration.

In the meantime there is an `example/identity` directory showing how to integrate minimal user identification with internal interfaces. All it really does is provide a username for the current user (which could be read from a server, for instance) which will show up in the bottom-left and get recorded as a "creator" property on objects created by that user. This is an approach that would be unsupported and will likely break in the future, but could be useful as an interim solution depending on your needs.

I'll close this issue since it's accounted for on our road map, but if you have further questions please feel free to ask.
