### ISSUE TITLE
[Summary Widget] Can't add rules

### ISSUE THREAD

**Issue by vicfx** [nasa/openmct#1883]
Observed during VISTA R3.4 Testing. Steps to reproduce:

1. Create a summary widget
2. Drag and drop a channel into the summary widget
3. Save the summary widget
4. Edit the summary widget
5. Add rule
6. Select the channel
7. Select a telemetry field
8. __Observe:__ No further options appear.

<img width="700" alt="image" src="https://user-images.githubusercontent.com/1685764/35073239-f353dc46-fb9c-11e7-9693-3c892d6d6f14.png">

May be due to an absence of real-time data.

**Comment by VWoeltjen** [comment]
Root cause is that the [`latest`](https://github.com/nasa/openmct/blob/4b07930305c95689028b607fe3ce013591418829/src/plugins/summaryWidget/src/ConditionManager.js#L132) strategy is used to get a single datum to look at the data type. The relevant data provider was unavailable during that particular test, so this failed. Using telemetry metadata to determine types instead would be resolve the issue.
