### ISSUE TITLE
Table View Columns do not resize to fit enumeration strings, and aren't resizable in general. 

### ISSUE THREAD

**Issue by mudinthewater** [nasa/openmct#2017]
In particular, I have a telemetry table with the following columns: 
[ID][Timestamp][DN][EU][Enumeration]

The enumeration field contains a text string set by the enum datatype in the dictionary, but when the column is rendered it seems to be a fixed width unless the window is resized. This cuts off the text in the last column (since there are so many columns I assume). Ideally, columns would either auto-resize to fit the width of their contained element, or be resizable via a slider (similar to Excel behavior). 

Right now in order to read the text in that final column, I have to expand the whole thing to the width of my browser and for whatever reason the timestamp field then takes up half the space but the enumeration field just expands enough to read the text that I've got in it.

**Comment by mudinthewater** [comment]
The workaround for this is to just name the column with a name that's as long as the longest possible enumeration in the dictionary. I just put some filler text in the name and it works great.

**Comment by larkin** [comment]
@mudinthewater thanks for reporting.  I think there is actually a bug here with how table columns are automatically sized for enumerations that may have been fixed with https://github.com/nasa/openmct/pull/2019 which was merged yesterday.

Can you try again with the latest OpenMCT version and let us know if you still see this bug?

On a separate note, there is a request for custom column sizing, #1964.

**Comment by mudinthewater** [comment]
I've verified that this appears to be fixed via #2019. Since the column sizing is already in #1964, I'll close this.
