### ISSUE TITLE
Flexible Layout todos

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2205]
A checklist for final-mile implementation todos, in loose order of priority.

- [ ] @dtailor90 Integrate toolbar with remove, toggle frame, change layout.
- [x] @charlesh88 Allow drop-hints to display for first placeholder container.
- [ ] @charlesh88 Make sure all is well with the Snow theme.
- [ ] @dtailor90 When removing a frame from a container that has more than one, the size of the  frames needs to be recalced - right now they both display as "50%". To reproduce: make a new FL with two containers, then add two objects to only one of the containers. 
![screen shot 2018-11-05 at 5 18 26 pm](https://user-images.githubusercontent.com/1056412/48036887-10639e80-e11f-11e8-86a3-09c09836af8c.png)
Then move one of the objects via drag to the other container.
![screen shot 2018-11-05 at 5 18 32 pm](https://user-images.githubusercontent.com/1056412/48036893-15285280-e11f-11e8-84c5-9efba1842b25.png)
- [ ] @dtailor90 Object headers in FL frame always show the object icon instead of the proper icon for the object type.
- [ ] @charlesh88 Final mile on `symbols-font-update` branch, integrate new icons for FL's.
- [ ] @charlesh88 Change drop-hint icons to + symbols once `symbols-font-update` integrated.
- [ ] @dtailor90 @charlesh88 Need to handle `is-editing` when an FL or a fixed Layout is nested in a FL or vice versa.
- [ ] @dtailor90 @charlesh88 Draggable containers with drop-hints for container placement.
- [x] @dtailor90 By default, new FL's should have two empty containers.
- [ ] @charlesh88 Better styling for s-selected within FL.

**Comment by larkin** [comment]
@charlesh88 @dtailor90 New issues are intended for bugs or features in master branch.  Because this is being implemented in TCR I'm going to move this checklist to the [pull request for flexible layouts](https://github.com/nasa/openmct/pull/2201).  I don't want to open extra issues for new development that's happening in a topic branch, and this allows us to track the development progress on flexible layouts in a single location.
