### ISSUE TITLE
Remove package-lock.json from .gitignore

### ISSUE THREAD

**Issue by Ajmdag** [nasa/openmct#2230]
Remove package-lock.json from .gitignore to avoid errors while building project. And add this file to repository. This file provides you to lock versions of dependencies of your project. It will help you to avoid errors.

**Comment by aayusharora** [comment]
Hi @Ajmdag 

This file should be committed because:
- Describe a single representation of a dependency tree such that teammates, deployments, and continuous integration are guaranteed to install exactly the same dependencies.

- Provide a facility for users to "time-travel" to previous states of node_modules without having to commit the directory itself.

- To facilitate greater visibility of tree changes through readable source control diffs.

And optimize the installation process by allowing npm to skip repeated metadata resolutions for previously-installed packages.

**Comment by larkin** [comment]
We're intentionally ignoring this file right now for a list of reasons, we may reconsider that at a later date.
