### ISSUE TITLE
Save and Finish no longer shows blocking modal dialog

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2496]
When saving an object that takes a long time to save, a blocking modal dialog used to be displayed:
<img width="1186" alt="Screen Shot 2019-09-17 at 5 06 40 PM" src="https://user-images.githubusercontent.com/1056412/65088267-8b1b5e00-d96d-11e9-9180-6da95962ccb0.png">

This dialog is no longer shown, leaving the Save and Cancel buttons exposed with no feedback to the user. The user, thinking their first request didn't go through, will almost certainly try to invoke Save and Finish again - this causes console errors. 

The blocking dialog should be reintroduced to prevent this.

**Comment by akhenry** [comment]
@nikhilmandlik Take a look at the [RemoveAction](https://github.com/nasa/openmct/blob/7c32700b697f5004f79d70cd2ba1658be8c87664/src/plugins/remove/RemoveAction.js#L46) for an example of using the Overlay API. In this case we will want to use the [`.progressDialog` function](https://github.com/nasa/openmct/blob/7c32700b697f5004f79d70cd2ba1658be8c87664/src/api/overlays/OverlayAPI.js#L124), with an `unknown` progress bar, instead of `.dialog` as in the example.

**Comment by deeptailor** [comment]
fixed in pr #2498
