### ISSUE TITLE
Tutorial for telemetry adapter - plotting error

### ISSUE THREAD

**Issue by wireless-openmct** [nasa/openmct#2540]
https://stackoverflow.com/questions/52557979/click-on-plot-view-for-openmct-have-a-error

**Comment by wireless-openmct** [comment]
Kindly reply what the solution is for this issue. The tutorial also isn't updated.
Also, isn't bower_components deprecated. Is it advisable to use it still?

**Comment by wireless-openmct** [comment]
I was facing this issue. When queried, someone else was also facing the same (posted in stackoverflow). What is the way out? I'm completely new to openmct.

**Comment by shefalijoshi** [comment]
Hi,

We apologize for the misunderstanding but the up to date OpenMCT tutorial can be found here: https://github.com/nasa/openmct-tutorial

Can you also please let us know how you reached the old tutorial site so that we can down the out of date link to it? Thank you.

**Comment by wireless-openmct** [comment]
I cloned the latest release available and followed tutorial in openmct/docs/src/tutorials/index.md.

But then, the plugin installation / telemetry adapter followed in https://github.com/nasa/openmct-tutorial is completely different from the master release. For example, we use require.js to define and install plugins in the present master branch. But, the tutorial you mentioned follows a completely different style of directly installing plugins from index.html

Also, present master branch uses bower_components, isn't it deprecated?

**Comment by akhenry** [comment]
@wireless-openmct Hi! Thanks for using Open MCT.

My apologies for the confusion here. It seems that the source for our old tutorials is still lying around in our repository. That's our bad. This old tutorial reflects our legacy API, and a number of changes have occurred that affect how plugins are installed in Open MCT. We are going to remove this legacy documentation in order to avoid this confusion in the future. Thanks again for raising this.

@shefalijoshi Is correct, https://github.com/nasa/openmct-tutorial is the right tutorial to be using. This tutorial will take you through the process of defining and installing plugins using the current plugin system. It will also show you how to populate the tree with objects, how to define new object types, and how to integrate a telemetry source into Open MCT to show data in plots, tables, etc.

Finally, re: Bower. Yes, Bower is deprecated. We will be releasing a new version of Open MCT in December that uses npm for dependency management, and Webpack for building, and completely removes our dependency on Webpack.

**Comment by wireless-openmct** [comment]
Thanks!
So just to clarify again, any customized plugin that has to be installed should be directly called from index.html? Defining plugins through bundle.js is not required and will be completely removed in future?

**Comment by akhenry** [comment]
@wireless-openmct Right, plugins should be installed using `openmct.install(pluginInstallFunction);`. In the simplest case this can be done from index.html. Support for legacy bundles will be around for a while (we still have a bunch of code depending on it), but it will eventually be completely deprecated.

**Comment by wireless-openmct** [comment]
Okay...Thanks for the info!
