### ISSUE TITLE
Hide infobubble when context menu is clicked

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#268]
Was /jira/browse/WTD-1300

An unforeseen consequence of both the infobubble and context menus coexisting is that it's very distracting when they both overlay each other. As a solution, infobubbles should be hidden when a context menu is activated.

**Comment by andersonkmi** [comment]
Hi, I have recently submitted my CLA and I would start helping by working on this issue. Do I need to assign it to myself? I trie to do it, but could not where I could do it. Thank you.

**Comment by akhenry** [comment]
@andersonkmi Hi! We have received your CLA, thanks for sending it. There's no need to assign the task to yourself, and indeed our repo configuration won't allow assigning issues to contributors outside of the organization. 

In any case, this is a great first issue to work on. Let us know how you get on, and give us a shout if you need any help.

**Comment by andersonkmi** [comment]
Hi @akhenry. thank you for your attention. I will surely let know you how it goes. Take care.

**Comment by andersonkmi** [comment]
Hi @akhenry.. I have been away for a while... I was reading the docs and exploring the source code a bit and for this issue, it is related to that bubble that is displayed when the app is open for the first time (Welcome to the OpenMCT...)?

**Comment by andersonkmi** [comment]
@akhenry, hi! I believe I could figure out this isuse after doing some exploration. I see that it may happen to have the info bubble show up even when the context menu is active. As a starter, I will play around with this issue. Thank you.

**Comment by akhenry** [comment]
@charlesh88 Just some clarification here. The current situation is that if an info-bubble is active, and a context menu is triggered, then the info-bubble will be hidden (this happens because the context-menu appears under the mouse cursor causing a mouse-leave event on the info-bubble).

It is possible to trigger an info-bubble once a context menu is active, and if they overlap in screen space the context-menu will partially obscure the info-bubble.

Are we saying that info bubbles should be completely disabled while a context menu is active?

**Comment by akhenry** [comment]
@andersonkmi Apologies for the delay in getting back to you. Yep, you got it. This issue is referring to the info bubbles that appear on hover over an object and show metadata about that object. It's not referring to the "tour" that appears in our online demo.

The template in question is `info-bubble.html`, and not `infobubble.html` [which is a red-herring](#1427).

**Comment by charlesh88** [comment]
This is way old, closing.
