### ISSUE TITLE
[Notebook] Refactoring

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#2825]
* [x] Address comments in https://github.com/nasa/openmct/pull/2755/files
* [x] Add unit tests

**Comment by shefalijoshi** [comment]
Verified on 10/05/2020
Notebook functionality seems to work OK.
Found one issue: If you click on each of the notebook snapshots in the snapshots bar, the "timespan bounds change" notification stacks for each click instead of overwriting itself. So to get rid of the notification you have to click (x) multiple times.
