### ISSUE TITLE
Unknown Bundle undefined error when trying to install Elasticsearch plugin

### ISSUE THREAD

**Issue by knk38** [nasa/openmct#2886]
Hi I am trying to install the built-in elasticsearch plugin using the openmct.install( ) function  but I am getting an Unknown bundle undefined error, which doesn't make sense to me because the elastisearch plugin is included in the source code already. Is there something else I should be adding besides the install function in index.html? I have tried installing other plugins such as the Snow theme and they have worked fine so I am stuck. Here is a picture of the error I am getting
<img width="929" alt="bunderegistryerror" src="https://user-images.githubusercontent.com/56562686/78812632-b8773a00-7999-11ea-81b4-aa6306561520.png">

**Comment by JoelMcKinnon** [comment]
Sorry about the delay getting back to you. The error you saw is due to a couple of things you can fix on your end, but there’s also some work we need to do to bring our code up to date with some changes in the Elasticsearch api.
 
Here’s what you can do to get it a little closer to working:

1. Go to the elasticsearch.yml file located at the root level of the directory created after downloading and decompressing the package. Add the following lines to allow openmct to call the Elasticsearch folder without violating CORS protocol:
```
    http.cors.allow-origin: "/.*/"
    http.cors.enabled: true
```
2. In index.html, remove the line that installs the LocalStorage plugin, and add:
    `openmct.install(openmct.plugins.Elasticsearch('http://localhost:9200'));`
3. Go to src/plugins/plugins.js and add Elasticsearch to the bundleMap object (~line 88):
    `Elasticsearch: 'platform/persistence/elastic’`

You will still have some errors on attempting to add and remove objects from the tree until we fix the API issues. We'll get that done ASAP.

**Comment by JoelMcKinnon** [comment]
Regarding the CORS configuration noted above, setting `http.cors.allow-origin: "/.*/"` basically allows any domain access and is therefore a security risk. 

A better approach is to set it first for local development with 
`http.cors.allow-origin: /http?://localhost(:[0-9]+)?/`

Then replace the localhost regex with your webserver host name for a production scenario.

**Comment by akhenry** [comment]
Verified Fixed 05/12/2020
