### ISSUE TITLE
[Actions] Add 'Go to Parent' action

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#289]
Add an action representing "navigate to the parent of this object", and utilize this from the back arrow template.

Observed during CLI prototyping (branch cli), filed per #176; this is a place where behavior that belongs in the information model has been handled in the display layer.

**Comment by larkin** [comment]
Wouldn't confuse 'back' and 'navigate to an object'.  Browsers have a back button, and users should be able to use them even in a single page app. 'back' is "go to whatever i was looking at before the current thing I'm looking at," and this is accomplished by the back button, or by window.history.back() or window.history.go(-1).  

The behavior you're describing is not an information model concern IMO: an object knows it's parent, and it's possible to generate a link to the parent, so navigating to a parent object should be just that: navigating to a parent.

I've mentioned in other places, but we should be using hyperlinks for navigation (`<a href="...">) so that we piggyback on standard browser functionality.

**Comment by VWoeltjen** [comment]
We could call it `{ key: "up", name: "Go to Parent" }` if we want to disambiguate.

Real issue here is that the code for this is in the template; we're mixing the code for a thing the user wants to do ("go up the tree") with the code for displaying the clickable thing to do that. A thing the user wants to do is normally encapsulated as an action.

We could remove navigation as a concern from the information model and just handle it in the display layer (e.g. as links); I agree this would be much more in line with normal functionality. This makes initiating these interactions in other ways a little difficult however (e.g. navigating to an object upon its creation), and runs a risk of becoming inflexible (reusing that code on the backend, for instance.) Think we'd end up wanting to express these changes as actions anyway for that purpose; possibly add an optional `url` property to actions allowing the display layer to represent these as simple links (in lieu of invoking `perform`)?

I'll add these notes to #61 since we're starting to tread over there.

In any case, definitely low priority.

**Comment by larkin** [comment]
I think there are some grey areas with actions: are they all directly tied to user input?  If so, why do they have any meaning in the back end?  Left a comment in #69 with some api level feedback.

**Comment by larkin** [comment]
Closing as wontfix.
