### ISSUE TITLE
[Notebook] Entries and Embeds need to use the same timesystem

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#2920]
Currently the Entry uses Date.now and embeds use UTC

**Comment by JoelMcKinnon** [comment]
## Testing Instructions (from PR):

1. Create new Notebook or goto existing Notebook.
2. Add a new entry to notebook page.
3. Goto any other telemetry object (eg: Display Layout)
4. Take a snapshot so that it save into a notebook
5. Goto Notebook and 'Display Layout' embed and 'notebook entry' timestamps should match.
![Screen Shot 2020-05-11 at 3 25 55 PM](https://user-images.githubusercontent.com/1292612/81618558-737d6380-939c-11ea-8304-d66b80cdc411.png)

**Comment by JoelMcKinnon** [comment]
Verified.
