### ISSUE TITLE
Problem with integrating custom plugins as seen in the integration tutorial

### ISSUE THREAD

**Issue by LeDemz** [nasa/openmct#2954]
Hi,

I'm currently trying to replicate the telemetry integration tutorials (openmct-tutorial) on this repo of OpenMCT. However, I am quite stuck in the beginning steps as I see in my browser console log that the file I have included in the `<script src="nameoftheplugin.js"><\script> `are not found by the node.js server. Is there a difference between this version of OpenMCT and the one found in the tutorials (I had no issue whatsoever in including the files with the tutorial version) as of why I am unable to include custom plugins to make a simple telemetry adapter ?

Thanks in advance!

**Comment by RyanProffitt** [comment]
I also encountered this issue. Please correct me if I am wrong, but are the tutorials / API guide out-of-date?

**Comment by akhenry** [comment]
Hi, thanks for reporting this issue, and I'm sorry to hear that you're having problems. If you're writing plugins for Open MCT, we recommend not writing them directly in the Open MCT source tree itself. Instead, we recommend that you start a new project, [using Open MCT as an NPM dependency](https://github.com/nasa/openmct-tutorial/blob/ee90bb4bcad690c12e2d55fd447390c7922fee73/package.json#L22), which is how the tutorial works.

The problem in this case is that our build and development environment is not aware of your new plugin. For building Open MCT we use Webpack, only knows about source files if they are part of the dependency tree that starts with the source code entry point, in this case [openmct.js](https://github.com/nasa/openmct/blob/4eb4cbfffc2d7c48fefb133c2371c69329ca40ac/webpack.config.js#L21). Because your plugin is not included from any of our source code, Webpack doesn't know about it, so it does not get served by the Webpack dev server.

There are ways to fix this by changing the Webpack configuration, but again, I would recommend defining your own build and development environment and including Open MCT as a dependency. If you'd like to use Webpack, we have a ["Hello World" project](https://github.com/nasa/openmct-hello) which provides a basic npm and Webpack configuration for building and running Open MCT as a dependency. If you'd prefer not to use Webpack you can still use our "Hello World" project as a basis, and just switch Webpack out for something else.

One caveat, neither of the node.js servers used in the tutorial or for Open MCT development should be used in any kind of production environment. These are provided for development, and demonstration purposes only. For production you should use an industry standard web server such as Apache, nginx, etc.

**Comment by skrobchik** [comment]
I was struggling a lot to figure out how to package my application with npm and webpack. This helped a lot. Maybe it should be included in the main readme to save other people some time.
