### ISSUE TITLE
Incorrect condition match with test data

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#3037]
Steps to reproduce:
1. Create a condition set with 2 conditions - 1st one using a specific telemetry object as it's criterion and the 2nd one using Any/All telemetry as it's criterion.
2. Create test data for the 1st condition to always evaluate to true
Observe: The 1st condition does not always win.

In the example below, the 2nd and default conditions should never win, but they do.

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/5247066/81753257-40a0a180-9468-11ea-98cb-2f647580f443.png">

**Comment by charlesh88** [comment]
Verified fixed with SWG of amplitude 10 (-10 to +10) and this CS:
![Screen Shot 2020-05-15 at 3 35 17 PM](https://user-images.githubusercontent.com/1056412/82101613-c703f000-96c1-11ea-93a5-f42d245af708.png)

This layout was used to test:
![Screen Shot 2020-05-15 at 3 37 04 PM](https://user-images.githubusercontent.com/1056412/82101660-f4e93480-96c1-11ea-9d26-397d50b54687.png)

**Comment by nikhilmandlik** [comment]
Verified fixed testathon 05-15-20.
