### ISSUE TITLE
[Time] Synchronization between time API and URL is slow and unpredictable

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3088]
Eg. changing the bounds, or time system in the conductor can sometimes take several seconds to be reflected in the URL, especially if the clock plugin is disabled (as it is in VISTA).

### Testing Notes
1. Make changes in time conductor and confirm that they are immediately reflected in the URL.
eg. changing from fixed to realtime mode should result in the value of the `tc.mode` parameter in the URL changing from `fixed` to `local`.
2. Test that URL sharing still works. After changing some settings in the time conductor, copy the url and open a new tab or window. Paste the url into the new tab, and once the application has loaded, confirm that the conductor settings are the same as the tab that you copied from.

**Comment by deeptailor** [comment]
Testathon 06/22/2020

Passed

**Comment by charlesh88** [comment]
Verified _partially fixed_ -  item 1 verified, but item 2 fails with the following observed issue related to URL sharing: when the Time Conductor is in Local UTC mode, it will not switch settings from the URL.

1. In Chrome, go to a Layout with the Time Conductor in Fixed mode. Bookmark the URL in the browser.
1. Open a new tab for the current view using whatever method you like (New Tab button in status area, copy and paste URL, etc.). Switch the Time Conductor Local UTC.
1. Click the browser bookmark created in step 1. Expected behavior is the TC will change to Fixed Mode and set itself to the bookmarked parameters. Observed: TC does not change.
1. Bookmark the current real-time view, then switch back to the first browser tab, which should still have the TC in Fixed mode.
1. Click the second real-time bookmark and observe that the Time Conductor _does_ properly set itself to the bookmarked parameters.

Note that all of the above can also be replicated when attempting to paste a copied URL rather than clicking a browser bookmark.

**Comment by nikhilmandlik** [comment]
Verified. Testathon 6/22/2020

**Comment by jvigliotta** [comment]
Verified Fixed: Testathon 07/01/2020
