### ISSUE TITLE
[Tabs View] Adding new objects don't create tabs after removing all items

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3155]
Seen in master branch. 

### How to replicate
1. Make a new Tabs View, then add one item.
1. Remove that item via its context action in the Elements pool. There must be no tabs visible to cause the bug.
1. Try to add new objects from the tree: observe that while they appear in the Elements pool, they are not added as tabs. 

![Tabs View tabs don't show after removing all](https://user-images.githubusercontent.com/1056412/86661377-80839100-bfa0-11ea-8369-6904a1527476.gif)

### Notes
- This only occurs when starting with a "no-tabs" situation - if a tab is present, the bug doesn't manifest.
- Saving the Tabs View then navving away and back will cause the view to display its tabs properly.
- While the attached GIF shows drops happening in the middle of the edit area (vs. dropping onto the drop target) the behavior is the same if items are carefully dropped on the target area.

**Comment by deeptailor** [comment]
I bet there is an error in the console that blocks new tabs from being
added. Good catch!

**Comment by deeptailor** [comment]
After investigation, turns out when the currentTab is removed, this.currentTab becomes undefined. When adding a new tab, we check wether the currentTab is the one the user should be shown, throwing an error on this.currentTab.key.

The correct fix would be to check wether this.currentTab is defined before checking for equality in isCurrentTab. If this.currentTab is undefined, we should return false.

**Comment by akhenry** [comment]
Verified fixed, 07/13/2020

**Comment by shefalijoshi** [comment]
Verified fixed on 13th July

**Comment by nikhilmandlik** [comment]
Verified. Testathon 7/13/2020

**Comment by charlesh88** [comment]
Verified Testathon 07/13/2020.

**Comment by davetsay** [comment]
Verified in VISTA
