### ISSUE TITLE
[Condition Set] Message string is incorrect

### ISSUE THREAD

**Issue by deeptailor** [nasa/openmct#3211]
See image below:

![image](https://user-images.githubusercontent.com/13260688/87828656-40d76780-c832-11ea-9194-5a65346e79a6.png)

The message string for the first condition should say Match if all criteria are met: ENG-0001 - main_engine_turn_on Stale is "TRUE" but it says Match if all criteria are met: ENG-0001 - main_engine_turn_on Stale is "False"

**Comment by shefalijoshi** [comment]
@deeptailor 
Can you include the telemetry metadata here please?

**Comment by deeptailor** [comment]
` enumerations: [
                {
                    string: "TRUE",
                    value: 1
                },
                {
                    string: "FALSE",
                    value: 0
                }
            ],`

**Comment by shefalijoshi** [comment]
@deeptailor I haven't been able to reproduce this issue locally. Can we debug this together sometime?

**Comment by shefalijoshi** [comment]
**Testing Instructions:**
Test locally - Modify the [State Generator metadata ](https://github.com/nasa/openmct/blob/master/example/generator/GeneratorMetadataProvider.js#L91) so that the order of it's enumerations is ON first and OFF second
```
enumerations: [
                        {
                            value: 1,
                            string: "ON"
                        },
                        {
                            value: 0,
                            string: "OFF"
                        }
                    ],
```

Create a condition set
Drag a State generator into it as telemetry
Create a condition using the State Generator telemetry and compare the State to either ON or OFF.
Ensure that the condition description correctly displays ON or OFF based on what was chosen in the value comparison.

**Comment by charlesh88** [comment]
Verified fixed Testathon Aug. 24, 2020
