### ISSUE TITLE
[Core] Prototype domain object cache

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#322]
(From review notes on #319)

Prototype domain object cache to ensure that only a single instance of a domain object with a given ID (as returned by the objectService) is present in the system at any given time.

Some things to consider:
- Memory utilization - how to avoid leaking memory with such a cache. (Don't think `WeakMap` will work here. May be some eviction strategy we can use?)
- Correctness - does any behavior rely on having separate instances of the object throughout the application?

**Comment by larkin** [comment]
I think a cache is a poor solution here-- it doesn't account for the fact that multiple instances of a domain object with the same ID can actually exist-- links vs originals.  It seems the motivation for a cache is to ensure objects don't get out of sync...

If domain objects are kept in sync via a cache, there is a need for change detection.  With a cache, we depend on watches, which is not ideal.  I think we should be using observables: everything that uses a domain object should listen for changes that are important for that thing to do it's job.  When that thing ceases to exist, it should stop listening for changes to that domain object.  When no references are held for a thing, the GC will clean it up-- enough said.

The trick with observables is that event listeners are the prime cause of memory leaks and must be properly added/removed; the responsibility for that must be placed on the consumer of the domain object, which typically fits into the lifecycle management events, such as `$scope.$on('$destroy', ...)`.  This adds a lot of boilerplate.

A pattern we could steal from backbone would be extending $scope to support `$scope.$listenTo(observable, eventName, callbackFunction, callbackContext)`, which would automatically deregister handlers when the scope is destroyed.  Worth noting that an `observable` is anything that supports the `on` and `off` methods-- or their more verbose forms -- `addEventListener` and `removeEventListener`.

**Comment by akhenry** [comment]
When I made the original suggestion I actually didn't realize that links have the same ID as the original. For some reason I thought they had a unique ID and were linked via a relationship to the original. Your point is taken. Perhaps links don't need to be separate instances though?

That point aside, the main motivation in considering a cache is to ensure that everyone has the same instance of an object. 'Synchronization' is not necessary because everyone has the same object. In fact attaching observers to an object will only work if everyone has the same instance of said object, otherwise the observers need to be on a shared third party (like a service). This is how the status capability currently works, and is what prompted this discussion.

Using a cache does not prevent us from using observers instead of watches, but it does allow us the flexibility to choose the appropriate approach in a given situation.

**Comment by VWoeltjen** [comment]
For reference, specific rationale for this comes [from here](https://github.com/nasa/openmctweb/pull/319#discussion_r45420117):

> Status should be an attribute of the object itself, rather than being tracked centrally via a service. Is this being done this way because of the possibility of having multiple instances representing the same object? If so, maybe we need to rethink this. Maybe, for example, we need to consider an object cache so that whenever an object is requested from the object service, the same instance is always returned?

I think it's probably worth looking at this is a trade, and prototyping only if more information is needed:

* Have a single "real instance" (wrapping these for context, editability, and other cases where we need multiple instances):
  * Implies a cache (creates memory leak or requires solving some eviction strategy)
  * May cause subtle bugs with capabilities (when behavior of "the real instance" leaks into the wrapped instance)
  * Allows code to accrue which makes a single-instance assumption for correctness, making it difficult to change this later (conversely, code which accounts for one or more instances will still be correct with one instance)
* Have multiple instances
  * Requires that capabilities synchronize across instances.
  * Introduces risk of memory leaks with observables (since those will likely be used to synchronize capabilities.)

One of the recurring themes in #69 is that we need a class library for extensions to use and/or inherit from (currently, we handle variation among extensions 80% with properties and/or implemented methods, and 20% with byzantine decoration strategies.) The `status` capability from the referenced pull request also comes with a service that stores status by ID; repeating this would require _n_ such services for _n_ capabilities, but we could also hide this nicely in a reusable parent class to reduce this to 1 such service for _n_ capabilities.

**Comment by larkin** [comment]
First-- to handle sharing events among multiple domain objects, they can abstract the actual listeners to the topic service, allowing different instances to be synchronized by an application-wide topic service.

Caching as a method to prevent object duplication requires an eviction policy otherwise we will continually leak memory, but if you evict an object that is still in use elsewhere, the next request for that object will duplicate it.  The only way to track when an object is currently still in use requires the same sort of lifecycle events as I've described above, so why not skip the cache and use observables with lifecycle events?

Ultimately, the common pattern emerging for web displays these days is for view components to declare their data dependencies and for some service to push them updates as necessary.  It allows for very efficient display updates (ideal for mobile) and simplifies memory management.  This isn't actually a new pattern, there's a great article tracing it's roots to windows 3.1 and earlier that I can't seem to find right now.

**Comment by VWoeltjen** [comment]
> Ultimately, the common pattern emerging for web displays these days is for view components to declare their data dependencies and for some service to push them updates as necessary. It allows for very efficient display updates (ideal for mobile) and simplifies memory management. This isn't actually a new pattern, there's a great article tracing it's roots to windows 3.1 and earlier that I can't seem to find right now.

This is the direction we've been going and there have been no particular issues there. Closing as a wontfix; it would require a big shift in plans for this to be relevant again.
