### ISSUE TITLE
[Time Conductor] Zoom not changing bounds

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#3344]
## Overview
The bounds display is being changed on zoom operation but the actual bounds are not changing.

## Expected Behavior
Completing a valid zoom operation should change the time conductor bounds.

## Steps to Reproduce
1. Navigate to a plot
1. Perform zoom function (Hover over time conductor axis, click, drag, and release)
1. Observe that bounds in inputs change to zoom bounds.
1. Observe that plot changes with respect to new bounds.

**Comment by nikhilmandlik** [comment]
Verified Fixed. Testathon 9/14/2020.

Wondering if hover over time conductor axis, click, drag, and release should snap to nearest value instead of changing to values in milliseconds.
eg: start and end bounds are 
1. within same seconds snaps to milliseconds
2. within same minutes snaps to seconds
and so on.

**Comment by shefalijoshi** [comment]
@nikhilmandlik 's comment will be created as an enhancement issue.
