### ISSUE TITLE
Object API is returning undefined for missing objects

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3367]
Previously, missing objects would be returned as a [`MissingModel`](https://github.com/nasa/openmct/blob/14114781fcd436674fdc30d585066249b604d03f/platform/core/src/models/MissingModelDecorator.js#L40), meaning that client code could handle them like regular objects (albeit with a special type of `unknown`).

The new API does not explicitly do this, and was instead depending upon legacy code to do it. As we replace our legacy object providers this is starting to become a problem, because they do not invoke any of the legacy API that previously handled this. We need to add some catchall code to [`ObjectAPI.get()`](https://github.com/nasa/openmct/blob/14114781fcd436674fdc30d585066249b604d03f/src/api/objects/ObjectAPI.js#L156) that inspects objects returned by the `.get()` function call, and if it's undefined return a missing object. The missing object should look like this:
``` JavaScript
let missingObject = {
    identifier: requestedIdentifier,
    type: 'unknown',
    name: 'Missing: ' + openmct.objects.makeKeyString(requestedIdentified)
}
```

**Comment by akhenry** [comment]
@shefalijoshi  This is a good candidate for object request interceptors as well

eg.
``` JavaScript
openmct.objects.addInterceptor((identifier, object) => {
    if (object === undefined) {
        return {
            identifier,
            type: 'unknown',
            name: 'Missing: ' + openmct.objects.makeKeyString(identifier)
        }
    }
});
```

**Comment by shefalijoshi** [comment]
Testing Instructions:
Update index.html to use CouchDB instead of LocalStorage by replacing 
`openmct.install(openmct.plugins.LocalStorage());` with 
`openmct.install(openmct.plugins.CouchDB('http://localhost:5984/openmct'));`

Delete all objects from CouchDB
Start Open MCT
The My Items folder should be visible with No Items in it.
Add a folder or any other object from the create menu
It should be visible under My Items
Refresh the browser and ensure that the My Items and newly created domain object are still available.

**Comment by akhenry** [comment]
Verified fixed.

Verified by running Couch DB and manually deleting just one of the objects in my tree using -

```
curl -XDELETE http://localhost:5984/vipersim/<object id>?rev=<rev>
```

Because the parent's composition does not change, this results in a missing object in the tree.
