### ISSUE TITLE
[Navigation Tree] Context delete doesn't work as expected 

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#3382]
## Overview
Seeing a couple of strange behaviors deleting objects from tree
- delay in delete
- object not fully deleting from tree until navigated away

## Expected Behavior
- Object should be removed from tree immediately
- Object should not be able to be navigated to

## Steps to Reproduce
1. Navigate to an object in tree with children
1. Expand object
1. Context-menu delete the object
1. Observe Object remains as alias and can be navigated to

![delete bug](https://user-images.githubusercontent.com/3614296/93646827-d7074580-f9bb-11ea-874d-f4baaa4a3ea6.gif)

**Comment by akhenry** [comment]
Similar issues in the past have been caused by stale object models. I suspect that somewhere a view is mutating a stale version of the object model. If this is what's happening it will manifest as a remove composition event followed immediately by an add composition event.

The reason this happens is because of [some compatibility code between the old and new APIs](https://github.com/nasa/openmct/blob/master/src/api/composition/DefaultCompositionProvider.js#L264) that detects composition changes via changes to the `composition` property of objects. Composition is tracked via the `.composition` property on objects. A composition change will result in an object identifier being added or removed from the property. If code mutates a stale object it may still have the pre-deletion composition, and the subsequent mutation of the model (it doesn't matter what property is mutated) will trigger a composition change event which will **add the object back into the tree**. 

As such, it is necessary for any code that mutates objects to also ensure that it is mutating a fresh copy of the object. Object models can be kept fresh using wildcard listeners, 
eg.
``` JavaScript
let listener = this.openmct.objects.observe(this.domainObject, (updatedObject) => {
    this.domainObject = updatedObject;
});
```

[There is an example of this in the Elements view](https://github.com/nasa/openmct/blob/master/src/ui/inspector/Elements.vue#L118).

**Comment by jvigliotta** [comment]
Ok, after some digging into the issue I found the problem was caused by not watching the ancestors of the currently navigated tree item for any changes. So, when a tree node is expanded, it's children are loaded in and the node is watched for composition changes, so, any new folders or removed folders from that currently viewed node would be updated accordingly. BUT if you were to delete the parent of the currently viewed node (an ancestor) it would be updated with its location set to "null" hence the "alias" status in the tree, but nothing was done after that, because ancestors weren't being watched for changes.

@akhenry I did use objects.observe, but I used it for location only on any current ancestors and if the location was set to null, then I reset the tree to that ancestors parents. I'm testing out some more scenarios, but it seems this fix is working.

**Comment by jvigliotta** [comment]
# Testing
- follow the "Steps to Reproduce" in the original comment on this issue
- verify the item is actually removed and not just aliased and that the tree is set to the parent of the removed item
- create a bunch of nested objects and delete any of the ancestors
- verify that the tree is navigated to the parent of the deleted ancestor

**Comment by akhenry** [comment]
Verified fixed 10/05/2020

**Comment by deeptailor** [comment]
Verified fixed 10/05/2020

**Comment by davetsay** [comment]
Verified

**Comment by charlesh88** [comment]
Verified fixed Testathon 10-05-20.
