### ISSUE TITLE
[UI] Transitions to progress indicator are unclear

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#339]
From user testing related to #127 and #155, @RCarvalhoNASA reports:

> Notification comes up and then transitions to progress bar, though I'm not sure why it does it both ways and whether one allows a different state than the other.

>  Notification transitions to progress bar, though it is unclear to user why this transitions or what that means. Progress bar seems to work fine.

Filing as a separate issue for triage. Believe components are working as intended and that this is best handled as a UX enhancement.

**Comment by charlesh88** [comment]
@RCarvalhoNASA Robert, let's talk about this when you get a chance - I'm unclear on the behavior being described that's causing confusion.

**Comment by RCarvalhoNASA** [comment]
So when you do an operation that takes some time, such as a large copy, it initially gives you a popup in the middle of the screen showing it is in progress, and then that shrinks down to the bottom bar of the screen after a certain point.  I'm just not sure why both modes are used, and if there is any difference between the two in terms of the limitations on what the user can do while those are happening.  Why not just have one indication that lasts through the whole activity?

**Comment by charlesh88** [comment]
Thanks for the comment. It's like an airliner: initially you can't get out of your seat while we're climbing because you might hurt yourself (that is, you might operate on files that we're also operating on, messing up the copy). Once we reach cruising altitude and there's no turbulence, you're free to roam the cabin - that is, we can finish our operation and you can do whatever you want.
I think the action for us here is to have a clearer explanation in the blocking dialog as to its behavior.

**Comment by charlesh88** [comment]
I've added a hint message to the dialog that displays during copying/duplication, but have no clear way to test my changes.

**Comment by charlesh88** [comment]
Testathon 2016-06-16
Verified fixed, message is displaying as intended:

![screen shot 2016-06-16 at 2 40 12 pm](https://cloud.githubusercontent.com/assets/1056412/16134124/50fb7822-33d0-11e6-8eeb-0875fd9a1bd7.png)
