### ISSUE TITLE
[Plot] Strange plot line shapes

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#343]
This is a transient issue, that was observed separately by myself and @costigan. Not clear yet on how to consistently reproduce it. 

Essentially, plots are sometimes seeing an extra straight line added to them. It looks as though the first and last values of a plot are being joined by a straight line. I did observe this consistently in the rems_data branch, where it was caused by an error on my part that resulted in telemetry values being duplicated in the returned data, but I'm not sure what is causing it in this case.

Screenshots below 

**My Items > RP15 Layouts > Power Layout > Batt SOC**
![weird plot](https://cloud.githubusercontent.com/assets/4215777/11355090/f110222a-9206-11e5-9206-90d9c0960cba.png)

**IGV212N - NIRVSS Shortwave Power Level**
![plotting_bug](https://cloud.githubusercontent.com/assets/4215777/11355174/d4f71390-9207-11e5-89c1-487d94202e06.png)

**Comment by VWoeltjen** [comment]
Was playback running on a loop when this was happening? There's no special handling for out-of-order data so this would be consistent with that.

**Comment by akhenry** [comment]
@VWoeltjen yep, was running in a loop. This theory sounds plausible.

**Comment by Costigan** [comment]
What command was run to play telemetry back?  How long was the loop?
(I can't find where the instructions for playing back telemetry were.)
________________________________

**Comment by akhenry** [comment]
I followed the instructions in the PDF you sent yesterday. Sorry, afk or
I'd send it to you.  I'm not sure how long the loop is in that telemetry
file

**Comment by Costigan** [comment]
Sorry.  Found the instructions.  It was just one file, which was short.
Victor's explanation is probably right.  I think we should defer the issue and look for it at the next test-a-thon while running a much longer loop.

________________________________

**Comment by Costigan** [comment]
p.s., In that file, EPSIO_BIT runs from 15-237-16:51:14.285 to 15-237-16:54:10.488.  That looks like the range of the Batt SOC plot.  Victor's explanation must be correct.  Let's just run longer playbacks in the future.

________________________________
From: Shirley, Mark H. (ARC-TI)
Sent: Tuesday, November 24, 2015 12:12 PM
To: nasa/openmctweb; nasa/openmctweb
Subject: RE: [openmctweb] [Plot] Strange plot line shapes (#343)

Sorry.  Found the instructions.  It was just one file, which was short.
Victor's explanation is probably right.  I think we should defer the issue and look for it at the next test-a-thon while running a much longer loop.

________________________________

**Comment by akhenry** [comment]
Suggest we close this one, we have a plausible explanation for why this is happening. We can reopen if we see any evidence of it happening with non-looping data. Any objections?

**Comment by VWoeltjen** [comment]
I think there's two issues we should probably spin off from here:

1. Update testathon procedures to account for longer loops of data
2. Decide how we handle out-of-order data (I think connecting it like this is incorrect)

I'll file these (or find existing issues) and then close this issue.

**Comment by larkin** [comment]
I think out of order data is something to be handled at the adapter level and is not a standard concern.  We've discussed it as a potential option for warp-server because it may potentially result in faster access patterns but if it's something every display needs to support then it's going to increase complexity markedly.  Looking for the lowest common denominator here.

**Comment by VWoeltjen** [comment]
I think we can defer this but don't think we can ignore this indefinitely. We have seen this in multiple sims, tests, etc. There are operational scenarios where data can be received out-of-order. 

Concur that we should prefer solutions that don't involve every display.

**Comment by VWoeltjen** [comment]
Filed WTD-1586 for testathon procedures, added note that these should include specification of inputs of sufficient length to avoid looping during testathon. Think this issue is sufficient to serve as the design task associated with this; closing existing issue WTD-746 as a duplicate.

> When plot receives data out of order, it draws data in the order received (not in time order)

> This is not desired behavior in WARP. In VISTA, there should be a toggle between this order and time ordering.

**Comment by larkin** [comment]
I think when we've seen this occur it is because of an actual error in the data source or an operational issue that requires users to clear their displays to resolve, which we have a story for (refresh!).  

I don't want to dedicate too much time without really solid use cases for this.  Will gladly remove this from the upcoming sprint and allow for discussion at a later date.

**Comment by charlesh88** [comment]
Not sure how this was assigned to me, but I got nothin' on this one. Reassigning.

**Comment by VWoeltjen** [comment]
@charlesh88 - The assignment was intentional but [poorly explained](https://github.com/nasa/openmctweb/issues/343#issuecomment-160706252); there is a design task here insofar as we don't have a specification for how plots should display out-of-order data, and user feedback suggests that the way we currently handle this is confusing. 

As an example of what I mean by out-of-order data, I mean cases like:

Order received by client | Timestamp on data | Data Value
-------|---------|-------
1 | 2015-12-09 14:00:00 | 1.0
2 | 2015-12-09 14:00:05 | 2.0
3 | 2015-12-09 14:00:10 | 1.5
4 | 2015-12-09 13:50:00 | 1.0
5 | 2015-12-09 13:50:05 | 1.2

Between points 3 and 4, the timestamp jumps back. This means that to display Point 4 correctly on a plot, it needs to appear before Point 1 - we know that much. Beyond that, there's a lot of options for how this could be display. Connect points 3 & 4, like we do now; leave a gap; leave a dotted line; keep everything connected but reorder (so there would be a line connecting point 5 and point 1); do any of the preceding with a little "out-of-order data received" notification; etc...

Not an immediate concern, as it's rare that we receive data in anything other than timestamp order. But there are real use cases where this occurs. Think we should keep this in the backlog for now and revisit when we start encountering relevant requirements.

**Comment by larkin** [comment]
Before removal from backlog, I'd prefer to see substantiation from a user that this is a thing that happens during normal operations so we better understand the needs around handling it.  Otherwise we're just guessing at solutions. (changing plot display format could make this a non-issue).

**Comment by Costigan** [comment]
This does occur in normal operations (or, rather, it does occur for existing systems and will occur for us) when the spacecraft clock is jammed.  My understanding is that that operation is rare at JPL and the clock is adjusted by managing the mapping between SCET and ET or UTC.  Ames has mostly jammed the SC clock with UTC, which causes small discontinuities (either forward or backward) in the SCET.  The latter causes what we saw here.  I know some Goddard missions do what Ames does, but I can't speak for all of them.  RP will most likely be flown this way, so it'll occur with RP.

**Comment by VWoeltjen** [comment]
Observing this again in a testbed environment, due to out of order data in a real-time test data set (earth received time increases monotonically, but spacecraft event time does not)

**Comment by VWoeltjen** [comment]
Notes from discussion 5/4/2016:

* Tracking receipt order and display order as two separate things could be useful here (we do this already in tables)
* Don't want to try to resolve as a patch to existing VISTA release; there are open design questions, and this does not specifically contradict any requirements (data is plotted at correct locations)
* Workaround: Disable lines on that plot.

**Comment by Costigan** [comment]
Thanks for cc.  Discussion wasn’t on the group calendar.  What was the focus?
What was the context for the first point?  By receipt order, do you mean receipt by the web client or receipt at the ground station?

**Comment by larkin** [comment]
@Costigan receipt order at web client, not at server.

**Comment by larkin** [comment]
Moving to #1557 .

Weird shapes are accurate displays of data.  Closing this as wontfix.
