### ISSUE TITLE
[Documentation] API.md telemetry value specification uses "units" field instead of "unit"

### ISSUE THREAD

**Issue by AudunVN** [nasa/openmct#3562]
The current API documentation in [API.md](https://github.com/nasa/openmct/blob/master/API.md) incorrectly (?) specifies a field on telemetry values called "units" instead of the currently used "unit".

This means that following the API documentation will leave users (me included, after recently updating Open MCT in [one of my projects](https://github.com/AudunVN/mct-depot)) confused as to why value units don't show up anywhere despite being included as described in the documentation.

**Comment by AudunVN** [comment]
Actually a bit confused as to what's going on here; multiple locations in master currently reference `units`, but f03bfdebb4bcff8d09d0451f5d2a3fb45518e0e0 that seems to have caused this issue appears to use `unit`. Is the field name inconsistently used?

**Comment by nunoguedelha** [comment]
Hello @AudunVN , I also noticed the same inconsistencies in the Open-MCT API, as well as in the Open-MCT code.

Clearly, by running a grep on the code for `unit`...
```
$> egrep -Rs -e "\.unit[^s]" src/plugins/*
src/plugins/LADTable/components/LADTable.vue:            let metadataWithUnits = valueMetadatas.filter(metadatum => metadatum.unit);
src/plugins/LADTable/components/LadTableSet.vue:                            if (metadatum.unit) {
src/plugins/LADTable/components/LADRow.vue:            this.unit = this.valueMetadata ? this.valueMetadata.unit : '';
src/plugins/displayLayout/DisplayLayoutToolbar.js:                            .filter((metadatum) => metadatum.unit)
src/plugins/displayLayout/components/TelemetryView.vue:            let unit = this.metadata ? this.metadata.value(value).unit : '';
src/plugins/displayLayout/components/TelemetryView.vue:            const unit = this.unit ? ` ${this.unit}` : '';
src/plugins/gauge/components/Gauge.vue:            this.units = this.metadata.value(this.valueKey).unit || '';
src/plugins/plot/legend/PlotLegendItemExpanded.vue:            this.unit = seriesObject.get('unit');
src/plugins/plot/configuration/PlotSeries.js:            unit: range.unit,
src/plugins/plot/configuration/PlotSeries.js:        this.set('unit', valueMetadata.unit);
src/plugins/telemetryTable/TelemetryTable.js:                if (metadatum.unit !== undefined) {
src/plugins/telemetryTable/components/table-configuration.vue:                if (metadatum.unit !== undefined) {
src/plugins/telemetryTable/TelemetryTableUnitColumn.js:                    return this.metadatum.unit;
src/plugins/telemetryTable/TelemetryTableUnitColumn.js:                    return this.metadatum.unit;
src/plugins/telemetryTable/TelemetryTableUnitColumn.js:            return this.metadatum.unit;
```

...and `units`...
```
$> egrep -Rs -e "\.units" src/plugins/*
src/plugins/charts/scatter/ScatterPlotView.vue:            const xAxisUnit = xAxisMetadata.units ? `(${xAxisMetadata.units})` : '';
src/plugins/charts/scatter/ScatterPlotView.vue:            const yAxisUnit = yAxisMetadata.units ? `(${yAxisMetadata.units})` : '';
src/plugins/charts/scatter/ScatterPlotWithUnderlay.vue:                const unit = yAxisMetadata.units;
src/plugins/charts/bar/BarGraphPlot.vue:                const unit = yAxisMetadata.units;
src/plugins/charts/bar/BarGraphView.vue:            const xAxisUnit = xAxisMetadata.units ? `(${xAxisMetadata.units})` : '';
src/plugins/charts/bar/BarGraphView.vue:            const yAxisUnit = yAxisMetadata.units ? `(${yAxisMetadata.units})` : '';
src/plugins/gauge/components/Gauge.vue:            this.units = this.metadata.value(this.valueKey).unit || '';
src/plugins/plot/configuration/YAxisModel.js:                .map(s => (s.metadata ? s.metadata.value(s.get('yKey')).units : ''))
```

...and analysing the code, we can see that `unit` is apparently intended to be the final choice.

The plot series data to be plotted is defined by a `PlotSeries` object, which holds the reference metadata for updating the `unit` value in the collapsed or expanded plot legend, as well as the Y axis label, and stays synchronized with the input forms bound to the plot right pane.

<details>
<summary>Some details and references in the code...</summary>

- We can see how the field `unit` is retrieved and updated in the elements mentioned above: 
  https://github.com/nasa/openmct/blob/488cd82ae168a39c3d64a8224077972035b56a2d/src/plugins/plot/legend/PlotLegendItemCollapsed.vue#L113
  https://github.com/nasa/openmct/blob/488cd82ae168a39c3d64a8224077972035b56a2d/src/plugins/plot/legend/PlotLegendItemExpanded.vue#L152
  where `seriesObject` is the mentioned `PlotSeries` class source object, and we are retrieving `seriesObject.model.unit`.
- The model structure data is copied from the "value" blocks in the `PlotSeries.metadata` structure indexed by the `yKey`.
  https://github.com/nasa/openmct/blob/488cd82ae168a39c3d64a8224077972035b56a2d/src/plugins/plot/configuration/PlotSeries.js#L247
  https://github.com/nasa/openmct/blob/488cd82ae168a39c3d64a8224077972035b56a2d/src/plugins/plot/configuration/PlotSeries.js#L259
- This metadata structure is itself copied from the telemetry dictionary. 

</details>

The presence of `units` instead of the singular form `unit` appears to be a leftover after the change f03bfde on the telemetry tables mentioned by @AudunVN, and actually appears less often than the later.

Using `unit` over `units` indeed makes more sense as the later can be mistaken for a term relating to a number structure: tens, units, decimal point, tenths, hundredths, etc.

@jvigliotta , does this match the final choice for `unit` field in the Open-MCT plugins design?

**Comment by nunoguedelha** [comment]
Since this issue is about the documentation, I'll open a new one for covering the internal code inconsistencies and how they are affecting the app behaviour.

**Comment by charlesh88** [comment]
Verified fixed Testathon 2023-08-22.
