### ISSUE TITLE
[Notifications] Simplify DialogService for showing errors

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#361]
Currently to show a blocking error message requires something like:

``` javascript
    self.dialogService.showBlockingMessage({
        title: "Persistence Error",
        severity: "error",
        hint: error,
        primaryOption: {
            label: "ok",
            callback: function() {
                self.dialogService.dismiss();
            }
        }   
    }); 
```

I suspect that this is going to be a common use case, and I would suggest that a convenience method should be added that wrap this for error messages, so that we can make calls like

``` javascript
dialogService.error("Persistence Error", "Unable to persist object");
```

The method would be quite simple. eg.

``` javascript
DialogService.prototype.error(title, message){
    return this.showBlockingMessage({
        title: title,
        severity: "error",
        hint: message,
        model.primaryOption: {
            label: "ok",
            callback: function() {
                self.dialogService.dismiss();
            }
        }
    });
}
```

There are good reasons  to keep public interfaces simple on our services, but I think that this is a case where enough value is added to justify adding a public method.

**Comment by larkin** [comment]
Would rather have reasonable defaults instead of a separate function. Arguably, blocking dialog vs non blocking dialog is itself an option, not a different function.

if you don't specify options or primary option, default to an OK button for dismiss.

If you don't specify severity, default to error (it is blocking, afterall).

Etc.

Pete

On Dec 1, 2015, at 4:10 PM, akhenry <notifications@github.com<mailto:notifications@github.com>> wrote:


Currently to show a blocking error message requires something like:

    self.dialogService.showBlockingMessage({
        title: "Persistence Error",
        severity: "error",
        hint: error,
        primaryOption: {
            label: "ok",
            callback: function() {
                self.dialogService.dismiss();
            }
        }
    });

I suspect that this is going to be a common use case, and I would suggest that a convenience method should be added that wrap this for error messages, so that we can make calls like

dialogService.error("Persistence Error", "Unable to persist object");

The method would be quite simple. eg.

DialogService.prototype.error(title, message){
    return this.showBlockingMessage({
        title: title,
        severity: "error",
        hint: message,
        model.primaryOption: {
            label: "ok",
            callback: function() {
                self.dialogService.dismiss();
            }
        }
    });
}

There are good reasons to keep public interfaces simple on our services, but I think that this is a case where enough value is added to justify adding a public method.

**Comment by VWoeltjen** [comment]
Another option here (loosely inspired by #372) would be to add a single service that sits in front of these, providing _just_ methods at the particular severity:

| AlertService |
|------------------|
| info(title, [message], [options]) |
| warn(title, [message], [options]) |
| error(title, [message], [options]) |

The `options` argument could include a `{ blocking: true }` flag. The `AlertService` could also have some "smart" defaults for this - e.g. handle errors with blocking dialogs, handle info messages as notifications. (I suppose in practice it's generally well-specified which form of alert to use, but I like the principle of minimizing the amount of specificity needed for common cases.)

Obvious downside here: Adds another interface.
