### ISSUE TITLE
Build is Broken on Docker node:latest

### ISSUE THREAD

**Issue by zmgehlke** [nasa/openmct#3681]
Hi,

Sometime in the last two weeks, the build broke when using Docker containers.

This Dockerfile previous successfully built and now fails:
```
FROM node:latest

ARG srv_path="/srv/openmct"

# Install OpenMCT
RUN git clone https://github.com/nasa/openmct.git ${srv_path}
WORKDIR ${srv_path}
RUN npm install --legacy-peer-deps

ENTRYPOINT ["npm", "start"]
```

If you remove `--legacy-peer-deps` it fails due to version conflicts; if you include it, the build hangs.

Edit:

Including error logs without `--legacy-peer-deps`:
```
74 verbose cwd /srv/openmct
75 verbose Linux 4.15.0-132-generic
76 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
77 verbose node v15.8.0
78 verbose npm  v7.5.1
79 error code ERESOLVE
80 error ERESOLVE unable to resolve dependency tree
81 error
82 error While resolving: openmct@1.6.1-SNAPSHOT
82 error Found: eslint@7.0.0
82 error node_modules/eslint
82 error   dev eslint@"7.0.0" from the root project
82 error
82 error Could not resolve dependency:
82 error peer eslint@"^5.0.0 || ^6.0.0" from eslint-plugin-vue@6.2.2
82 error node_modules/eslint-plugin-vue
82 error   dev eslint-plugin-vue@"^6.0.0" from the root project
82 error
82 error Fix the upstream dependency conflict, or retry
82 error this command with --force, or --legacy-peer-deps
82 error to accept an incorrect (and potentially broken) dependency resolution.
82 error
82 error See /root/.npm/eresolve-report.txt for a full report.
83 verbose exit 1
```

**Comment by jvigliotta** [comment]
Hi @zmgehlke thanks for bringing this to our attention, @nikhilmandlik is going to take a look at this. We'll update when we have more information.

**Comment by rpearce** [comment]
I believe this is because node v15 is being used (which brings in npm 7, I believe), and that's where this behavior was introduced. The best way around this is to run `npm i --legacy-peer-deps`, like it says in the error message.

This is a good writeup: https://betterprogramming.pub/the-step-by-step-guide-to-understanding-and-adopting-npm-7-914504f7090f

**Comment by unlikelyzero** [comment]
@zmgehlke thank you for the bug report. It turns out that we do not currently support node:latest. Could you try to use one of the supported node versions 10-14?

To follow node:16 support, please follow this ticket https://github.com/nasa/openmct/issues/3966 . If you'd like to add support yourself, we welcome PRs! https://github.com/nasa/openmct/discussions/3821
