### ISSUE TITLE
Changing plot line rendering method seems to alter data

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3762]
Seen on hulk/dev this evening. While editing an Overlay plot, with this setup:

When I changed the line interpolation method for the low14num telem point, I got the following:

Suddenly, I got a lot more data points and the actual _values_ being plotted changed really significantly. 
Note that the pink trace for high14num was the first instance I saw of this problem and so has already been through this process.

Here's another example with captures just 13 seconds apart in real-time. 
Before:

After:

Filing as Blocker, as data appears to be really missing.

**Comment by akhenry** [comment]
The problem is almost certainly in the data rather than the plots themselves.

@shefalijoshi Could you take a look at this? I'd start by looking at the data that comes back from YAMCS in each of the cases highlighted above (see the email for the screenshots). I'll bet the plots are just showing what they get back from YAMCS.

**Comment by akhenry** [comment]
Turned out to be an issue with the local clock not syncing with network time which was causing data points to be discarded prematurely.
