### ISSUE TITLE
Support Inspection of Activities from Plans and Time Views

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3832]
Clicking on an activity in a plan or time view should reveal additional information about that activity in the inspector. 

This should make use of [the Selection API](https://github.com/nasa/openmct/blob/master/src/selection/Selection.js).

Some design is necessary to determine exactly what information is shown in the inspector on selection. We should also consider what occurs in the event of multiple activities being selected.

**Comment by shefalijoshi** [comment]
Testing Instructions:
Find a plan in the VIPER Plans folder (You should try fixed timespan ranges of 2020-08-01 to 2020-09-01 OR 2023-12-01 to 2024-01-01 to display content in a plan)
Once you see the plan content
**Single activity**
  Click on either a rectangle OR the text of an activity in the plan
  The inspector should be updated to show details of the activity as shown below (including the name, times)
  Ensure that durations are accurate

**2 Activities**
  Click on one activity and then command-click on another one so that 2 activities are selected.
  The inspector should update to show  (Convex Hull) details of the 2 selections including the aggregated times and gap/overlap.
  Ensure that durations are accurate

**3 or more Activities**
  Click on one activity and then command-click on another 2 or more so that many activities are selected.
  The inspector should update to show  (Convex Hull) details of the 3+ selections including the aggregated times. No gap/overlap should be shown.
  Ensure that durations are accurate

**Comment by jvigliotta** [comment]
Found a possible issue, most everything looks great, but when I select one item like below:
![Screen Shot 2021-07-13 at 11 06 13 AM](https://user-images.githubusercontent.com/12013460/125503410-8dbc2f35-c536-470a-8203-77202a21b197.png)

The total duration is 2hrs +

When I select a longer one with overlap like below:
![Screen Shot 2021-07-13 at 11 07 12 AM](https://user-images.githubusercontent.com/12013460/125503522-16ea9eba-94bc-4512-8b23-7828e56d8f30.png)

The overlap says 10hrs+ but shouldn't it be the originally selected items total duration?

**Comment by nikhilmandlik** [comment]
Tested with,
VIPER Sample Plan 2023-12-26 19:18:49.286Z - 2023-12-27 22:37:31.269Z
2024-02-17 17:53:59.469Z                    2024-02-18 17:53:59.469Z



> Click on either a rectangle OR the text of an activity in the plan

We should add `cursor: pointer;` and also should show selected activity name in inspector

Also issue @jvigliotta mentioned

**Comment by unlikelyzero** [comment]
@unlikelyzero  to file the bug and enhancements identified in this ticket
