### ISSUE TITLE
Update circle and karma to support chrome:latest testing

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#3860]
At the moment, our circleci test runner is using an unsupported and outdated version of firefox (77). This ticket captures the work necessary to move us to the _evergreen_ version of chrome. It would also be worth investigating what it would take to support Chrome canary as means to be aware of upcoming breaking changes.

### History
At some point, the circleci and karma config were modified to target FirefoxHeadless due to memory constraints.

### Links
[dockerhub circleci node images](https://hub.docker.com/r/circleci/node/tags?page=1&ordering=last_updated&name=13)
[Link to where the browser version in directly referenced in our ci config](https://github.com/nasa/openmct/blob/0da35a44b05925944aa27745f578b8af2aee9fbe/.circleci/config.yml#L5)
https://github.com/nasa/openmct/pull/3829 - Related PR which includes changes to specify ChromeHeadless over Firefox Headless

**Comment by akhenry** [comment]
Good call, the memory constraints that lead us to switch to FF originally were addressed properly in https://github.com/nasa/openmct/pull/3275 so that's no longer a factor in our choice of browser. Our target browser is Chrome, so that's where we should be looking for regressions.

The reason for locking to v77 was to do with a breaking change that was introduced in later versions of FF, but I believe this has been addressed.

**Comment by unlikelyzero** [comment]
Note: https://github.com/karma-runner/karma/issues/3676#issue-865625448

**Comment by kobe1104** [comment]
Verified fixed. Testathon 8/5/201.
I used this script to run the test on firefox: `npm run test:coverage:firefox`
