### ISSUE TITLE
Persistence errors for multiple users making new Snapshot entries in same Notebook

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#4122]
#### Summary
Seen during multi-user Notebook test of 8-16-21. Two users making new entries at the same time by dragging in Snapshots to the same page of the same Notebook caused one user to have persistence errors and lose their entry. 

#### Expected vs Current Behavior
Users must be able to create new entries in the Notebook without fear of collision and losing content.

#### Impact Check List
- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce
See Summary description. This may or may not be easily reproducible. From discussion with @akhenry, the fact that the users were creating new entries via Snapshots may be exacerbating the possibility of a race condition occurring in the Notebook.

#### Environment
* Open MCT Version: 1.7.4
* Deployment Type: stable build on a NASA server
* OS: Mac OS
* Browser: Chrome

**Comment by akhenry** [comment]
Even with the automatic synchronization of notebook models persistence conflicts are unavoidable. The act of updating a notebook causes a persistence event which may take a second or two for a simple entry on a slower connection. If another user modifies the notebook during this window then one of the users is going to be persisting a stale notebook model, and Couch will return a conflict response.

Handling this sort of persistence conflict generally is going to be really hard, and there is probably no "one size fits all" solution. The way we address this will probably depend upon the type of object, and perhaps even the type of operation being performed on the object.

In this case it may be sufficient to simply update the notebook model so it's no longer stale, and ask the user to try again, so long as this doesn't happen very often.

Longer term the "command pattern" might be applicable here. In the command pattern, any modifications to a notebook would be encapsulated in atomic "commands" that in the case of a persistence error can be simply be replayed onto the updated notebook object. Alternatively, we could attempt a merge of the two conflicting models, perhaps using something like [`_.merge`](https://lodash.com/docs#merge).

**Comment by akhenry** [comment]
Identified an issue that occurs with slow connections where one user adds an entry to  a shared notebook, and before that change has propagated to everybody another user creates a new entry. This will result in a 409 conflict error.

Have implemented a fix that detects this case, and attempts a merge of both notebook entries. There may be other edge cases where conflicts can occur on slow connections, but this will hopefully address the most common cause.

### Testing Instructions
1. Open the same notebook in two windows
2. Open Chrome dev tools in both windows, and switch to the Network tab
3. Change the "Not throttling" dropdown to "Slow 3G" in both windows.
4. In the first window add a new entry (eg. "A")
5. Switch to the second window quickly and enter another new entry (eg. "B").
6. Initially the second window will only show entry "B". After some time, entry A should also appear.
7. In the first window, after some time entry "B" will appear.

Additionally, some general testing of notebooks should occur in order to test for regressions.

**Comment by khalidadil** [comment]
I'm still seeing this issue.

**Comment by khalidadil** [comment]
https://user-images.githubusercontent.com/2343076/134084188-770468c2-5473-4fbb-8c44-53f437ad5af0.mov

**Comment by khalidadil** [comment]
Verified Fixed
