### ISSUE TITLE
[Enhancement] Selection API should support unselection

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#4164]
#### Summary

Clicking an object in navigation tree without a view provider does not unselect previous selection.

#### Expected vs Current Behavior

The previously selected object should be unselected, in which case the 3-dot menu actions, inspector views, etc. should be cleared. Or, there should just be some default fallback view provider that only is available for objects that don't have any other views, so that there are default 3-dot menu actions, inspector views, etc, but also so that the view dropdown doesn't ever show this as a choice.

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1. Select any object with a view
2. Select an object without a view (missing object, custom object types without view providers)
3. Observe 3-dot menu actions and inspector views are for the previously selected object
4. May need to disable a plugin in code for an already created object to create a missing object

#### Environment
* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

**Comment by davetsay** [comment]
@charlesh88 , would love to get your UX expertise when looking at some VISTA objects that currently don't have views. Also, would like to hear opinions on the idea of a default fallback view.

**Comment by charlesh88** [comment]
Beyond fixing this bug, we should file another issue, maybe in the VISTA repo, I don't think we have this problem in vanilla Open MCT. 

In short, all objects should have _some_ view. Containers that are used to subdivide large dictionaries (like "Dictionary" > "A" > "A001 - A099") could simply inherit the Folder view. A configured Data Set object could have a view that displays a read-only table of its name / value pair settings. If nothing else, we could create a standard "this view has no view" screen so that _something_ gets displayed, which is far better than the current nothing at all.

**Comment by charlesh88** [comment]
@davetsay Checking in on this issue, let's discuss possble options.

**Comment by davetsay** [comment]
Going to close this as not needed. Solution was to provide views for objects in which there were none. If needed in the future we can reopen.
