### ISSUE TITLE
Implement Telemetry Request Abort

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#4361]
**Is your feature request related to a problem? Please describe.**
Clicking multiple views in succession will continue to queue up requests, even if the view has been destroyed and the requests are not needed anymore. If enough requests are queued up the UI becomes unusable.

**Describe the solution you'd like**
Implement abort in views

**Additional context**
There should be partial implementation already.

VISTA ticket: https://github.jpl.nasa.gov/MissionControl/vista/issues/964

**Comment by akhenry** [comment]
I would like to see this implemented in the API if possible, so that we don't have to put a lot of boilerplate in individual views. On navigation the telemetry API could automatically abort the request and reject the promise. That way, our views would only need to handle rejected promises (which they should anyway) and would not need specific handling for handling abort.

The Telemetry API would just need to manage an AbortController and pass it down to the telemetry providers along with the passed in arguments. We will need to modify the telemetry provider interface slightly to include an optional abort controller. We should make sure that [the public documentation](https://github.com/nasa/openmct/blob/master/API.md#telemetry-providers) gets updated when we do this.

To detect navigation the telemetry API could listen to the ApplicationRouter's `'change:path'`.

**Comment by khalidadil** [comment]
Testing instructions:
1. Open a domainObject with telemetry on banner.
2. Open devtools and the network tab.
3. Navigate to another domainObject. You should see the old telemetry request has been aborted.

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 12/13/2021

Any existing telemetry requests were canceled.

**Comment by kobe1104** [comment]
Verified fixed - testathon 12/13/2021

**Comment by charlesh88** [comment]
Verified fixed Testathon 12-13-21.
![image](https://user-images.githubusercontent.com/1056412/145902788-a0e734d8-a9b9-418d-80af-ecae192e5724.png)

**Comment by nikhilmandlik** [comment]
Verified Fixed.
