### ISSUE TITLE
locator menus should all be alphabetically sorted

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#4466]
**Is your feature request related to a problem? Please describe.**
The object tree is now sorted alphabetically, but when I create an object, the locator menu is not sorted in the same manner.

**Describe the solution you'd like**
All locator menus (ex. object tree, create object menu, conditional style selector menu) should be sorted alphabetically.

see #1717

**Comment by jvigliotta** [comment]
This could be done by combining our two tree's. Currently we implement the locator selection tree (forms) separately from the main Open MCT tree (left hand sidebar). My suggestion, would be to enhance the main tree so that it can be used as a selection tree in forms, maybe by sending in a Boolean prop or something similar to let it know how to handle clicks.

**Comment by jvigliotta** [comment]
## Testing
- navigate around the normal tree on the left. Make sure navigation is working as expected
- create an item using the create + button
- when selecting a location, make sure you can navigate around the tree in the form as expected
- make sure you can select appropriate locations correctly
- create or navigate to a condition widget
- enter edit mode
- go to styles tab in inspector
- select a recently created or exiting condition set 
- make sure you can only select condition sets and that it works properly when selected

**Comment by charlesh88** [comment]
Testathon 1-24-22: verified fixed.
