### ISSUE TITLE
[CI] Determine why codecov.io is reporting ~50% coverage instead of ~70%

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#4563]
#### Summary
After https://github.com/nasa/openmct/issues/4561 we're reporting at 53%. Let's investigate why.

Also, need to learn about https://github.com/nasa/openmct/pull/4605#issuecomment-996509199

**Comment by akhenry** [comment]
Istanbul reports line coverage of ~ 70%
![Screen Shot 2021-12-10 at 4 20 36 PM](https://user-images.githubusercontent.com/4215777/145656427-aea65393-86df-429b-b623-fd278e07fd8b.png)

**Comment by akhenry** [comment]
@scottbell to investigate

**Comment by scottbell** [comment]
This PR in particular reduced coverage ~13%:
https://github.com/nasa/openmct/pull/4550

**Comment by unlikelyzero** [comment]
Our istanbul config may need to be modified to ignore our spec files
https://github.com/istanbuljs/nyc#using-include-and-exclude-arrays

**Comment by scottbell** [comment]
> Our istanbul config may need to be modified to ignore our spec files
> https://github.com/istanbuljs/nyc#using-include-and-exclude-arrays

Good find!

**Comment by scottbell** [comment]
@unlikelyzero found the answer. We were excluding *Spec.js files in Codecov (https://github.com/nasa/openmct/pull/4550) but not in our istanbul reporter. Because of this, there was a big drop in code coverage as we removed our ~99% code covered test files from the considered coverage set.

To remedy, I think we should make exclusions & inclusions primarily in istanbul, and use Codecov primarily a dumb report viewer. I've got a PR opened here to do this:
https://github.com/nasa/openmct/pull/4714

**Comment by unlikelyzero** [comment]
@scottbell can you add some testing note? Thanks!

**Comment by scottbell** [comment]
To test, ensure Codecov is reporting the lower 56% number for code coverage, which should be what istanbul is reporting too.

**Comment by shefalijoshi** [comment]
Verified Fixed
