### ISSUE TITLE
Limited Timezone options when creating a Clock object

### ISSUE THREAD

**Issue by AdamElliott-AB** [nasa/openmct#4578]
When creating a Clock object, the only timezone options are now "UTC" and "Etc/UTC". There used to be a lot more timezone options to choose from, such as "EST".

**Comment by akhenry** [comment]
@scottbell Would you mind taking a look at this one? Thanks!

**Comment by scottbell** [comment]
The two options presented are because the default timezone option for the Clock object of "UTC" matches both "UTC" and "Etc/UTC":
<img width="835" alt="image" src="https://user-images.githubusercontent.com/9853862/146927843-05d614c7-9ed6-4a93-a5f9-0c82b76bcd28.png">

If you start typing, all the timezone options are presented as this is an auto-complete form, though this behavior is somewhat hidden to the user:
![Dec-21-2021 13-00-24](https://user-images.githubusercontent.com/9853862/146926655-3c4f0cee-6b12-4f31-8683-cfd5c078a186.gif)

Here are some options I think for making this better:
1. Add some text for the user to the form label to indicate to the operator that the form is auto-completable (e.g., "type for more options").
2. Don't have a default time zone option for Clock and add placeholder text in the form to indicate to the user to "type for for more options".
3. Show all the options if the default time zone option is in use and the user has never clicked on the form
4. Only show the exact match for the timezone (not `includes`) if the user has never clicked on the form (i.e., exclude  "etc\UTC" from matching)
4. Remove "etc\UTC" from the available list of time zones entirely so we don't provide more than one option when creating a Clock
5. Some combination of the above

@akhenry @charlesh88 What do you all think?

**Comment by akhenry** [comment]
FWIW, the old behavior was to _always_ show all timezones when the user clicks the down arrow. Focusing on the text box and typing triggers autocomplete based on what the user has typed in -
![timezone](https://user-images.githubusercontent.com/4215777/148310830-e6beec47-310f-4386-9245-d4c92028f983.gif)

@charlesh88 Any preference for how we proceed here?

**Comment by akhenry** [comment]
@scottbell Let's just make it do what it used to do and move on. Thanks

**Comment by scottbell** [comment]
Wilco!

**Comment by scottbell** [comment]
I have a PR open for this issue here:
https://github.com/nasa/openmct/pull/4708

To test:
- Create a clock
- Click on the arrow to the right of the timezone
- Ensure you can see full list of time zones
- Type to filter, ensure filtering works

For animation of expected behavior, see:
https://github.com/nasa/openmct/issues/4578#issuecomment-1006197574

**Comment by charlesh88** [comment]
Verified fixed Testathon 2/17/22.

**Comment by shefalijoshi** [comment]
Verified fixed

**Comment by charlesh88** [comment]
Testathon 2024-03-20 cannot reproduce, fixed.
