### ISSUE TITLE
Lint precommit hook

### ISSUE THREAD

**Issue by depperm** [nasa/openmct#4610]
#### Summary
Currently anyone can commit and push code without it being in a passing state and then CI/CD will run various jobs on it to verify things like linting are done.

Instead I think pre-commit hooks should be used so that code is linted properly before committing. I've used [husky](https://www.npmjs.com/package/husky) before.

As an added bonus unit tests could also be run before committing using the same method

**Comment by unlikelyzero** [comment]
@depperm this has been discussed a few times before. We're purposefully not trying to block any sort of commits for any reason.

I think a post-commit hook might fit into our current development model. It's worth noting that our current linting rules are fine tuned. It can take up to 10 minutes to run a complete lint without some of the modifications on this line. https://github.com/nasa/openmct/blob/2d64813a4fa5bfb69f16f7ab8e2753f73f232a8b/package.json#L88

**Comment by akhenry** [comment]
Yeah, in my experience pre-commit hooks just serve to stop people from commiting, which we don't want. We want developers committing and pushing as often as they can because it provides a backup in the event of catastrophe.

Our PR hooks mean that nothing makes it into our master branch without being linted and tested, which I think provides a good balance of concerns here.

I'd also strongly encourage users to use real-time linting tools in their IDE, and we provide our [.eslintrc](https://github.com/nasa/openmct/blob/master/.eslintrc.js) file for that purpose.
