### ISSUE TITLE
[Search CouchDB] Duplicate results

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#4667]
#### Summary

When searching using CouchDB as persistence, each search item shows up twice. Selecting one, selects both, which means it's the same item.

#### Expected vs Current Behavior

One result per item.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Steps to Reproduce

1. Search using couch db persistence

**Comment by scottbell** [comment]
Looking into this

**Comment by scottbell** [comment]
Ah, I think I found the issue. It looks like CouchDB installs itself into [two different namespaces](https://github.com/nasa/openmct/blob/master/src/plugins/persistence/couch/plugin.js#L31): `""` and `"mct"`. We should be asking for only object providers that match the object's namespace here:
https://github.com/nasa/openmct/blob/master/src/api/objects/ObjectAPI.js#L233
Otherwise we return a search result for each namespace CouchDB is installed into (two in this case).

**Comment by scottbell** [comment]
What is still unclear to me is how this worked before.

**Comment by scottbell** [comment]
Ah, this is why:
https://github.com/nasa/openmct/pull/4583
which is a recent merge.

**Comment by scottbell** [comment]
@akhenry Not entirely sure how to resolve this. I can add a hack to search both, and then remove duplicates, but this seems a bit wacky.

**Comment by akhenry** [comment]
The reason this happens for search and not other object operations is because `openmct.objects.search` searches across all namespaces, whereas all other functions of the Object API are restricted to the namespace provided with the object identifier. This is my fault, I hadn't thought of the search use case.

There are two potential approaches here:
* We could separate out the search and CRUD operations of the CouchObjectProvider. A simple way of doing this might be to install disable search for the '' and 'mct' namespaces, and install a third object provider that is just for search. eg.
``` JavaScript

// src/plugins/persistence/couch/CouchObjectProvider.js
class CouchObjectProvider {
    //... Other stuff
    // Dummy search function. It has to appear to support search, otherwise the in-memory indexer will index all of its objects, but actually search results will be provided by a separate search provider
    search() {
        return Promise.resolve([]);
    }
}

// src/plugins/persistence/couch/CouchSearchProvider.js
class CouchSearchProvider {
    constructor (couchObjectProvider) {
        this.couchObjectProvider = couchObjectProvider
    }
    search(query, abortSignal) {
        const filter = {
        "selector": {
            "model": {
                "name": {
                    "$regex": `(?i)${query}`
                }
            }
        };

        return this.couchObjectProvider.getObjectsByFilter(filter, abortSignal);
    }
}

// src/plugins/persistence/couch/plugin.js
export default function CouchPlugin(options) {
    return function install(openmct) {
        //... Other stuff

        openmct.objects.addProvider(LEGACY_SPACE, install.couchProvider);
        openmct.objects.addProvider(NAMESPACE, install.couchProvider);
        openmct.objects.addProvider(COUCH_SEARCH_ONLY_NAMESPACE, new CouchSearchProvider(install.couchProvider));

```

* There may be issues with the previous approach that I haven't foreseen. A really kludgy but simple alternative is to just debounce CouchObjectProvider.search.

**Comment by akhenry** [comment]
@scottbell  Do you mind taking a look at this since you've started looking into it already and you're pretty familiar with the Couch provider?

**Comment by scottbell** [comment]
I'm a little worried with approach one that it's reliant on the timing of the query not being finished in time for the second query to delete itself. I could see situations where the timing that feeds outstanding searches changes (refactoring, errors in the first search, etc.) that would cause some cryptic behavior.

I like the second approach as it's introducing complexity into a place that's already got it, namely adding a third provider with the other namespaces. If the namespace issue gets resolved, we can remove the CouchSearchProvider too.

I'll take a start with option #2 👆 above if that works for you @akhenry. And thanks for the code!

**Comment by scottbell** [comment]
I've got a PR open for this here:
https://github.com/nasa/openmct/pull/4688

**Comment by jvigliotta** [comment]
Confirmed Fixed - Testathon - 3/14/2022

**Comment by unlikelyzero** [comment]
e2e test.

e2e/tests/search.e2e.spec.js
```js
test.describe('Search Tests')
test('Two objects are returned from a single search')
1. Create two objects with a semi-unique name (could be a uuid)
2. Search for the objects in Tree
3. Verify that only those two objects are returned
```

**Comment by dimitriharding** [comment]
@unlikelyzero PR made #5171. 

A few things, I wasn't sure if I needed to do anything specific with couch DB before starting my tests, but I assumed that it's being used by default. If that's not the case, I would need guidance there. 

It should be noted that I also added two additional tests outside of what you requested in your [comment](https://github.com/nasa/openmct/issues/4667#issuecomment-1118032595) since I believed those would help with test coverage for search. 

Looking forward to any feedback!
