### ISSUE TITLE
[Build] Support IDE Intellisense 

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#4690]
#### Summary
Let's summarize what all is needed for IDE Intellisense support and maybe some links to how it works

Note: Added a Github Discussion for this Typescript topics: https://github.com/nasa/openmct/discussions/4693

**Comment by trusktr** [comment]
By default nothing is needed in VS Code and it will start automatically type checking things. This is why in a plain `.js` file, you can hover on a variable you declared, f.e. `const foo = 123`, and you will see that it tells you it is type number. VS Code does this with TypeScript.

However, if one adds a `tsconfig.json` file (the same config file that TypeScript would use if we were to compile typescript code to JS) to a project, then VS Code will use this to configure it internal TypeScript instance.

In the config file I added in https://github.com/nasa/openmct/pull/4643 specifies for VS Code to check plain JS files (i.e. actually show errors) due to the `checkJs` and `allowJs` options. These two options (along with the supplemental other ones like `strict: true` to enforce strict type checking), cause VS Code to actually show red squigglies on type errors.

Without `allowJs`/`checkJs`, no red squigglies will be shown by VS Code.

To test this out, you can write the following snippet in any file (while on that #4643 branch which isn't merged yet, and after all dependencies are installed) then you'll see a type error and you can hover on the variable names to see more information:

```js
/* @type {number} */
const foo = 123

/* @type {string} */
let bar = foo // type error: number is not assignable to string
```

Although this error is displayed by VS Code, it has nothing to do with our build system and that continues to work as-is. It is purely a cosmetic feature that we see in the editor for dev convenience (converting files to `.ts` would be a different effort that _would_ require build changes).

It's more like a lint feature that doesn't require code changes. If we want to, we can set `strict` to `false` which will make TypeScript automatically assign the type `any` to many variable, and will reduce the number of type errors at the loss of type safety (we have no type safety to begin with since we have a lot of plain JS without TS being able to infer types anyway), but this at least allows us to begin to write code that type checks, preventing some errors, and we can modify improve thing here or there little by little.

**Comment by unlikelyzero** [comment]
Verified Fixed

**Comment by nikhilmandlik** [comment]
Verified Fixed.
