### ISSUE TITLE
Plots in a Tabs View don't re-query when Time Conductor toggled to Local Clock

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#4777]
#### Summary
1. Place a Stacked Plot with some real-time data in a Tabs View.
1. Put the Time Conductor (TC) in Local Clock (RT) mode. Verify that data is visible that has some distinct values to it. 
1. Switch the TC to Fixed mode, then wait for a minute or two.
1. Switch the TC back to Local Clock.

Observe: the plot will draw traces from the time in which the TC was switched to Fixed mode directly to the time in which it was switched back to RT. This may not be the case for all plots, see this example:

It should have re-queried and filled in the data for all plots in the view.

#### Impact Check List

- [X] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [X] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Environment
* Open MCT Version: 1.8.3
* Deployment Type: /stable
* OS: Mac
* Browser: Chrome

**Comment by davetsay** [comment]
We need to make sure when fixing this that eager load true does not break. the requests (that aren't happening) @charlesh88 is talking about should happen for the current tab and also all other tabs. Then, on tab change no new requests should be made.

**Comment by charlesh88** [comment]
Repro steps update: initially it was thought that Eager load had to be set true, but we just retested during Testathon today and determined that the setting doesn't matter.

**Comment by shefalijoshi** [comment]
Testing instructions:
View a plot with good data.
Switch between Local Clock and Fixed time span and ensure that data is requested for the bounds given.

**Comment by akhenry** [comment]
Verified fixed

**Comment by akhenry** [comment]
The issue here is actually that historical data retrieval is extremely slow in the test environment, and there is no visual indication provided to the user that historical requests are still outstanding. ie. there is no spinner being shown.

In attempting to reproduce this, the plot did _eventually_ fill in the missing data, it's just taking several minutes for Yamcs to return historical data at times due to .

I do not think that the answer to this is to show the spinner in this case, we should not prevent the user from seeing the data already in the plot, but we should tell them subtly that we are fetching the "missing" data.

**Comment by akhenry** [comment]
We should re-test the issue as originally reported and verify that it is actually fixed. There is a secondary issue of plots not showing a spinner when historical queries are outstanding, which I will create a separate issue for.

**Comment by davetsay** [comment]
verified

**Comment by unlikelyzero** [comment]
We need an explicit test for this
