### ISSUE TITLE
Changing object name from edit properties does not get re-indexed for search

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#4948]
#### Summary
Dependent on #4947. #4947 introduces this bug but its a required fix as it fixes basic search capability and fixes performance issue.

Name changes from the tree context action edit properties does not re-index the new name for search. Name changes from object view do.

#### Expected vs Current Behavior
Expect search to match for latest name of an object if updated. Updating name using tree context action edit properties does not change the search index, so the old name will return the new object, but the new name will not have any search results.

#### Steps to Reproduce
1. search for an existing object by name
2. verify search results include object
3. right-click object in tree and select edit properties action
4. change name and save
5. search again for object
6. expect search using past name returns no results and expect search using current name to have search result

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [] Does this impact a critical component?
- [] Is this just a visual bug with no functional impact?

**Comment by davetsay** [comment]
@scottbell , if you have time can you investigate this bug introduced by #4946. Until this is merged you can look at branch `search-fix-identifier`. I don't think this is a bug with the search observers. Not exactly sure why the action doesn't seem to be mutating the object. The tree isn't using full domain objects, but I would assume the action does...

Changing name via the object view browse bar does get picked up. Just the context action name change doesn't.

**Comment by scottbell** [comment]
@davetsay The issue is the BrowseBar calls mutate using the name field:
https://github.com/nasa/openmct/blob/master/src/ui/layout/BrowseBar.vue#L274
but the EditProperties field merely saves the object without any specific mutation events:
https://github.com/nasa/openmct/blob/master/src/plugins/formActions/EditPropertiesAction.js#L81

This triggers the Kleene star object observer (as it was before #4946), but not the specific "name" filter. The obvious thing to do, namely triggering a mutation event in EditPropertiesAction if the name property was changed:
https://github.com/nasa/openmct/blob/search-fix-identifier/src/plugins/formActions/EditPropertiesAction.js#L56
will cause another roundtrip for the persistence. As the mutation will cause a save event, and so on. Is this acceptable? Should we try to wrap this in a transaction, or is it not worth it?
