### ISSUE TITLE
[Sine Wave Generator] Clicking on the plot causes duplicate plot points to appear

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#5395]
#### Summary

Clicking on a Sine Wave Generator plot causes the plot points to duplicate. 

https://user-images.githubusercontent.com/9259993/176006589-606cdf90-b5f8-4b44-95a7-22ce8d8037fc.mov

#### Expected vs Current Behavior

The plot points should not duplicate.

#### Steps to Reproduce

1. Create a Sine Wave Generator with some randomness value (makes it easier to see what's happening)
2. Click on the Plot a bunch of times
3. See that more plot points appear

Note that this occurs with or without a randomness value. It's just easier to see if there is a randomness value as the plot points appear randomly instead of overlayed on existing points.

#### Environment

Version: 2.0.5
Build Date: Mon Jun 27 2022 10:52:33 GMT-0700 (Pacific Daylight Time)
Revision: 00a5cbd2fd2a68de2c5ad7b385bafbe90c98903d
Branch: release/2.0.5

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [x] Does this have an impact on Performance?

**Comment by akhenry** [comment]
The problem here is that clicking on a plot causes a historical telemetry request. This is a regression of a bug we have fixed at least twice already.

It's adding new points because the SWG generates values randomly (when the randomness option is switched on). The plot thinks a zoom has been requested, issues a historical request for the same bounds (because the user didn't really zoom), and then merges the results (because that's how zoom works in the plot).

**Comment by akhenry** [comment]
Reclassifying as critical, no loss or misrepresentation of data here.

**Comment by akhenry** [comment]
Need an e2e here to verify that the Plot does not issue a historical request on mouse click.

**Comment by ozyx** [comment]
Verified Testathon 09/30/22

Clicking on the SWG plot w/ randomness no longer created ghost plot points

**Comment by rukmini-bose** [comment]
Verified Testathon 9/30/22
