### ISSUE TITLE
Gauge allows bad drag and drop

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#5536]
#### Summary
The Gauge needs to follow the same rules about drag and drop composition as other telemetry views like plots, but isn't.

#### Expected vs Current Behavior
Gauge should follow the composition rules that plots use.

#### Steps to Reproduce

1. Create or edit a Gauge.
2. Drag a telemetry point into the Gauge to add it. This can be done from the tree, or search results. This should work.
3. Drag a disallowed object type (folder, layout, imagery, etc.) into the Gauge. This should be disallowed, but isn't.

#### Environment

* Open MCT Version:  R 2.0.5
* Deployment Type:  /testathon
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by charlesh88** [comment]
### Testing Notes
1. Create of edit a Gauge. 
2. Drag and drop a numeric data source such as telemetry or a Sine Wave Generator on the Gauge: verify that
this is allowed and works as expected. If the Gauge already has a data source, you may see a notification message that the action  will replace it.
3. Drag and drop a non-numeric data source on the Gauge. Verify that this is not allowed in the same way as on other similar data views such as an Overlay Plot.
4. Repeat step 3 with a non-data object such as a Folder or layout.

**Comment by rukmini-bose** [comment]
Verified Testathon 11/16. 

I did notice one REALLY minor thing. If you drag a telemetry point in a gauge that already contains another telemetry point, notice the confirmation dialog pop up. However, if you press "Cancel", the gauge's telemetry goes blank until you refresh/nav away and back. The telemetry is still flowing, as you can tell in the picture that the staleness indicator turns on and off, but the user just can't see it.  Its a small visual inconvenience, but I honestly don't think we need to spend any time fixing it since refreshing fixes the problem.

<img width="1023" alt="Screenshot 2023-11-16 at 2 40 17 PM" src="https://github.com/nasa/openmct/assets/48999852/289d104b-bce1-497e-8622-8c6136ff03a6">
