### ISSUE TITLE
[Import/Export] Example Display Layouts are broken on Import or Export

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#5857]
#### Summary
@charlesh88 created an example display layout which best illustrates a Mission Display. After importing, I noticed that the layouts did not match what was represented in the email

#### Expected vs Current Behavior
Import
![Screen Shot 2022-10-07 at 1 22 50 PM](https://user-images.githubusercontent.com/12446869/194646961-10a28cf1-0bc4-4530-b009-aba1cd40b1d3.png)

Exported by Charles
![thumbnail_image](https://user-images.githubusercontent.com/12446869/194647082-357a9581-0d5b-4d38-b390-f682cd5ae30d.png)

#### Steps to Reproduce
1. Import the Display Layout from ./e2e/test-data/ExampleDisplayLayout.json
2. Note how the display does not match the screenshot from the initial export

#### Environment
* Open MCT Version: 2.1.1

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by charlesh88** [comment]
Wow! As mentioned in email, this export was the result of exporting a folder with aliases to two layouts. I've attached that original export here, as well as an export of my My Items folder which holds the two layout's originals.

**Newly exported My Items folder that contains the two layouts, as well as a number of other things.**
[Open MCT Examples 10-05-22.json.zip](https://github.com/nasa/openmct/files/9737560/Open.MCT.Examples.10-05-22.json.zip)

**The original 'bad' export file cited in the bug.**
[CH My Items export 10-07-22.json.zip](https://github.com/nasa/openmct/files/9737559/CH.My.Items.export.10-07-22.json.zip)

**Correct version of 'Display Layout Example 1'**
![Screen Shot 2022-10-07 at 2 19 50 PM](https://user-images.githubusercontent.com/1056412/194656379-d086ad35-8546-4fc4-a699-9e37f5192753.png)

**Correct version of 'Flexible Layout Example 1'**
![Screen Shot 2022-10-07 at 2 20 00 PM](https://user-images.githubusercontent.com/1056412/194656430-1236ba78-5cb0-422c-bec2-6c9fa481fd50.png)

**Comment by charlesh88** [comment]
I tried importing my own previously exported file '[CH My Items export 10-07-22.json.zip](https://github.com/nasa/openmct/files/9737559/CH.My.Items.export.10-07-22.json.zip)' at got these results. In short, the Display Layout was severely broken and identical to what @unlikelyzero observed, while the Flexible Layout is identical to its original.

![Screen Shot 2022-10-07 at 2 27 13 PM](https://user-images.githubusercontent.com/1056412/194663333-e6940003-0280-46be-aeb2-7eccd793f662.png)
![Screen Shot 2022-10-07 at 2 27 20 PM](https://user-images.githubusercontent.com/1056412/194667551-369d68fa-6d57-4264-bf1d-0a009cbb9e93.png)


I also reimported my own My Items export, and in that version the Flex Layout was again identical to the original, while the Display Layout was _mostly_ correct, with a misplaced alphanumeric (upper left), which is a known (?) issue:

![Screen Shot 2022-10-07 at 2 34 31 PM](https://user-images.githubusercontent.com/1056412/194664339-7b48a233-bd8c-42bd-a5ca-95d13a367703.png)

A couple thoughts: how do we (do we?) handle in exports Condition Sets that are used by domain objects like Condition Widgets if the export doesn't include a folder that contains them? For example, what happens if the user exports 'Display Layout' below?
```
> Folder
  > Condition Set
  > Display Layout
    > Condition Widget (that uses Folder > Condition Set)
```
What location does the Condition Widget's styling Condition Set use? Looking in the 10-05 export JSON file, the '210 Condition Set' object has the property of `location: null`. Is this part of the problem?

**Comment by shefalijoshi** [comment]
Are display layout imports that Don't use condition sets also broken?

**Comment by shefalijoshi** [comment]
> 

@charlesh88 I tried to export a Display layout with a condition widget and condition set like you mentioned and did not have any trouble importing it between Firefox and Chrome browsers on my computer. The layout was fine when imported.
There must be something else going on.

**Comment by charlesh88** [comment]
> @charlesh88 I tried to export a Display layout with a condition widget and condition set like you mentioned and did not have any trouble importing it between Firefox and Chrome browsers on my computer. The layout was fine when imported.
> There must be something else going on.
Some of the elements in use (SWGs, Condition Sets, etc.) are kind of old, so wondering if that’s a factor.

**Comment by charlesh88** [comment]
@shefalijoshi Some of the elements in use (SWGs, Condition Sets, etc.) are kind of old, so wondering if that’s a factor.

**Comment by shefalijoshi** [comment]
I'm unable to reproduce this on either 2.1.1 or 2.1.2 locally. (localhost:8080)
this is what I see when I import it.
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/5247066/197831312-98b3feff-ce9a-4dfc-a4af-1860c4d16bae.png">

**Comment by unlikelyzero** [comment]
adding @charlesh88 to help in the investigation

**Comment by unlikelyzero** [comment]
Cannot reproduce with 2.1.1 or 2.1.2. Will close this and remember that it exists 👀
