### ISSUE TITLE
[Edit] Add Save options

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#588]
<p>Support multiple save options from the Edit user interface. User should be able to Save and return to browse, or Save and continue editing. See UI documents for design details.</p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-376
Originally created: Fri, 12 Sep 2014 06:01:41 -0700
Updated: Thu, 14 Jan 2016 16:32:54 -0800

**Comment by BogdanAlexandru** [comment]
This looks fun, I can take it if nobody minds. Are the mentioned UI docs publicly available anywhere (if they refer to anything other than the general architecture design, for example mock-ups)?

**Comment by VWoeltjen** [comment]
Thanks, we'd appreciate the help! @charlesh88 - do you have relevant UI docs that you could share here?

**Comment by charlesh88** [comment]
Yes, this has been designed: please see page 29 of the UI doc. A couple notes, as we've not really paid much attention to this for a while:

- In the menu, "Save" should be changed to "Save and Done Editing".
- You'll need an icon for the "Save and Continue Editing" - I can provide this once code is stubbed in, just use the standard Save icon for that as well for now.
- The menu should use our existing dropdown menu control.

**Comment by BogdanAlexandru** [comment]
Any chance you could point me to the doc? Couldn't find anything related to the UI in the repo, so I'm not sure it's in a public location. Did I miss it somehow?

**Comment by VWoeltjen** [comment]
Here's a relevant snippet from the UI docs:

![screen shot 2016-08-30 at 10 45 23 am](https://cloud.githubusercontent.com/assets/1685764/18100648/ae9f9f48-6ea0-11e6-9061-12aa25e56125.png)

I think this would just need:

1. An additional action ("Save and Continue Editing") 
2. Changes to the UI to add the drop-down style button. 

These two elements could be split up into separate tasks/PRs as well.

**Comment by BogdanAlexandru** [comment]
Awesome, thanks for the snippet! I'll get to it.

**Comment by BogdanAlexandru** [comment]
Would it be considered a breaking change if we made the default Save action not close the editor anymore? Looking at Open MCT itself it doesn't look like a big deal but I'm not sure how much derivatives like WARP and VISTA rely on the current behavior of the Save action. It's tempting to define a new SaveAndCloseEditor action along the lines of `Save.perform().then(closeEditor)`.

Aside from that, the idea that a save finishes editing seems to be ingrained in more than the save action. The EditorCapability also triggers an editor close on Save because it marks the status of the object as not being edited anymore. An alternative to the capability's save would be necessary there that I think will not do much more than `transaction.commit().then(startNewTransaction)`. An "apply" of sorts.
I'm still digging through the code to understand what happens around there. It appears that the item being edited still gets saved saved even though I don't explicitly start a new transaction for it after I commit the previous. This might be a bug or an architectural decision that I'm not familiar with. I should be able to get to the bottom of it this weekend once I get more time to look at it.

**Comment by akhenry** [comment]
> Would it be considered a breaking change if we made the default Save action not close the editor anymore?

I think this would be ok, so long as the user experience remains the same (ie. the button labelled "Save" still saves and exits). I think your approach to defining a new `SaveAndCloseAction` by chaining off of a redefined `SaveAction` actually makes a lot of sense.

@larkin / @VWoeltjen - does VISTA define any custom behavior on save? I know it [exhibits custom behavior at times](#1080) 😃 

You're correct that editing is effectively cancelled by `EditorCapability.save()`. I'd be inclined to redefine this as well and remove the status change. Then in `SaveAndCloseEditorAction` you could call `save()` then `cancel()`.

**Comment by VWoeltjen** [comment]
> It's tempting to define a new SaveAndCloseEditorAction along the lines of SaveAction.perform().then(closeEditor).

:+1: I think that's a smart idea. Separating out the "save" part from the "finish editing" part is a very sensible refactor for the existing SaveAction (and `save` method of EditorCapability), and makes the "save and continue editing" action much easier.

Using Cancel to mean "finish editing" is a little iffy to me semantically ("Cancel = Revert Changes + Finish Editing" seems more correct to me) but I don't think this will cause problems in practice. Cancel is already smart about not refreshing objects that aren't dirty.

> @larkin / @VWoeltjen - does VISTA define any custom behavior on save? I know it exhibits custom behavior at times 😃 

Nope, this should be a non-breaking change for WARP/VISTA.

**Comment by BogdanAlexandru** [comment]
Thanks for the answers!

> Using Cancel to mean "finish editing" is a little iffy to me semantically

Good point; in practice this will be averted I think by the fact that cancel is part of the EditorCapability, so the actual code using it will look something like:

```
function closeEditor() {
     return domainObject.getCapability("editor").cancel();
}

return saveAction.perform()
    .then(closeEditor);
```

Which makes it clear that closing the editor is what we want and `cancel()` is just the means through which we do it - we just saved so the reverted changes part shouldn't affect us.

**Comment by BogdanAlexandru** [comment]
Referencing this here as I think it'll either alter or make it obsolete: https://github.com/nasa/openmct/issues/975

**Comment by akhenry** [comment]
> Using Cancel to mean "finish editing" is a little iffy to me semantically ("Cancel = Revert Changes + Finish Editing"

Agreed, it's a little confusing. Could be renamed to `.end()` or `.finish()`?

**Comment by BogdanAlexandru** [comment]
I'll rename it, sure thing.

I ran into an issue. It seems that the Action's `navigate()` also made the saving dialog "exit" early (or be hidden). If this comment is still up to date:

```
// Discard the current root view (which will be the editing
// UI, which will have been pushed atop the Browse UI.)
function returnToBrowse(object)
```

that's probably why. This doesn't affect the functionality at all, but if saving takes very little time the dialog still shows up and then goes away in a fraction of a second. This can look a bit sloppy. See this gif:
http://i.imgur.com/iJqu2C9.gif

Do we want to block this issue until we fix the dialog? Technically it won't manifest without these changes, but it's easy to repro it if we want to fix it in isolation: make the SaveAction not navigate anymore and rely only on the EditorCapability to close the editor.

**Comment by VWoeltjen** [comment]
I think the dialog still makes sense for Save and Continue, but the fact that it flashes like that for saves that resolve quickly isn't great. I've seen that occur during "regular" Save as well, but it looks much more distracting in the midst of an editing session.

I do think we need to improve our UX here (filed #1168) but I don't think we need to block this issue for it. The dialog is annoying but not incorrect, and since most of our deployments use a remote persistence store, often the Save will take long enough that the dialog is just useful.

**Comment by BogdanAlexandru** [comment]
There's one last thing that prevents me from filing a PR for the commands themselves, testing `SaveAndStopEditingAction`. Since `SaveAndStopEditingAction` is really more or less a "proxy" for `SaveAction` relying on it for everything minus closing the editor, you'd just mock away `SaveAction` and test that it gets interacted with properly. This is kinda tricky because `SaveAction` is a module dependency. I've seen Squire being mentioned in the new API docs, but it doesn't seem like it's ever been used in Open MCT. I also haven't seen another case where an action uses another to do its thing.

Considering Squire for just this test seems like overkill, but to my knowledge the only alternative is to turn `SaveAndStopEditingActionSpec` into an integration test and basically copy-paste more or less everything from `SaveActionSpec` to make sure stuff is set up properly for `SaveAction` to do its thing. The validation logic also ends up being mostly identical.

Any thoughts on the right approach here?

**Comment by VWoeltjen** [comment]
There will probably be some redundancy in the test setups (especially setting up mocks.) Aside from that, when there's a uses or extends relationship in a class, we generally only verify the new behavior of the using/extending class, under the assumption that the used/extended behavior has its own tests. (Code coverage verification & reporting helps to verify that assumption.) In other words, for `SaveAndStopEditingActionSpec`, I'd just focus on verifying that it invokes the cancel behavior after save behavior (based on some evidence of the save occurring.)

Some options I see:

1. Use dependency injection as a code style. `SaveAndStopEditingAction` instantiates a `SaveAction`, then passes that into (and returns) a `SaveAndStopEditingActionImpl` which uses it. The `SaveAction` can be mocked and the interactions verified that way. This is great for testability, but does result in extra classes/scripts that don't have a real function.
2. Be white-boxy, and spy on the private instance of `SaveAction` that is being used by `SaveAndStopEditingAction` explicitly from the spec to verify that interaction. (If `SaveAction` is instead inherited from, you could temporarily spy on `SaveAction.prototype.perform` to achieve the same result.)
3. Just provide the dependencies that `SaveAction` needs and let it run. Use some other call (e.g. `editorCapability.save()`) to verify that the "save" part occurs, but otherwise just verify the behavior that is implemented in `SaveAndStopEditingAction`.

I think Option 3 is the simplest and has the fewest drawbacks, but if that starts looking uglier than I'm imagining, the others would also work.

**Comment by BogdanAlexandru** [comment]
I went with option 3, I forgot about `appliesTo`. That one is part of `SaveAndStopEditingAction`'s interface so it should be covered. It makes more of the redundant mocking not be redundant anymore.

**Comment by BogdanAlexandru** [comment]
I'm doing bad with the available time to spend on the UI part. If this is still around when the weekend starts, I'll resume work on it.

If anyone feels like they could do it quicker, I think there should be no problem altering the UI independent of my PR: https://github.com/nasa/openmct/pull/1170 at least until the end when it comes to linking each save option to their specific actions (which can be a final commit after the actions get merged).

**Comment by BogdanAlexandru** [comment]
I've got a few questions to make sure I did the right thing.

**Design-wise:**
Is this what we want?
![Imgur](http://i.imgur.com/h7O0db1.png)
I tried to keep the options blue-like:
![Imgur](http://i.imgur.com/6mCiBCB.png)
But this seems to only be possible if the parent button stops being `major`, which is most likely not what we want (in the snippet from the docs the button is major).

Tried searching for a way to remove the inherited `major` from the menu but so far I've found that it's not possible to remove inherited CSS from specific elements (this is my first contact with anything webdev so it's likely I'm not aware of alternatives - what I didn't want to try is dive into `major` and make changes that would affect everything in the app). But if the first version is what we want and `major` affecting its children isn't a bug, then this is a non-problem.

**Logic-wise:**
I gave the save actions their own category (right now called `save`), so that I could differentiate them from the others which end up being just buttons. This makes __EditActionController.js__ keep track of two sets of actions:

```
$scope.saveActions = $scope.action ?
            $scope.action.getActions(SAVE_ACTION_CONTEXT) :
            [];
$scope.otherEditActions = $scope.action ?
            $scope.action.getActions(OTHERS_ACTION_CONTEXT) :
            [];
```

And the __edit-action-buttons.html__ template decides based on the number of save actions whether it shows a button or a dropdown.

```
<span ng-if="saveActions.length === 1">
    <a class='s-button major {{saveActions[0].getMetadata().cssclass}}'
        title='{{saveActions[0].getMetadata().name}}'
        ng-click="saveActions[0].perform()">
        <span class="title-label">{{saveActions[0].getMetadata().name}}</span>
    </a>
</span>

<div ng-if="saveActions.length > 1"
        ng-controller="ClickAwayController as toggle"
        class="btn-bar right menu-element s-menu-button major icon-save no-label" 
        ng-click="toggle.toggle()">
    <div class="menu" ng-show="toggle.isActive()">
        <ul>
            <li ng-repeat="saveAction in saveActions"
                class='{{saveAction.getMetadata().cssclass}}'
                ng-click="saveAction.perform()">
                {{saveAction.getMetadata().name}}
            </li>
        </ul>
    </div>
</div>
```
This is useful so that the Save As action appears as a button still while belonging to the new `save` category.

I initially thought about attaching arbitrary tags to actions (so that we'd have all the save actions be in the `conclude-editing` category but with the `save` tag) and then `filter()` to separate the actions based on tags, but the docs mention that the metadata has a predefined structure. I think using multiple categories would work somewhat similarly to tags (each save action would have `["conclude-editing", "save"]`.

In any case, just defining a separate category for the save actions seems like the simplest and most straightforward approach to me. Thoughts?

**Comment by BogdanAlexandru** [comment]
@charlesh88 @VWoeltjen 
> The menu should use our existing dropdown menu control.

Should've probably asked this first, but which one is that concretely? I got this to work using a `ClickAwayController` similar to how the Create and Switch View dropdowns use. But after I was done I noticed there's also the arrow menu which seems to be 100% action focused but on the other hand appears to be dedicated to context menus.

The end result looks like this: [gif](http://i.imgur.com/PF2Y6Ro.gifv)

The __edit-action-buttons.html__ template now treats the save actions separately, and if there's just one, it creates a button for it (this is what makes Save As still show up as a button), otherwise it creates a dropdown. It looks like this:

```html
<span ng-if="saveActions.length === 1">
    <a class='s-button major {{saveActions[0].getMetadata().cssclass}}'
        title='{{saveActions[0].getMetadata().name}}'
        ng-click="saveActions[0].perform()">
        <span class="title-label">{{saveActions[0].getMetadata().name}}</span>
    </a>
</span>

<div ng-if="saveActions.length > 1"
        ng-controller="ClickAwayController as toggle"
        class="btn-bar right menu-element s-menu-button major icon-save no-label" 
        ng-click="toggle.toggle()">
    <div class="menu" ng-show="toggle.isActive()">
        <ul>
            <li ng-repeat="saveAction in saveActions"
                class='{{saveAction.getMetadata().cssclass}}'
                ng-click="saveAction.perform()">
                {{saveAction.getMetadata().name}}
            </li>
        </ul>
    </div>
</div>

<span ng-repeat="currentAction in otherEditActions">
    <a class='s-button {{currentAction.getMetadata().cssclass}}'
        title='{{currentAction.getMetadata().name}}'
        ng-click="currentAction.perform()"
        ng-class="{ major: $index === 0 && saveActions.length === 0 }">
        <span class="title-label">{{currentAction.getMetadata().name}}</span>
    </a>
</span>
```

Essentially I moved the save actions to their own "save" category, so `EditActionController` keeps track of two sets of actions (`saveActions` and `otherEditActions`). I found this to be simple and straightforward; I think the HTML template could be further simplified so the Save As button gets automatically handled via the repeat for `otherEditActions`, but that'd be at the expense of more controller complexity so I'm not sure it's an okay goal.

Let me know if my current implementation misses the point completely or needs changes.

**Comment by akhenry** [comment]
@BogdanAlexandru I think the approach you're taking is great, nice work. Grouping save actions into a new category seems to me like the cleanest way to do this. 

I think that the `menu-button` control (passed as a key to an `mct-control` directive) would probably be the right control to use here. It should save you some boilerplate in the markup.  @charlesh88 jump in and correct me if this is not the right one to use here.

**Comment by BogdanAlexandru** [comment]
Thanks for pointing me to `mct-control`! It's a totally different thing from what I was doing, haha. Sorry for my ignorance, this is my first attempt at anything webdev and comprehending how everything gets glued together is definitely one of the most challenging things I've been through lately.

`menu-button` appears to use its own layer of abstraction so a bit of conversion was necessary in the controller but the markup definitely looks a lot cleaner.

```
<mct-control key="'menu-button'"
             structure="{
                options: saveActionsAsMenuOptions,
                click: saveActionMenuClickHandler,
                cssclass: 'btn-bar right icon-save no-label major'
             }">
</mct-control>
```

@charlesh88 Can you send me the icon for the Save and Continue Editing option when you get the chance?

**Comment by VWoeltjen** [comment]
Verified in testathon 20161021

**Comment by charlesh88** [comment]
Somewhat verified in Testathon 2016-10-21, see #1275.

**Comment by VWoeltjen** [comment]
Is there any aberrant behavior here that is not covered by #1275? If not, would prefer to keep this issue closed to avoid double-tracking the issue

**Comment by larkin** [comment]
closing this to make it easy to review testathon status, we can reopen after we discuss.
