### ISSUE TITLE
[CouchDB] Creating an object hangs forever after receiving a conflict error

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#5982]
#### Summary

If a user attempts to create an object directly after receiving a 409 Conflict error from CouchDB, the object creation will fail and a ton of errors flood the console. After clicking "OK" on the Create dialog, the Save progress dialog will just hang. A refresh is needed to get the app back into a good state.

#### Expected vs Current Behavior

Open MCT should recover from conflict errors and the object should be able to be created

#### Steps to Reproduce

1. Launch Open MCT with a local CouchDB instance, and CouchDB plugin activated
2. Open two browsers to your local Open MCT instance (they can both be the same browser, e.g.: Chrome)
3. Prep both Open MCT instances to create an object (Clock, for example)
4. Click OK on one browser, then click OK on the other. This doesn't need to be completed in any specific amount of time.
5. Observe a conflict error on the second browser
6. Observe that only one clock appears under 'My Items' (due to conflict in 'My Items' composition)
7. On the browser that received a conflict error, click the "Create" button
8. Observe a ton of errors in the console
9. Select the folder to save it in, and click "OK"
10. Observe that the "Save" progress dialog just hangs

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

Errors in console after clicking "Create" post-conflict:
![image](https://user-images.githubusercontent.com/9259993/201776231-8adaa711-705d-468f-8135-84ec0f3f0da2.png)

**Comment by ozyx** [comment]
# Testing Instructions
1. Launch Open MCT with a local CouchDB instance, and CouchDB plugin activated
2. Open two browsers to your local Open MCT instance (they can both be the same browser, e.g.: Chrome)
3. Prep both Open MCT instances to create an object (Clock, for example)
4. Click OK on one browser, then click OK on the other. You can take up to 3 seconds to click OK on the second browser
5. Observe a conflict error on the second browser
6. Observe that only one clock appears under 'My Items' (due to conflict in 'My Items' composition)
7. On the browser that received a conflict error, click the "Create" button
8. Confirm that no errors appear in the console
9. Select the folder to save it in, and click "OK". Verify that Open MCT creates the object successfully and that it appears as a child of the selected parent object.

**Comment by akhenry** [comment]
In pre-merge testing I found that the original issue is, indeed, fixed! Awesome work.

I did find some odd behavior when _editing_ an existing display layout. These were my steps:
1. Open the same display layout in two browser windows
2. Make an edit in the first window and save it.
3. Make a different edit in the second window and save it. You should get a conflict error (correct!). 
4. Confusingly, you will also get a notification stating that the save was succesful.
5. Here's where it gets really weird. The display layout in the second (conflict) window is still showing the edit made in that window.
6. Click anywhere in the display layout
7. Note that the display layout will now suddenly update with the _remote_ changes.

In future we will have better handling for conflicts, but for now it would be great if we could refresh the model in conflict from the server. I think we're doing this already (which is why clicking, which is triggering the selection API, is causing the remote version of the object to appear magically), but for whatever reason the layout is not automatically refreshing its view from the fresh model after a failed save.

This approach will discard the user's local changes, but that's ok, we have no way of recovering them right now.

**Comment by shefalijoshi** [comment]
While I did not see any hanging after receiving a conflict error, I did observe the following:

In the view for the browser where the 1st object was saved (with no conflict), this is what I see in the tree (even after collapsing and expanding it) I needed to refresh the browser to get the 2nd object to show up.
<img width="272" alt="image" src="https://user-images.githubusercontent.com/5247066/209858559-3978a8aa-dd4c-4bc5-86b8-e24abad953e3.png">

In the view for the browser where the 2nd object was saved (conflict + re-saving), this is what I see in the tree (after collapsing and expanding)
<img width="270" alt="image" src="https://user-images.githubusercontent.com/5247066/209858635-f7b5f5ff-7027-48f3-a244-c95f65f78c40.png">

**Comment by unlikelyzero** [comment]
Re-verified on 2.1.4-ERT and 2.1.5
