### ISSUE TITLE
Searching on partial words gives puzzling results

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#603]
<p>Searching for "elphic" brings up results that make sense (items that have "elphic" in the name.</p> <p>However, searching on "el", "elp", or "elph" brings up items that don't have those sub-strings in their names. </p>

Migrated from: https://trunk.arc.nasa.gov/jira/browse/WTD-1544
Originally created: Thu, 17 Sep 2015 15:25:32 -0700
Updated: Thu, 7 Jan 2016 16:24:28 -0800

**Comment by VWoeltjen** [comment]
Migrated comment, from @charlesh88:
<blockquote>
<p>The issue here is that the results don't make it clear why something matched - this should be made clear.</p>
</blockquote>

**Comment by charlesh88** [comment]
Is #663 related to this?

**Comment by charlesh88** [comment]
Notes from tagup 10/26/16:
**Not a good candidate for Help Wanted at this time**
- Is related to #663.

**Comment by larkin** [comment]
Related to #132, problem is we are searching on invisible fields of the object, some of which are system properties.  In concert with #132 this can be rewritten as a more clear statement of intent.

**Comment by charlesh88** [comment]
Adding my thoughts on this. Possible solutions, easy (?) to hard:

1. If we're string matching against internal fields like GUIDs or something, we shouldn't do that. Until we redesign search results to add more contextual information on why something matched a query and/or add advanced search, I think we should limit search to the object's Title and Notes fields only - and I'm guessing that search currently doesn't encompass Notes yet. My thought is that this would be the simplest short-term enhancement we can do to make search results better.
1. Allow searching on the Notes field in addition to Title, and include a snippet of the object's Notes value in the result, Google-style. This makes Notes a lot more usable as an adhoc tagging solution.
1. Later, we can design a more robust results (Spotlight, other) that provides much more context on matching.
1. Advanced search lets the user define their own context directly, which then alters the perception of the results. For example, allow users to explicitly search the Notes field for a string, or find all telem points that had a value that exceeded an inputted value in a timeframe.

@larkin @VWoeltjen @akhenry Thoughts?

**Comment by akhenry** [comment]
Hrm, we don't seem to be explicitly searching across invisible properties. I assumed, based on observed behavior, that we were doing string matching on a `JSON.stringify`-ed version of the indexed objects, but based on the code it [looks like we are just indexing name](https://github.com/nasa/openmct/blob/c98286d426330bbfe1a4f7624211e908946ac213/platform/search/src/services/GenericSearchWorker.js#L36). I assume then that the behavior we're seeing is a result of ElasticSearch which presumably indexes everything (being agnostic of our particular object structure)

In any case, I agree that we should not match on hidden fields unless we can convey to the user why the match occurred. I actually think that the easiest thing to do right now, which will immediately remove ambiguity is to search name only. We can then progressively enhance search by adding other fields as time permits. Adding notes has obvious utility, but will require more effort to modify the search implementation and to incorporate notes snippets into the search results. If we match on notes, but don't show notes snippets in the results I fear users will still be confused by the results.

A search across everything is actually kinda nice because it means we don't need to build any assumptions about object structure into the search providers, and it works with all present and future object types. We would definitely need to enhance the search results to show why a match occurred though. We could use the registered object types to build a superset of property names to filter on, which can be selected or deselected by the user.

**Comment by larkin** [comment]
@akhenry elasticsearch search provider is across all fields, and is deployed in warp environment. That's where we see this.

**Comment by charlesh88** [comment]
Per @larkin let's have a way to disable ElasticSearch for search, which is a root of this problem. CH todo: create new issue for this and assign to Pete.

**Comment by charlesh88** [comment]
#1399 assigned to Pete.

**Comment by larkin** [comment]
Closed as wontfix. This was due to fuzzy elasticsearch searching on invisible fields of models.
