### ISSUE TITLE
Delete notifications independently

### ISSUE THREAD

**Issue by JonanOribe** [nasa/openmct#6073]
**Is your feature request related to a problem? Please describe.**

I would find interesting the possibility of deleting the notifications not only all at once, but by cherry picking with an X next to the notification. This is because there may be unimportant notifications that you don't want to keep, while others need to be reviewed. The current option is to delete all or none.

![image](https://user-images.githubusercontent.com/11914201/208936401-462bb41b-f83a-4f88-9d3b-95e8d0be5a9e.png) 

**Describe the solution you'd like**

Add delete option for every notification on the list.

**Comment by rukmini-bose** [comment]
Testathon 1/17/23 
Functionally, we can individually delete notifications so that's verified. 

However, I'm now noticing the following issue with notifications in general: After we click the notification button in the status bar for the first time to expand the notification overlay, and then close it afterwards– if you continue to do any work in the same object (For example, editing the object and clicking "Save"), the expanded notification overlay opens automatically without even clicking it upon the object saving.

**Comment by rukmini-bose** [comment]
Testathon 1/17/23
Functionally, we can individually delete notifications so that's verified.

However, I'm now noticing the following issue with notifications in general: After we click the notification button in the status bar for the first time to expand the notification overlay, and then close it afterwards– if you continue to do any work in the same object (For example, editing the object and clicking "Save"), the expanded notification overlay opens automatically without even clicking it upon the object saving.

**Comment by 360macky** [comment]
Hi @rukmini-bose!

> However, I'm now noticing the following issue with notifications in general: After we click the notification button in the status bar for the first time to expand the notification overlay, and then close it afterwards– if you continue to do any work in the same object (For example, editing the object and clicking "Save"), the expanded notification overlay opens automatically without even clicking it upon the object saving.

I'm trying to repeat this behavior but I can't.

Does this happen exclusively with information notifications? Any particular object?

I'm from Open MCT Version: 2.1.5-SNAPSHOT on Mac OS.

**Comment by ozyx** [comment]
@rukmini-bose @360macky  : I'm seeing the same thing. Here's my steps to reproduce:

1. Create a new Overlay Plot
2. Before the "Save Successful" banner disappears, click on the "Notification" indicator to go into the notification overlay.
3. Press the "X" on the single notification in the overlay, the notification overlay should close
4. With the overlay plot still in edit mode, click "Save and Finish Editing"
5. See the notification overlay appears again, with the notification still there

**Comment by 360macky** [comment]
😬 Ohhh... Yes, I can see that, I'll see what's happening.
Thanks @rukmini-bose for opening #6130
