### ISSUE TITLE
inspector views tabs

### ISSUE THREAD

**Issue by davetsay** [nasa/openmct#6118]
**Summary**
Inspector views are getting more complex and there are more of them. We need a better way to organize them.

**Describe the solution you'd like**
TABS!

**Describe alternatives you've considered**
Accordions

**Testing Instructions**
1. put the inspector through its paces
    2. select different objects in the tree and see that the inspector displays context for the selection
    3. select different tabs and see that the inspector view changes appropriately
    4. go into and out of edit mode (both saving and exiting without saving)
    5. tabs should only be visible for intended selections and in correct state (edit mode, stylable, etc.)
1. some more specific tests
    2. plots have different view / edit inspector views
    3. folders and non-persistables should not display a styles tab
1. things to keep an eye out for
    2. wacky or super long tab names
    3. empty inspector views

**Comment by rukmini-bose** [comment]
Testathon Verified 3/9/22. 

Everything seems like its working, but I am noticing that for Display Layouts, the more elements exist in the object, the longer the "Elements" tab takes quite some time to load. I have a Display Layout with simply 6 objects in it, and the elements tab took 3 seconds to load. I almost thought it was broken at first glance since it was lagging. I'm just thinking about how this may be problematic in the future when it is being used for way more advanced layouts.

**Comment by shefalijoshi** [comment]
Verified. Looks really good!
Sometimes the tabs are too small to click on, but that's not something that can be helped.
