### ISSUE TITLE
Plot annotations aren't creatable

### ISSUE THREAD

**Issue by scottbell** [nasa/openmct#6157]
#### Summary
When you marquee plot points, they aren't being selected properly for annotation creation.

#### Expected vs Current Behavior
When using the marquee for annotations, plot points should glow.
Expected behavior:
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/9853862/214127560-215a0293-5f46-4d46-bbac-8cf5d0786ca2.png">

Current behavior:
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/9853862/214127210-ce6e530c-04eb-4611-bdfd-a1399f4aefdb.png">

#### Steps to Reproduce

1. Create a Sine Wave Generator
2. Put it into Fixed Time Mode
3. Hold Option+Shift and drag a marquee around some plot points
4. Ensure plot points are glowing and annotation inspector allows adding a tag

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by scottbell** [comment]
Tested and seems to be due to [this merge](https://github.com/nasa/openmct/issues/6157). Lots of overlapping code, so expected.

**Comment by scottbell** [comment]
This issue is due to the marquee y axis now being an array.

**Comment by shefalijoshi** [comment]
Testing instructions:
1. Create several sine wave generators with different offsets and ranges.
2. Add all but one of these sine wave generators to an overlay plot so that they are all on one y axis
3. Add annotations to points on the plots and confirm that they're saved and can be recalled.
4. Move some of the sine wave generators to different y axes
5. Ensure that the existing annotations correctly show up and scale to the y axis they're on.
6. Add the last sine wave generator to the overlay plot (this should have no annotations)
7. Ensure that the last sine wave generator does not show any annotations
8. Remove a sine wave generator from the overlay plot and ensure that the other sine wave generator annotations still show up and work correctly.

**Comment by ozyx** [comment]
Testathon 1/24/23

Mostly verified, was not able to confirm adding tags since no tags were configured on testathon. Dragging the marquee does highlight the area and points correctly

**Comment by charlesh88** [comment]
Verified fixed Testathon 2023-01-26.

**Comment by ozyx** [comment]
Verified fixed -- Testathon 2023-01-26

**Comment by rukmini-bose** [comment]
Verified 3/20/2024
