### ISSUE TITLE
[New Edit Mode] Remove Edit-related concerns from ContextMenuGesture

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#635]
From #481:

> * Remove Edit-related concerns from ContextMenuGesture
  * Menu should be suppressed in these cases, but responsibility for this suppressing should be externalized.

**Comment by akhenry** [comment]
There are a few different ways this could be achieved -
1. A decorator on the `ContextMenuAction`, `ContextMenuGesture`, `GestureProvider`, or `ActionCapability` that uses a policy to filter menu items or suppress context menu altogether based on policy. Because the decorator would have to have some contextual information (menu is suppressed only in the tree, and only in edit mode), the `ContextMenuAction` or `ContextMenuGesture` are easier to support because they have a reference to the element. Inspecting the element to establish context is not great though
2. Fundamentally change how the context menus are defined and declare context menu items in markup on the element itself. Representations could support current default behavior if no context menu content explicitly defined to avoid significant repetition in defining context menus for existing representations.
3. Define new TreeContextMenuGesture that extends `ContextMenuGesture` the `ContextMenuGesture`. Would still need to be decorated from the edit bundle though, to suppress in edit mode. Would not address #631.

Whichever approach is used should be considered in the context of #631 . Ideally both should be addressed at the same time.

@VWoeltjen thoughts?

**Comment by charlesh88** [comment]
#2 won't work because of the DOM structure: context menus need to be able to span and lay over containers that may have overflow: hidden - they need to be created and inserted at high level in the DOM to avoid this problem. This is currently an issue with the color picker menu that is temporarily being used in examples/plotOptions.

**Comment by akhenry** [comment]
@charlesh88 A good point. My description was actually a little misleading. What I was thinking was that you would not actually write the markup for the context menu, but rather define a list of action names, or a function that produces an array of action names perhaps as an Angular statement as an attribute in the markup. They would then be applied using the existing ContextMenuAction, which uses an absolute positioned child element of `body` to render the context menu.

**Comment by VWoeltjen** [comment]
I like Option 1 the most - this seems like a problem that could be solved with policy.

I _think_ we could do this with just a single `action` policy:

```
function EditContextualActionPolicy(navigationService) {
    this.navigationService = navigationService;
}

EditContextualActionPolicy.prototype.allow = function (action, context) { 
    var isEditing = this.navigationService.getNavigation().hasCapability('editor');

    if (isEditing && context.category === 'contextual') {
        return context.domainObject.hasCapability('editor');
    }

    return true;
}
```

In other words, "while editing, only allow context menus for objects that are being edited."

This removes "the tree" from the equation. That seems correct to me - it's not the treeness of being a tree that makes us want to prevent these actions, it's that the objects shown there are not part of the editing scope.

**Comment by akhenry** [comment]
> it's not the treeness of being a tree that makes us want to prevent these actions
I love this so much.

Ugh, you're right, the answer's obvious really. Was looking at it the wrong way. Thanks!

**Comment by akhenry** [comment]
@VWoeltjen Think I'll go with a slightly modified version of your suggestion in order to address #631 at the same time. Will write a policy that 
1. If domainObject is in edit mode, only allows whitelist of actions (for the limited context menus in edit mode)
2. If domainObject is not in edit mode, but the navigated object *is* in edit mode, rejects all actions. An empty array of actions has the effect of suppressing the context menu altogether.
Policy would be applied in the `ContextMenuController` at the point that actions are returned from the `ActionCapability`. Could potentially apply it within `ActionCapability.getActions(...)` for `category==='contextual'`. Would rather not build category specific logic into the ActionCapability itself though. Alternatively, could decorate the ActionCapability, but as the edit specific logic is already confined the policy, writing a decorator for this seems like overkill.

**Comment by VWoeltjen** [comment]
__For testing__: Want to check for regressions in context menus

**Comment by larkin** [comment]
A few bugs I have observed that may be related to this; I am not sure if they should be resolved or not, but easy to reproduce.

Objects in a layout don't have context menus while editing:
While viewing a layout:
![screen shot 2016-04-15 at 5 06 08 pm](https://cloud.githubusercontent.com/assets/226503/14577721/730b1c76-032c-11e6-9e74-9463967618d9.png)

When editing a layout:
![screen shot 2016-04-15 at 5 06 16 pm](https://cloud.githubusercontent.com/assets/226503/14577722/78081b5c-032c-11e6-856d-4996a4c11a97.png)

Plot Series objects don't have remove actions when editing:
When viewing a plot:
![screen shot 2016-04-15 at 5 07 53 pm](https://cloud.githubusercontent.com/assets/226503/14577739/c1da53d0-032c-11e6-9459-ac156fc1eb3e.png)

When editing a plot:
![screen shot 2016-04-15 at 5 08 10 pm](https://cloud.githubusercontent.com/assets/226503/14577740/c63eae80-032c-11e6-8412-5608e5bffa1b.png)

**Comment by akhenry** [comment]
> Objects in a layout don't have context menus while editing:

Not trying to shirk responsibility here, but whether by design or not, these seem to have been missing for a while. I reverted to an OEM commit from December - 08c430201135926c100d05a45a9d539432bd8396 - and the context menu arrow does not appear there in layouts in edit mode either. Were context menus ever available for this case?

**Comment by akhenry** [comment]
> Plot Series objects don't have remove actions when editing

Is there a new Plot branch I can test this out in? I enabled example/plotOptions and the remove action appears in edit mode in that branch, but it's pretty out of date now.

**Comment by larkin** [comment]
Re objects in layout not having context menus-- this could be intentional, I'm not really sure.

Re plot: figure that out later.

**Comment by charlesh88** [comment]
Testathon 041816
Isn't clear what work was done here and what should be tested at this point. Currently, I don't see any context menus in objects in a layout. That's better than allowing context gestures that disrupt the editing of the current object, but it would be good (for example) to include a "Remove" context menu item. I may owe some UX design related to this, and apologize for missing that input if that was the case.

**Comment by VWoeltjen** [comment]
This is a refactoring task, so no changes should be evident (testing here should be for regressions in related areas.) Think that we should have a `refactoring` label and some clearer guidance in testathon instructions on how to use that labeling (let's formalize this when we review issues afterward)

Based on [previous comments](https://github.com/nasa/openmct/issues/635#issuecomment-211045332), think we should open the "missing context menus in Layouts" as a new, separate issue; don't believe it is related to this refactoring as it is reproducible pre-NEM

**Comment by VWoeltjen** [comment]
Menu arrow in layouts is covered by #836 and Elements pane context menus are covered in comments to #794; do no believe regressions are related to this refactoring (and if so, issues are accounted for elsewhere), closing this as it has undergone testing (testathon 20160418)
