### ISSUE TITLE
[Tests] Difficult to navigate tree with Protractor

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#643]
Paraphrased from Luis @ JPL; he reports that it is difficult to select tree node elements and interact with them in protractor tests.  Selection must be done via by cssContainingText to find correctly named elements, and then it is difficult to find the disclosure arrow associated and then click it to open the composition.

Would be helpful if the tree node includes the object name as an attribute or other selectable element.  Any advice on how to better select and navigate the tree from protractor?

**Comment by larkin** [comment]
adding additional markup just to support tests doesn't seem like the right thing to do, but our markup is quite confusing.  For example:

![node location](https://cloud.githubusercontent.com/assets/226503/12632431/b80ffaac-c50c-11e5-8e74-ac1f7e4a5573.png)

**Comment by VWoeltjen** [comment]
Agree with not wanting to make changes solely to support tests. Conversely, poor testability usually correlates to other qualitative problems (e.g. tight coupling.)

Looking at this one, I think the issue here is the degree of specificity in the markup. If I were to give instructions to a user to do this, I'd say "click on the arrow next to My Items in the tree." If I were to try to explain this to Protractor, I'd say something like this untested code:

```js
var tree = element(by.css('.treeview ul.tree')), // "...in the tree"
  myItems = 
    tree.element(by.cssContainingText('.t-title-label', 'My Items')), // "...My Items..."
  myItemsToggle = myItems.element(by.xpath('ancestor::li[0]')) // "...the arrow next to..."
    .element(by.css('.ui-symbol'));
myItemsToggle.click(); // "click on..."
```

Aside from seeming backwards, this is all pretty reasonable/readable, except for when we try to get to the toggle itself. This looks nothing like "the arrow next to", because (a) Protractor/WebDriver doesn't seem to give us a very nice way of saying "next to", which we can't do much about, and (b) we didn't give ourselves a good way of saying "the arrow"; we just say `ui-symbol` and know/hope it's the right one. (And this test procedure would break if we added another `ui-symbol` in there...)

This is where I see "other qualitative problems" - we don't have enough specificity in our classes to know what's what. A task like "make all the toggle arrows in the tree red" should be easy, and it is; `.treeview li .ui-symbol { color: red; }` does this. But it also suffers from the same problems as the test: What if other `ui-symbol`s are added? Did we ever intend for those to be red? How is a reader of this code supposed to know the original intent?

On that rationale, I'd like to address this by adding some disambiguating classes (or attributes, as appropriate.) I think it's good to let us use test issues like this to identify them, provided we solve them in a general-purpose manner. (By comparison, we could have also solved this by saying `data-tree-toggle-for="My Items"`; this solves the test's problem but doesn't offer any generally-useful qualitative improvement.)

**Comment by larkin** [comment]
closing as wontfix as we got rid of protractor for the time being.  better tracked with #348
