### ISSUE TITLE
[Navigation] Go to location doesn't manipulate tree

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#658]
From @RCarvalhoNASA:

> I created a folder for the testathon, put a panel in there by means of issue 467, I then tried to use the inspector to get to that location in the tree on the left (my folder, as opposed to the packets part of the tree where I created this panel from).  However, clicking on the folder location in the inspector on the right changed the center view to the folder, but did not update the tree view on the left.  I would prefer the reverse: leave me seeing the thing I'm on in the main viewer, but show me where in the tree I am in the tree view on the left.  At a minimum, I would expect it to show me the tree location on the left, even if changing center view.

**Comment by charlesh88** [comment]
The root of what's going on here is that the treeview is not scrolling the object of interest into view. When an object is clicked in the Inspector Location part, it doesn't navigate to and highlight the clicked object. But, if that object is not in view due to the scroll position of the treeview, it leads to the second comment. 

It might be worth looking at the possibility of scrolling things into view in the tree as a first approach to this. I'd also suggest this is not a high priority problem right now.

**Comment by VWoeltjen** [comment]
Should we treat this as duplicate of #214 then?

**Comment by charlesh88** [comment]
Yes oh @VWoeltjen of the past, this is a dupe. Closing.
