### ISSUE TITLE
[Composition] Consider refactoring of composition policies to accept object instances

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#669]
Currently composition policies (eg. 'CompositionPolicy') operate on object `Type`s. It makes total sense why composition policies work the way that they currently do, but it would allow greater flexibility if composition policies could use object state. This could be achieved by one of
1. Creating a new policy category that operates on object instances rather than Types, and refactoring the current uses of composition policies to check both policy categories
2. Refactoring of existing policy categories to work with object instances (from which type can be retrieved) instead of object types. This may not always be appropriate or even possible depending on the context
3. Refactoring of existing policy categories to allow them to work with both Type or object instance, depending on the type passed in.

**Comment by VWoeltjen** [comment]
I think this is a good idea; had a similar thought today. For example, we can't currently use composition policy to prevent cycles, because that requires instance data. Would also be more consistent with other policies.

The only reason it is Type, Type currently is to allow this to be applied for Create actions. We did not have an `instantiation` capability, but now that we do it is straightforward to dry-run with an example instance for that purpose. (This was done in desktop MCT with some trepidation, since it sounds heavy and policy decisions should be fast, but after some initial debugging it worked quite well.)
