### ISSUE TITLE
Node 20 Support

### ISSUE THREAD

**Issue by adityadees** [nasa/openmct#6732]
#### Summary

Currently I'm using node v.20
but I think we only can use this till node 19
<img width="574" alt="image" src="https://github.com/nasa/openmct/assets/37553901/6d7fb41e-dc99-40f8-9e1e-0b8b2d548106">

**Comment by unlikelyzero** [comment]
@adityadees Thank you for filing this issue!

We currently are not testing with Node 20 and so we do not want to publish support for something we're not testing. A quick looks shows that the issue is related to https://github.com/achrinza/node-ipc/issues/45.

For now, we're going to block on node 20 until we update our testing matrix with node20 testing to prevent changes in the future.

**Comment by pharapeti** [comment]
Hi @unlikelyzero and @adityadees, looks like node-ipc [now supports Node v20](https://github.com/achrinza/node-ipc/pull/48)

**Comment by skrobchik** [comment]
Builds fine, and CI is passing #7254
