### ISSUE TITLE
[Timelines] Add action persists sub objects immediately

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#678]
1. Open or create a timeline
2. Using the add button, add an action to this timeline
3. New actions will be persisted immediately (can be verified in the network tab of developer tools)

**Comment by larkin** [comment]
Theres a more painful bug that occurs here: if you try to create a timeline while a telemetry point is selected, this persist operation will use the persistence space of the telemetry point and thus will fail.  Related to #656.

**Comment by VWoeltjen** [comment]
Noticed this issue was marked critical but unassigned. Don't suggest any action immediately, but @akhenry, can you check if this is still reproducible during the next testathon? We may want to reassess severity (esp. after fix for #656); if objects are persisted needlessly but there are no visible side effects to the user, that might be fine.

**Comment by akhenry** [comment]
@VWoeltjen Will verify in next testathon. In its original incarnation this issue was relatively benign (https://github.com/nasa/openmct/issues/678#issuecomment-183440564 and #656 aside). In the case where user discards changes, it results in orphan objects in the persistence store.

Will verify where #656 resolves https://github.com/nasa/openmct/issues/678#issuecomment-183440564

**Comment by charlesh88** [comment]
Testathon 032416
Verified fixed.
