### ISSUE TITLE
Major performance degradation when adding annotations to a plot

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#6822]
#### Summary

When adding a large annotation to a plot (from top left to bottom right) performance takes a nosedive. CPU becomes pegged at 100%. This can be seen especially when adding annotations to an Overlay Plot with more than one telemetry source.

#### Expected vs Current Behavior

Overlay Plots should remain performant enough to be useable even if there are annotations and multiple plots.

#### Steps to Reproduce

1. Create an Overlay Plot
2. Drag at least two SWGs into it
3. Navigate to the Overlay Plot
4. Shift + Option + Click and drag to create an annotation
5. Add tags to the annotation, at this point you should notice the slowdown
6. As you continue viewing the plot, performance gets worse

#### Environment

* Open MCT Version:  `3.0.0-SNAPSHOT`
* Deployment Type:  local
* OS: MacOS
* Browser: Chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [x] Does this block the execution of e2e tests?
- [x] Does this have an impact on Performance?

**Comment by scottbell** [comment]
It looks like annotations are being displayed in Real-time mode (instead of just fixed):

https://github.com/nasa/openmct/assets/9853862/2b14f2e3-834d-4c28-8e60-7c6edacf170d

**Comment by scottbell** [comment]
The annotations being displayed in real-time seems to be fixed. When the plot is frozen however, incoming data is still rendered and displayed, which is causing performance issues.

That said, I think there's a more general issue with plots in Vue3. Here's a clean plot (no annotations) before the Vue2 upgrade:

https://github.com/nasa/openmct/assets/9853862/9fb350ed-350e-4dfa-94bb-d8dea37660b4

Note the smoothness in selecting points as the mouse moves, and the rectangle selection.

Here's post Vue3, the same plot:

https://github.com/nasa/openmct/assets/9853862/7d760551-4e41-4968-a3fc-a9d2d9528ae2

Note the display struggles to keep up with the point selection as the mouse moves, and the choppiness in the rectangle selector.

I'll keep investigating.

**Comment by scottbell** [comment]
Draws happen much faster and at a higher rate pre-vue3:

https://github.com/nasa/openmct/assets/9853862/d9dadcef-c7bf-475b-838d-2f20c2178c71

versus post-vue3:

https://github.com/nasa/openmct/assets/9853862/b47e9abf-cce9-4c12-bf2c-82cadd73e77c

**Comment by scottbell** [comment]
Draws are taking ~2x the time, though I think we're bottlenecked before this. Here's pre vue3:


https://github.com/nasa/openmct/assets/9853862/07f07786-ab4c-4e32-8cf9-7b4e4e3c8a5c

and post:

https://github.com/nasa/openmct/assets/9853862/29c1de0e-0c44-46d3-8088-2dbd2872f39f

**Comment by scottbell** [comment]
might be `NODE_DEV=production` not being on test environments?

**Comment by akhenry** [comment]
Downgrading to critical, does not block regular plots usage.

**Comment by scottbell** [comment]
After talking to @akhenry, @shefalijoshi, and @ozyx we've got two issues:

- Plot configurations, highlights, and annotations have series models in them, and are reactive all the way down. We should instead being passing around series IDs instead of the full series model, and then have the individual components look up the series models internally. The trick here is they’ll need to then follow updates to add/removals of both series, and in the case of stacked plots, adding/removal of telemetry from the composition. I think this logic would be common to Legend components, MctPlot, and MctChart, and could exist in a separate helper class. The helper class could also return a series given an ID, which is what all these components want in the first place. 
- The annotations are being loaded when plots are opened, regardless of whether the plots are in fixed time mode or paused. Instead, when plots are loaded, if the plots are in real-time, we should defer loading annotations. When the time mode changes (be it flipping to fixed time mode or pausing the plot), we should then load annotations. This lazy loading will help operators who typically just load plots in real time.

Per @akhenry, I'm going to work on the latter (lazy loading annotations) first.

**Comment by scottbell** [comment]
@charlesh88 @shefalijoshi @akhenry I've got a draft PR to address some of the performance issues attached to this ticket. The PR:

- Only loads annotations if plot was loaded in fixed time, or if the time mode has changed to fixed time, or if the plot is frozen.
- Removes annotation point range checking and assumes FlatBush has done this already for us.

I'm still noticing slow performance though when the plot is frozen. This is because we're dragging around the series models in the annotation selections and points. In Vue3, these series models are reactive, which causes the annotations points to redraw as new data is coming in the series models. When the plot is frozen near the current time boundary, new data stills streams into this series models and causes the plot to redraw. There are couple of solutions here I think:

- Don't drag the series models around. This is probably the "right way" IMHO. To do this, we'll need to make sure the various plot components have access to the series models by listening to changes. See the [first item](https://github.com/nasa/openmct/issues/6822#issuecomment-1659137960) above.
- Don't freeze the plot, but change the conductor to fixed mode for editing. This is more impactful to the user (no editing in frozen mode anymore), but easier to code.

**Comment by scottbell** [comment]
Talking with @akhenry & @ozyx, we’re going to love forward with draft PR, but create a separate performance e2e test that selects a large part of the plot as a tag.

For the first part of [this](https://github.com/nasa/openmct/issues/6822#issuecomment-1659137960) , we’re going to create a separate ticket.
