### ISSUE TITLE
[Time Conductor] Use a different event mechanism for notifying changes in domain bounds

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#685]
Currently the time conductor uses scope.$broadcast to notify listeners of updates to time bounds. Ideally it should not be necessary to use scope for listening for updates to the time conductor's bounds. To avoid creating a direct dependency on the time conductor itself, listeners should either register with an application-wide event bus, or perhaps the telemetry infrastructure could be used for this purpose (maybe using the existing subscription approach, and triggering the update callback when request bounds change?).

**Comment by larkin** [comment]
I think we have to look at a tighter coupling here-- views controllers should be able to request info from time conductor and use it in their requests and configuration, and have defaults for when time conductor is not present.  They should also be able to receive notifications from the time conductor and requery when that occurs.

Currently in the plot overhaul I am directly coupled to the time conductor which allows me to read the selected domain, which is needed for display purposes.  But doesn't support fallback.  I imagine we'll have to figure out a method of establishing an optional dependency.  I think I'd floated the idea of a universal message bus (with two modalities: event listener, and request/response) in a previous thread, would be open for that option.

**Comment by VWoeltjen** [comment]
Agree with not wanting to use scope to communicate here.

An event system independent of scope is reasonable. Actually, we have this in `topic`, and could just use that. I'd prefer to move to a solution that isn't based on string-matching; this works OK for EventEmitters because it is practical to define a set of events for a specific object type, but an application-global event bus where event names may be arbitrary (among senders and receivers) becomes impractical to document, and therefore difficult to use.

We could refactor `topic` to instead be reusable to create topic _instances_ as services. Then, plots etc. could depend on the `timeBoundsTopic` (instance of `Topic.<TimeBoundsEvent>`), to which a reference is acquired in the same manner one would normally acquire service references, per #462. Although what I think we want here is actually an `Observable.<TimeBounds>` (something that supports event-driven usage but also has a plain old `get` method).

This `timeBoundsService` (or whatever it's called) would be implemented independently of the time conductor, and could include reasonable defaults (or undefined values which imply "use your own defaults.") The time conductor plugin could then use/replace/decorate this service to extend the behavior. The value of this approach is that plots etc. get the interface they need to work cleanly with the time conductor, without needing to be tightly coupled to the time conductor specifically.

**Comment by VWoeltjen** [comment]
> I imagine we'll have to figure out a method of establishing an optional dependency. I think I'd floated the idea of a universal message bus (with two modalities: event listener, and request/response) in a previous thread, would be open for that option.

Agree that we need a method for this. Would like to avoid "optional dependencies" in the sense of `if (someService) useSomeService()`, as this pattern introduces complexity (one optional dependency makes a unit twice as hard to test.)

I like the idea of a universal message bus (with various scopes; would be great to support inter-client communication across this, but that's an aside) but would prefer that this be "plumbing", not "porcelain"; `eventBus.listen('for-the-magic-word', andDoSomething)` is not something I'd like to see in plot code, for instance (it has the effect of creating "implicit extension points" that nobody is responsible for defining, which is a lot like the approach taken for extension categories, which I now consider an anti-pattern.)

**Comment by larkin** [comment]
fixed.
