### ISSUE TITLE
Remove normalize.css; update Licenses page

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#700]
With the switchover to using bourbon to compile SASS, we are no longer using Compass's reset library. Pete has added Eric Meyer's reset.css to master, and with that addition normalize.min.css should be removed as redundant.

We should also cleanup the Licenses page to reflect this change, and also remove modernizr.css while we're in there, as we don't use that either.

@VWoeltjen @larkin Do you guys see any issues with this approach?

**Comment by larkin** [comment]
:+1:

**Comment by VWoeltjen** [comment]
Sounds like the right thing to me

**Comment by charlesh88** [comment]
PR filed, closing.

**Comment by charlesh88** [comment]
@larkin So I've been reading up a bit more on this, and have to say that normalize looks like a better option than reset - reset does more of a clean sweep, but adds a lot inheritance crap when inspecting that I would love to do away with. We've been using normalize (although it was probably being pwned by Compass's reset stuff) so theoretically it will be less of a change.

I think we should keep using normalize, instead of replacing with reset. Thoughts?

**Comment by larkin** [comment]
@charlesh88 I'm down for using normalize instead of reset.  From my testing there are some elements that will require small style tweaks when you remove reset (the inspector being one), but it's not significant.  I'm used to using reset because I want a blank slate, where as normalize gives you a standardized slate and helps with a lot of cross browser differences.  Reading up, normalize seems to help with a number of other issues that I hadn't considered (http://stackoverflow.com/questions/6887336/what-is-the-difference-between-normalize-css-and-reset-css).
