### ISSUE TITLE
[Code Coverage] Codecov.io reports appear to be mostly broken

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#7015]
#### Summary
I noticed that we had a codecov.io report for release/3.0.0 which had the following calculations:
- 48% total
- 57% for the `e2e-stable` flag
- 44% for `e2e-full` flag
- 37% for `unit` flag

How is it possible that our total is 48% but the e2e-stable tests cover 57%?

I switched back to 'master' and noticed something our lowest coverage was for 'plot/plugins/mctPlot.vue'. We which shouldn't near-zero (0.27%) as this area is heavily exercised in our e2e suites.

Opening the `plot/plugins/MctPlot.vue` revealed that the two lines which were covered appeared to be randomly distributed
<img width="1560" alt="Screenshot 2023-08-29 at 12 19 06 PM" src="https://github.com/nasa/openmct/assets/12446869/3a544dec-15b4-4517-8cae-5f5de9a5414f">

We'll likely need to do a deeper investigation into why the code coverage is mostly inaccurate.

Probable causes:
- Sourcemaps mismatch between test suites and code coverage tooling (karma istanbul)
- Issues in `npm run start:coverage`
- Could be the same root cause as https://github.com/nasa/openmct/issues/5811

**Comment by unlikelyzero** [comment]
@evenstensberg please see this documention update and provide feedback https://github.com/nasa/openmct/pull/7027/files

**Comment by msf-caesar** [comment]
Try with:
1. Double-checking the sourcemaps configuration for test suites and code coverage tooling (karma istanbul).
2. Verifying that the `npm run start:coverage` script is correctly set up.
3. Investigating if the issue is related to the known root cause mentioned in the GitHub issue.
4. Running additional tests and analyzing test results to identify any areas that are not being properly covered.
5. Considering updating the code coverage tooling or configuration if necessary.

**Comment by evenstensberg** [comment]
@unlikelyzero okay, I'll have a look at the build.
