### ISSUE TITLE
[Tables] Consolidate various table implementations

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#713]
There are a number of 'table' type components in the codebase. With the new 'Table' type, we should consider whether any of these can be replaced with the Table type, and plan any work necessary to do so.

eg.
platform/features/events/src/directives/MCTDataTable.js
platform/features/rtevents/src/directives/MCTRTDataTable.js
platform/features/scrolling/...
platform/features/rtscrolling/...

**Comment by larkin** [comment]
IMO, replace them all with the new tables.  When we implemented events and scrolling we knew we wanted to refactor (tons of code duplication there), but didn't have the time.  Now's the time.

**Comment by VWoeltjen** [comment]
> IMO, replace them all with the new tables. 

:+1:

The only difference between Events and Scrolling is that new events appear at the bottom, not the top (and the screen auto-scrolls to show.) Since new Table supports sort-order, this is _mostly_ covered (we will need some solution which automatically scrolls to show real-time before we can really claim parity; this may sound like a nit, but for a real-time monitoring large-display use case this behavior is essential.)

Likewise, RT versus non-RT variants was never what we really wanted, it was just an expediency. After #707 the RT variants will be obsolete.

**Comment by akhenry** [comment]
Implemented as real-time and historical tables. Existing events and scrolling displays removed in #733
