### ISSUE TITLE
Remove mispellings from our cspell dictionary

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#7440]
#### Summary
[Our cspell dictionary](https://github.com/nasa/openmct/blob/master/.cspell.json) includes a lot of misspellings, presumably to get _something_ implemented that at least prevents further misspellings. We should go back and fix all of the misspellings captured in the cspell dictionary throughout our codebase.

**Comment by Chay2203** [comment]
Hey @akhenry, I can solve this issue, can you please assign me to this :)

**Comment by evenstensberg** [comment]
@ozyx Can I fix this? (If open)

**Comment by akhenry** [comment]
@ozyx  This needs test instructions as it touches runtime code.

**Comment by ozyx** [comment]
Since the code touches both `Dialog` and `Overlay`, and also some code within the UserAPI, we will want to test both.

# Testing Instructions

## Dialog / Overlay

### Dismissible dialog/overlay

1. Create a domain object that can only have a composition size of 1, such as a Bar Graph or Scatter Plot
2. Drag telemetry into it, such as SWG 1
3. Drag telemetry into it, such as SWG 2-- confirm that the "replace" dialog appears and is able to be dismissed

1. Create a telemetry table
2. Drag the SWG1 into it
3. Right click on a table row and select "View Full Datum" to trigger a dismissible overlay
4. Confirm it appears and may be dismissed

### Non-dismissible dialog/overlay

1. Create a Notebook
2. Create a notebook snapshot
3. Select the snapshot and "annotate" it
4. Confirm that the annotation workflow functions properly and dialogs/overlays may be accepted or dismissed

## User API

- Install the Open MCT Example User plugin:

```js
// index.html
openmct.install(openmct.plugins.example.ExampleUser());
```

- Ensure that switching between User roles works properly

**Comment by davetsay** [comment]
verified

NOTE: this is a breaking change to api and this should be referenced in release notes.

**Comment by charlesh88** [comment]
Testathon 2024-10-17: verified fixed.
