### ISSUE TITLE
[Tree] Does not show newly created objects

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#745]
1. Click "create"
2. select folder
3. save in a location.
4. you'll navigate to the new folder, but you can't see it in the tree.  the tree won't update until the page refreshes.

From Testathon on 2016-03-15

**Comment by VWoeltjen** [comment]
:embarrassed:

I swore I'd seen this working, but I think I'd been Creating in unexpanded folders.

Think this is same root cause as https://developer.nasa.gov/mct/warp/issues/145 (oh hey, you already said that)

**Comment by RCarvalhoNASA** [comment]
20160317 testathon this seems to be resolved

**Comment by akhenry** [comment]
20160317 +1

**Comment by charlesh88** [comment]
Testathon 031716
Verified fixed

**Comment by larkin** [comment]
Reopened while logged in as charlesh88 on accident.

Tree does not *always* show newly created objects.  I think this is the same issue as #795, but when I was reproducing #795 it was inconsistent and I blamed search.

**Comment by larkin** [comment]
Would classify like this: after the contents of a container (any container object in the tree) are modified once, all future create actions will not update the container in the tree.  

You can switch to a different container and it will work in the same fashion.

However, removal actions still remove items from the container, but they don't do a full refresh-- so if you add three items to a container (the second and third items should not display), and then remove the first item you added to the container, the first item will disappear from the list but the second and third item will still be missing.  After refreshing the page the second and third item will still be visible.

**Comment by VWoeltjen** [comment]
Investigating; callback which should trigger a refresh do get invoked for the object, but when composition is loaded, it still contains only the original objects (from the first modification.) This is consistent with the state of the model of the domain object at that time (so, that model is incorrect.)

As of 8f6a287 (merge of #756 to originally fix this) this issue is irreproducible, so something has regressed since then. Will `git bisect` for further insight

**Comment by VWoeltjen** [comment]
Issue is not specific to tree; also see this in the Items view when navigating back to Folder

**Comment by VWoeltjen** [comment]
`git bisect` says:

> There are only 'skip'ped commits left to test.
> The first bad commit could be any of:
> 8fa030437e38d81b9f4fb3397f39d00cabb1114e
> 17faf000b0786590bb0f92742e18715dc456a0dd
> 3fe41575bd03c94e3600cb1fef6d88f5794c8809
> 9c9db3c24f816af126e8d8bdcfd88fe278384d0d
> We cannot bisect more!

So, regression introduced by #773

**Comment by VWoeltjen** [comment]
Specifically, [removing from the cache on persistence](https://github.com/nasa/openmct/pull/773/files#diff-f6d9cdddbe14e455171941b3e3466e8aR152) causes this - it permits multiple instances of the same model to exist in the application. There are probably a lot of other subtle regressions lurking around this.

Intent there was to maintain similarity with earlier implementation (for newly-created objects, get models from persistence instead of using the version created in memory.) This is poorly-reasoned (also clears the cache on _every_ persist) and unnecessary; there are not cases where an object will look different on read from persistence than it did before it was saved.

**Comment by VWoeltjen** [comment]
Not entirely unnecessarily - without this check, subsequent Edits to a created Timeline trigger a Save dialog (effectively forcing you to Save As) for reasons which are unclear.

**Comment by larkin** [comment]
Verified resolved by #810 in second testathon of 2016-04-01.
