### ISSUE TITLE
Condition sets don't show most recent status for Operator/Mission Status on nav

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#7484]
#### Summary

When navigating to a Condition set based on Mission Status / Operator Status values (both enum values, unconfirmed if this extends to all enum telemetry), the Condition Set will not get the most recent value. However, if one reloads the page while viewing the condition set, or the state is changed while viewing the condition set, it will evaluate properly.

#### Expected vs Current Behavior

Condition sets should get the most recent value on nav to the object

#### Steps to Reproduce

1. Create a Condition Set with conditions based on Operator Status or Mission Status values
2. While viewing the condition set, set a value in Operator/Mission status
3. Notice the value is received by the condition set and it evaluates
4. Nav away to another object and back again
5. Notice the condition set value is '---' and nothing is evaluated
6. Refresh the page
7. Notice the condition set gets the most recent value and it evaluates properly

#### Environment

* Open MCT Version:  0aceb4b590be32d0abfc172b972b82b8c2bbcbfd
* Deployment Type:  testathon
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information

https://github.com/nasa/openmct/assets/9259993/a6ca545d-a6fa-43a3-b9ee-3c13e5782291

**Comment by scottbell** [comment]
I don't think it's just condition sets. Telemetry Tables and the the indicator itself are also having trouble with them:

https://github.com/nasa/openmct/assets/9853862/870e9623-bf50-46d0-9894-67bdb04e93fa

**Comment by scottbell** [comment]
Ah! I think this is because these datasets are using the time conductor - including the indicator itself!

**Comment by scottbell** [comment]
It looks like this is very sensitive to the time bounds. Extending the future time bounds seemed to help this issue for me.

**Comment by scottbell** [comment]
Note, started to look into this, and it appears to still be happening.

**Comment by scottbell** [comment]
The issue (as I see it), is that:
1. The [ConditionManager is depending on a telemetry subscription](https://github.com/nasa/openmct/blob/faed27c143cf14ca41d00627a7b0419de33b32a3/src/plugins/condition/ConditionManager.js#L74) firing with data to update the condition its condition is in 🎸.
2. This subscription normally would fire with new data for a new subscription, but the telemetry subscriber [is cached](https://github.com/nasa/openmct/blob/faed27c143cf14ca41d00627a7b0419de33b32a3/src/api/telemetry/TelemetryAPI.js#L449).
3. Why is it cached? Because the Operator Poll status is [holding onto a subscription too](https://github.com/akhenry/openmct-yamcs/blob/master/src/providers/user/user-provider.js#L160) (naturally)
4. Thus when navigating away, we [never delete the subscriber](https://github.com/nasa/openmct/blob/faed27c143cf14ca41d00627a7b0419de33b32a3/src/api/telemetry/TelemetryAPI.js#L518).
5. And therefore the ConditionManager's [telemetryReceived](https://github.com/nasa/openmct/blob/faed27c143cf14ca41d00627a7b0419de33b32a3/src/plugins/condition/ConditionManager.js#L406) function never fires.

To fix, we could:
1. Change the ConditionManager to request the telemetry on load (and not depend on the subscription immediately sending latest).
2. Change the TelemetryAPI to send latest to subscribers, even if subscription is cached.

Thoughts @ozyx & @akhenry?

**Comment by scottbell** [comment]
After talking with @akhenry - check why `request` isn't firing.

**Comment by scottbell** [comment]
To test:

- Create a Condition Set with conditions based on Operator Status or Mission Status values
- While viewing the condition set, set a value in Operator/Mission status
- Notice the value is received by the condition set and it evaluates
- Nav away to another object and back again
- Verify the condition set receives the latest value
- Refresh the page
- Verify the condition set gets the most recent value and it evaluates properly

**Comment by ozyx** [comment]
Verified fixed -- Testathon 3/28/24

**Comment by charlesh88** [comment]
Testathon 03-28-24 verified fixed.
