### ISSUE TITLE
Orphaned container accessible to the user

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#765]
Testathon 031716
Cancelling out of a write conflict can result in a user-accessible orphaned container. Scenario: two different users on two different computers:

1. User A and B. User A creates a folder in My Items, then User B creates a folder as well. Apparently this can also occur when an object is being moved or duplicated.
1. User B will see a conflict dialog. If User B selects "Discard" from the dialog, the main view area will navigate to User B's new folder. 
1. User B can drag items into the new folder, but upon navigating elsewhere the new folder will no longer be available to browsing.

What should happen is that at the end of step 2 above, the system should not navigate to the discarded new container, but instead stay where the user was when the Create action was initiated. 

While a user can lose work, this only currently happens in a multiple machine scenario. Additionally, I couldn't come up with a scenario where the user is able to lose data, so have not flagged as a blocker. Also, VISTA is not affected by this particular problem due to a difference in the persistence model.

**Comment by VWoeltjen** [comment]
There are a few different ways to address this. #408 might make this a little bit easier to handle responsively (e.g. "we failed to persist, so navigate to the parent instead of the created object")

However, I think it is true in the general sense that an orphan object should not be navigable, except in the specific case of Edit mode objects. I will explore this avenue.

**Comment by VWoeltjen** [comment]
Verified testathon 6-16-2016

**Comment by akhenry** [comment]
Verified testathon 6-16-2016
