### ISSUE TITLE
Timeline lags when identifying drop target

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#767]
Testathon 031716
When editing a Timeline and dragging elements, there is 2 and more second delay while drag-hovering before a valid drop target hilites to indicate a valid drop. 

CH should check to first make sure this isn't due to a CSS transition effect, then reassign if not.

**Comment by charlesh88** [comment]
Mechanism here is that class .drop-into is being assigned via an ng-class eval of ngModel.highlight(). There are no transition effects associated with Timeline swimlanes. Thinking at this point that a delay is due to processing within the "highlight()" function; "highlightBottom()" should also be taken a look at as well. 
Reassigning to Victor to have a look.

**Comment by VWoeltjen** [comment]
Think this is due to a missing `$apply` to notify Angular of the change; state doesn't get reflected until next digest cycle (triggered by the clock in the lower-right, for instance)

**Comment by VWoeltjen** [comment]
Noticing this in the context of work on #775 for #679 - this can actually be aggravating, because it can create the appearance that your drop target is something different than what it is. 

In particular, I often find myself positioning over the line between two activities, and dropping, only to realize I've actually dropped it _into_ the activity below the line. At first I thought I was seeing some weird bug (which is still a possibility) but I think the problem is that I'm actually moving a few pixels down, but because of the delay in the highlight I do not realize it.

May try to fix this in the context of that issue to aid debugging.

**Comment by charlesh88** [comment]
Testathon 032416
Verified fixed.
