### ISSUE TITLE
[e2e] Tests are failing on newly rendered time conductor tests

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#7775]
#### Summary
After the merge of the playwright `1.45.0` (https://github.com/nasa/openmct/pull/7762) the snapshot tests for time conductor detected a change:

https://output.circle-artifacts.com/output/job/01e8e081-4a84-4fc8-8ea3-882205fd2578/artifacts/0/html-test-results/index.html#?testId=a17fc55e77bcee4030fa-ca86ed74088bc58cd1be

Unfortunately, all merges to master are failing until this is addressed

**Comment by ozyx** [comment]
After investigation, this issue is due to layout shift during initial load. This is caused by the loading of our openmct icons, which are **not** being preloaded or dynamically included (using webpack).

Short-term solution is to skip the failing test.
Long-term solution is that we need a way to preload icons so that they don't shift the layout after the initial DOM content loads.
