### ISSUE TITLE
[Timelines] Activities cannot be moved, reordered in a new, non-persisted timeline

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#790]
To recreate
1. Create a new timeline, but do not save
2. Add a new activity
3. Add a second activity
4. Try to reorder activities, or drag second activity under first activity. Gestures do not seem to work. Possibly related to changes introduced by #678, or one of #767, #775, #679

**Comment by charlesh88** [comment]
Could be related to #789.

**Comment by VWoeltjen** [comment]
Testathon 20160331: Now able to drag-and-drop to reorder, but drag-over highlights are not appearing. (They do appear when editing a Timeline that had been previously saved.)

**Comment by VWoeltjen** [comment]
Missing drag-over highlights have same root cause as #717.

Specifically, due to the uninitialized model, an exception is hit when trying to read the start time. This occurs during Angular's digest cycle, causing later expressions in the cycle not to be evaluated, meaning the changed highlight state never gets reflected in the DOM.

**Comment by VWoeltjen** [comment]
Verified testathon 20160401
