### ISSUE TITLE
Tutorial & Guide links not working on contribution email

### ISSUE THREAD

**Issue by ev1stensberg** [nasa/openmct#917]
##### Bug: The attached email links with the CLA form isn't working and results in a 404.

**Comment by ev1stensberg** [comment]
I'm assuming this was sent from an template, so just wanted to notify :smile:

**Comment by akhenry** [comment]
Ah, apologies, it referenced the project's old name "openmctweb".

It wasn't a template, but it the URLs were copied from an older email.

The correct address for the guide is http://nasa.github.io/openmct/docs/guide . The tutorials need updating, but you can reach the (now outdated) tutorials at http://nasa.github.io/openmct/docs/tutorials . The biggest problem with them currently is that they use the old declarative bundle style rather than the newer imperative form. In the old style, each bundle was configured in a bundle.json file. The application was then tied together with a bundles.json file. Instead, each bundle now declares a bundle.js file (with v. similar syntax), with bundles included via require in main.js.
