### ISSUE TITLE
[safari] [time conductor] pressing enter in date field doesn't update bounds

### ISSUE THREAD

**Issue by larkin** [nasa/openmct#925]
I am able to reproduce this in safari 9.3
1. go to live demo mars weather 
2. change start date from "2012" to "2013" and press enter.
3. the time bounds visible below the date entry field should change.

actual outcome: the time bounds don't change.

**Comment by charlesh88** [comment]
Observed during 5/12/16 JASON-3 team user session.

**Comment by akhenry** [comment]
Test notes. There were actually two separate issues here. The original issue was due to Safari basically ignoring any form inputs that are style with `display: none`. Enter relied on a submit control with `display: none`, so while it worked in Chrome, it didn't work in Safari.

Secondly, enter was not supported at all, in any browser, for realtime mode due to an oversight on my part when I re-implemented the time conductor.

**Comment by larkin** [comment]
2018-07-02: Verified Fixed
