### ISSUE TITLE
[Drag and drop] Dragging from Search results doesn't display proxy

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#926]
Started this while testathoning #671. Normally a draggable object, while it's being dragged, displays some sort of translucent proxy. This varies per browser. Observed while dragging objects from browse tree and Search results:

Who | Platform | Browser Version | Browse Tree | Search Results
---- | ---- | ---- | ----
CH | Mac | Chrome 50.0.2661.102 (64-bit) | Translucent rect | **Nothing**
CH | Mac | Firefox 46.0.1 | Translucent icon + label | Translucent icon + label
CH | Mac | Safari 9.0.2 (11601.3.9) | Translucent icon + label | Translucent icon + label
VW | Mac | Chrome 49.0.2623.112 (Official Build) (64-bit) | Translucent icon + label | Translucent icon + label

The issue here is the difference in dragging from Search results and the browse tree. CH can replicate this problem on both home and work machines, both running the same version of Chrome. 

CH to first look into this to ensure it's not CSS-related.

**Comment by charlesh88** [comment]
Examining CSS, there is one selector in _timelines.scss: `.s-status-editing .l-title .rep-object-label[draggable="true"]`. However, this doesn't target tree and search results, and even commenting out the code doesn't alter the behavior.

Not sure where to take this at this point except to keep an eye out to see if this can be replicated in other platforms and systems. Flagging as unverified so we can test this out in the next Testathon.

**Comment by charlesh88** [comment]
ℹ️  Testing: Would like to see if this problem manifests in other systems. To test:

1. Try dragging anything from the browse tree. Do you see a translucent version of the item (icon and text), or a translucent rectangle? Or something else?
2. Search for something, and drag an item from the results list. What do you see? Same as what you saw during number 1, or different? Or nothing?

**Comment by larkin** [comment]
I think what you are seeing is the default browser behavior. We should implement our own behavior for dragging that meets our goals. Generally you would toss a new Dom elements in the page and have it follow the mouse cursor until it is dropped somewhere else.

**Comment by VWoeltjen** [comment]
I'd prefer to use HTML5 drag-drop rather than reimplementing something equivalent. 

The standards describe a "[drag data store bitmap](https://html.spec.whatwg.org/multipage/interaction.html#drag-data-store-bitmap)" which is positioned relative to the mouse during drag, and there's a DataTransfer.setDragImage call we can make to specify it (which, despite its name, should work with any HTML element.) We don't make this call because browsers (Chrome and Firefox, at least) use the element which initiated the drag as the default.

As far as I can tell, this is still happening in Chrome&ast;, but the image is getting rendered as a gray or blue (depending on selection state of the dragged object) rectangle from the tree, and as nothing from search results. I believe a CSS solution/workaround exists; I was able to get this "working" in Chrome 50 - able to see the element on drag instead of a weird box - by removing all classes in the tree and adding a few ad hoc styles.

&ast; _Specifically, if I `event.dataTransfer.setDragImage(document.querySelectorAll('.create-btn')[0], 0, 0)` during the `dragstart` event (from DragGesture), I see the Create button following my mouse as expected. If I make the same call with `element[0]` (element that initiated the drag) I get the same gray-or-blue box that I see if I don't make the call at all._

**Comment by larkin** [comment]
The html5 drag and drop spec is not awesome here-- drag image can behave very oddly depending on how we structure our html and how we apply css rules.  As our html and css change all the time, I think it would eventually break.  If we want a consistent drag image we should make a view for it separate from the tree node element.  To utilize that view, on dragstart we would have to insert a DOM element, make it visible, use it to set the drag image, and then remove it.  

At that point, you're half way to having a DOM node follow the cursor.  If you continue with the DOM node following the cursor, you can update it to reflect whether or not the object can be dropped in a specific location or do other changes as you'd like.

**Comment by charlesh88** [comment]
Still seeing this, and this is still a problem in trying to drag from Search results, where there is no proxy displayed. Why do we see different things between the tree and the results list?

**Comment by charlesh88** [comment]
Verified fixed Testathon 07-08-22.

**Comment by ozyx** [comment]
Verified Testathon 7/8/22

Draggable objects have a transparent proxy on drag. Tested with dragging from the tree and dragging from search results

**Comment by ozyx** [comment]
Verified Testathon 3/20/24

Draggable objects have a transparent proxy on drag. Tested with dragging from the tree and dragging from search results
