### ISSUE TITLE
[Edit] First Cancel fails for new nested objects

### ISSUE THREAD

**Issue by VWoeltjen** [nasa/openmct#979]
Steps to reproduce:

1. Create a Timeline.
  * Remain in Edit mode when the new timeline appears
2. Add an Activity to the Timeline
3. Click the "X" button (Cancel) to the top-right of the timeline
4. __Observe:__ Nothing happens.
5. Click the "X" button again
6. Observe: Now changes have been discarded as expected

Expected behavior would be for changes to discard after Step 3 (should only need to press X once)

After Step 3, the following appears on console:

```
angular.min.js:110 TypeError: Cannot read property 'modified' of undefined
    at e (PersistenceCapability.js:154)
    at angular.min.js:121
    at p.$eval (angular.min.js:136)
    at p.$digest (angular.min.js:133)
    at p.$apply (angular.min.js:136)
    at o (angular.min.js:90)
    at y (angular.min.js:94)
    at XMLHttpRequest.S.onload (angular.min.js:95)
```

Appears that the general cause is the attempt to `refresh` an object that has never been persisted (a case which is not handled/anticipated by the `refresh` method)

Observed during testathon 2016/05/31

**Comment by VWoeltjen** [comment]
Verified testathon 20160602

**Comment by charlesh88** [comment]
Testathon 2016-06-16
Verified fixed.

But now seeing a regression problem: the Add menu while editing a Timeline is being clipped because `<mct-toolbar name="mctToolbar" structure="toolbar.structure" ng-model="toolbar.state" class="flex-elem grows ng-pristine ng-untouched ng-valid ng-isolate-scope">` is set to overflow: hidden. 

Filed #1019 for this.
