### ISSUE TITLE
Assess and update markup and CSS style guide

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#988]
Per Release 3 Road Map: an updated style guide and markup and CSS refactoring as needed are both on deck for Kress. The goal is to have a style guide with good coverage of the general UI approach, as well as a guide to how to create and style various archetypal elements (buttons, tabular displays, form elements, etc.) with open source devs in mind as the audience.

I think the right approach is this:
1. Brush off the cobwebs and crack open the existing style guide and assess staleness (Charles).
2. Assess current state of markup and CSS for elements contained therein as well as missing elements (Charles). 
3. Where markup and CSS are overlay complex, flag as candidates for refactoring (Charles).
4. Do any of you guys have elements in mind that seem cumbersome that a open source dev would want to be juggling? If so, let's capture those as refactoring/documentation candidates (You guys).
5. Review list of candidates and prioritize (Us).

Realistically, I think from a scope perspective that Kress will let us do the assessment and the initial updates to the style guide, with refactoring happening in a later sprint.

**Comment by VWoeltjen** [comment]
Misc. thoughts:

* Having revisited tutorials a bit in the context of API refactor, one of the things that would be most useful for plugin devs here is an easy shorthand for common UI elements "in the Open MCT style" - buttons, dropdowns, etc. This is most useful if we support this as standard HTML form elements with classes (as opposed to Angular directives or some JS API)
  * Even better is if no classes are required, at least for the most common things. It would be nice to write generic HTML and have it appear appropriately-styled for Open MCT.
  * For "other stuff" - non-common elements that we can't prepare for ahead of time - the style guide is useful. But the shorter it is, the more likely it is to be read by third-party devs. 
  * I'm thinking of toolbars and dialogs specifically, here; we have a declarative syntax for these but it is both more convenient and more flexible for third-party devs to be able to build these from plain HTML if they so desire. We could make it easy to provide a consistent look for these if we replaced some of the class-based form markup we have with more semantic alternatives (for instance, in selector-speak, our `div.form-section` could be a `form section`, and our `div.section-title` could be a `form section h1`.)
* Somewhat off-topic, but we've talked in the past about handling icons as CSS classes instead of as glyphs inserted by JavaScript. If we formalized this approach and had conventions developers could follow, that would be useful to document in this context. But probably out-of-scope.

**Comment by larkin** [comment]
Have a previous issue for updating the style guide: https://github.com/nasa/openmct/issues/196, with some comments about how to document style guide.

As far as content of style guide:

* I agree with victor: biggest goal is styles that are html only-- no directives or extra stuff.  should be able to write HTML only.
* Getting rid of classes constrains us to perfectly semantic HTML, which can get in our way.  It also makes it harder to opt-out of styles when you want something different than the default.  Classes are a necessary evil, IMO.
* class-based glyphs are good-- much more stable than encoding glyphs as utf-8 escape sequences all over the place.
* forms should be generic with css classes for validation states and style guide for when to use those classes (charles has a nice email on this topic); want to allow defining forms without using mct-form and mct-control.)
* smaller & more stable components would be ideal-- at the level of flexibility that bootstrap would provide.   Need to focus on reusing styles as much as possible.

**Comment by larkin** [comment]
#382 has more detail on handling required fields and how we style form fields.

**Comment by VWoeltjen** [comment]
Goal for Kress: Set a stake in the ground for what we want style guide to look like. Don't necessarily want to refactor markup this sprint (to minimize risk); adding support while maintaining backwards compatibility may be reasonable (although still introduces some risk, since CSS selectors may apply in unexpected places)

**Comment by charlesh88** [comment]
Reviewing current style guide v1.0.0:

#### Content Changes
* Old edit mode > new edit mode. P1.
* Doc focuses on Espresso theme, colors and styles. Need to expand to generalize concepts around contrast. P1.
* Required field and form interaction; see notes on this in #382.
* Include theming. P2.
* Language has a lot of reference to WARP and VISTA; need to recast this as Open MCT. P1.
* "Fluid layout" should incorporate reference to usage of flexbox?  P3.
* More notes on gesture behavior:
 * How menus should operate, single-click to select and dismiss, click outside to dismiss, etc. P2.
 * Zoom/pan gestures and standards. P2.
* Add coverage for Notifications: blocking vs. non-blocking, message vs. status item, etc.  P1. 
* Mobile needs a lot of updates including UI wireframes swapped out with screen shots, notes on gestures and media queries, etc. P1.
* Update markup/CSS documentation: tables, menus, dropdowns, custom selects. Review each for markup that could be cleaned up/refactored. P1.

#### Markup/CSS refactoring candidates
* Glyphs to use CSS classes exclusively; currently inconsistent between the two different approaches. P1. Lots of small changes.
* Forms should use more common semantic elements, instead of .section-header, etc. P1. Low number of changes.
* Buttons should be able to be created with` <a class=".s-btn">` as with `<button>`. P2. Very easy.
* Verify that tabular displays are still semantic; also determine what needs to be documented to cover our current column sizing approach.

**Comment by charlesh88** [comment]
Per Jay week of Nov 7 this was pushed out to make way for GV design sprint and prototype building.

**Comment by charlesh88** [comment]
Done for now, closing.
